### ISSUE TITLE
Sequential XY Merge and Generation throws up error

### ISSUE THREAD

**Issue by rushuna86** [hako-mikan/sd-webui-supermerger#116]
Automatic1111 v1.4.0
Torch 2.0.1+cu118 with just built-in extension + super merger.

  File "D:\SD\WebUIX\extensions\sd-webui-supermerger\scripts\mergers\mergers.py", line 565, in get_font
    from fonts.ttf import Roboto
ModuleNotFoundError: No module named 'fonts'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\SD\WebUIX\extensions\sd-webui-supermerger\scripts\mergers\mergers.py", line 572, in get_font
    return ImageFont.truetype(shared.opts.font or 'javascript/roboto.ttf', fontsize)
  File "D:\SD\WebUIX\venv\lib\site-packages\PIL\ImageFont.py", line 996, in truetype
    return freetype(font)
  File "D:\SD\WebUIX\venv\lib\site-packages\PIL\ImageFont.py", line 993, in freetype
    return FreeTypeFont(font, size, index, encoding, layout_engine)
  File "D:\SD\WebUIX\venv\lib\site-packages\PIL\ImageFont.py", line 248, in __init__
    self.font = core.getfont(
OSError: cannot open resource

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\SD\WebUIX\venv\lib\site-packages\gradio\routes.py", line 422, in run_predict
    output = await app.get_blocks().process_api(
  File "D:\SD\WebUIX\venv\lib\site-packages\gradio\blocks.py", line 1323, in process_api
    result = await self.call_function(
  File "D:\SD\WebUIX\venv\lib\site-packages\gradio\blocks.py", line 1051, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "D:\SD\WebUIX\venv\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "D:\SD\WebUIX\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "D:\SD\WebUIX\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "D:\SD\WebUIX\extensions\sd-webui-supermerger\scripts\mergers\xyplot.py", line 52, in numanager
    result,currentmodel,xyimage,a,b,c= sgenxyplot(xtype,xmen,ytype,ymen,esettings,
  File "D:\SD\WebUIX\extensions\sd-webui-supermerger\scripts\mergers\xyplot.py", line 357, in sgenxyplot
    grid = smakegrid(xyimage,xs,ys,gridmodel,image_temp[4])
  File "D:\SD\WebUIX\extensions\sd-webui-supermerger\scripts\mergers\xyplot.py", line 374, in smakegrid
    grid = draw_origin(grid, currentmodel,w*len(xs),h*len(ys),w)
  File "D:\SD\WebUIX\extensions\sd-webui-supermerger\scripts\mergers\mergers.py", line 579, in draw_origin
    fnt = get_font(fontsize)
  File "D:\SD\WebUIX\extensions\sd-webui-supermerger\scripts\mergers\mergers.py", line 574, in get_font
    return ImageFont.truetype('javascript/roboto.ttf', fontsize)
  File "D:\SD\WebUIX\venv\lib\site-packages\PIL\ImageFont.py", line 996, in truetype
    return freetype(font)
  File "D:\SD\WebUIX\venv\lib\site-packages\PIL\ImageFont.py", line 993, in freetype
    return FreeTypeFont(font, size, index, encoding, layout_engine)
  File "D:\SD\WebUIX\venv\lib\site-packages\PIL\ImageFont.py", line 248, in __init__
    self.font = core.getfont(
OSError: cannot open resource

**Comment by hako-mikan** [comment]
You are using old version.
Update it.

**Comment by rushuna86** [comment]
nope commit [fc313940](https://github.com/hako-mikan/sd-webui-supermerger/commit/fc313940b2ae24961777d43b8db2957cfb592e38)

**Comment by hako-mikan** [comment]
`line 574, in get_font` means `get_font` is in line 574
in [fc313940](https://github.com/hako-mikan/sd-webui-supermerger/commit/fc313940b2ae24961777d43b8db2957cfb592e38) `get_font` is in line 666
So some problem may exist in your files.
You should dwonload mergers.py and overwhite it.

**Comment by rushuna86** [comment]
did what you said,

  File "D:\SD\WebUIX\extensions\sd-webui-supermerger\scripts\mergers\mergers.py", line 652, in get_font
    from fonts.ttf import Roboto
ModuleNotFoundError: No module named 'fonts'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\SD\WebUIX\extensions\sd-webui-supermerger\scripts\mergers\mergers.py", line 659, in get_font
    return ImageFont.truetype(shared.opts.font or 'javascript/roboto.ttf', fontsize)
  File "D:\SD\WebUIX\venv\lib\site-packages\PIL\ImageFont.py", line 996, in truetype
    return freetype(font)
  File "D:\SD\WebUIX\venv\lib\site-packages\PIL\ImageFont.py", line 993, in freetype
    return FreeTypeFont(font, size, index, encoding, layout_engine)
  File "D:\SD\WebUIX\venv\lib\site-packages\PIL\ImageFont.py", line 248, in __init__
    self.font = core.getfont(
OSError: cannot open resource

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\SD\WebUIX\venv\lib\site-packages\gradio\routes.py", line 422, in run_predict
    output = await app.get_blocks().process_api(
  File "D:\SD\WebUIX\venv\lib\site-packages\gradio\blocks.py", line 1323, in process_api
    result = await self.call_function(
  File "D:\SD\WebUIX\venv\lib\site-packages\gradio\blocks.py", line 1051, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "D:\SD\WebUIX\venv\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "D:\SD\WebUIX\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "D:\SD\WebUIX\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "D:\SD\WebUIX\extensions\sd-webui-supermerger\scripts\mergers\xyplot.py", line 52, in numanager
    result,currentmodel,xyimage,a,b,c= sgenxyplot(xtype,xmen,ytype,ymen,esettings,
  File "D:\SD\WebUIX\extensions\sd-webui-supermerger\scripts\mergers\xyplot.py", line 357, in sgenxyplot
    grid = smakegrid(xyimage,xs,ys,gridmodel,image_temp[4])
  File "D:\SD\WebUIX\extensions\sd-webui-supermerger\scripts\mergers\xyplot.py", line 374, in smakegrid
    grid = draw_origin(grid, currentmodel,w*len(xs),h*len(ys),w)
  File "D:\SD\WebUIX\extensions\sd-webui-supermerger\scripts\mergers\mergers.py", line 666, in draw_origin
    fnt = get_font(fontsize)
  File "D:\SD\WebUIX\extensions\sd-webui-supermerger\scripts\mergers\mergers.py", line 661, in get_font
    return ImageFont.truetype('javascript/roboto.ttf', fontsize)
  File "D:\SD\WebUIX\venv\lib\site-packages\PIL\ImageFont.py", line 996, in truetype
    return freetype(font)
  File "D:\SD\WebUIX\venv\lib\site-packages\PIL\ImageFont.py", line 993, in freetype
    return FreeTypeFont(font, size, index, encoding, layout_engine)
  File "D:\SD\WebUIX\venv\lib\site-packages\PIL\ImageFont.py", line 248, in __init__
    self.font = core.getfont(
OSError: cannot open resource

**Comment by rushuna86** [comment]
getting this exact error on a brand new clean install of automatic1111 with just supermerger installed

**Comment by hako-mikan** [comment]
May be fixed.

**Comment by hako-mikan** [comment]
Fixed. Thanks!

**Comment by rushuna86** [comment]
can confirmed has been fixed
