### ISSUE TITLE
AssertionError: duplicated lora name: lora_unet_down_blocks_0_attentions_0_transformer_blocks_0_attn1_to_q

### ISSUE THREAD

**Issue by shawpook** [hako-mikan/sd-webui-supermerger#122]
I encountered the same error when trying to extract lora using different models.

Traceback (most recent call last):
  File "D:\webui\sd-webui\python\lib\site-packages\gradio\routes.py", line 408, in run_predict
    output = await app.get_blocks().process_api(
  File "D:\webui\sd-webui\python\lib\site-packages\gradio\blocks.py", line 1315, in process_api
    result = await self.call_function(
  File "D:\webui\sd-webui\python\lib\site-packages\gradio\blocks.py", line 1043, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "D:\webui\sd-webui\python\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "D:\webui\sd-webui\python\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "D:\webui\sd-webui\python\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "D:\webui\sd-webui\extensions\sd-webui-supermerger-main\scripts\mergers\pluslora.py", line 157, in makelora
    svd(fullpathfromname(model_a),fullpathfromname(model_b),False,dim,precision,saveto,alpha,beta)
  File "D:\webui\sd-webui\extensions\sd-webui-supermerger-main\scripts\mergers\pluslora.py", line 445, in svd
    lora_network_o = create_network(1.0, dim, dim, None, text_encoder_o, unet_o)
  File "D:\webui\sd-webui\extensions\sd-webui-supermerger-main\scripts\mergers\pluslora.py", line 993, in create_network
    network = LoRANetwork(
  File "D:\webui\sd-webui\extensions\sd-webui-supermerger-main\scripts\mergers\pluslora.py", line 1096, in __init__
    assert lora.lora_name not in names, f"duplicated lora name: {lora.lora_name}"
AssertionError: duplicated lora name: lora_unet_down_blocks_0_attentions_0_transformer_blocks_0_attn1_to_q

**Comment by shawpook** [comment]
I commented out this check. If there are any similar issues, you can comment out the code before using it.

**Comment by hako-mikan** [comment]
Downgrade the version of diffusers to 0.14 or lower.
https://github.com/hako-mikan/sd-webui-supermerger/discussions/52
https://github.com/hako-mikan/sd-webui-supermerger/issues/97
https://github.com/hako-mikan/sd-webui-supermerger/issues/111
