### ISSUE TITLE
raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format( RuntimeError: Error(s) in loading state_dict for AutoencoderKL:

### ISSUE THREAD

**Issue by JFweimo** [hako-mikan/sd-webui-supermerger#125]
make LoRA start
loading SD model : D:\AI\sd-webui-aki-V4\sd-webui-aki-v4.1\models\Stable-diffusion\2-KWI-1.1.safetensors
diffusers version :  0.17.1
version of diffusers must be 0.10.2 to 0.14.0
loading u-net: <All keys matched successfully>
Traceback (most recent call last):
  File "D:\AI\sd-webui-aki-V4\sd-webui-aki-v4.1\python\lib\site-packages\gradio\routes.py", line 422, in run_predict
    output = await app.get_blocks().process_api(
  File "D:\AI\sd-webui-aki-V4\sd-webui-aki-v4.1\python\lib\site-packages\gradio\blocks.py", line 1323, in process_api
    result = await self.call_function(
  File "D:\AI\sd-webui-aki-V4\sd-webui-aki-v4.1\python\lib\site-packages\gradio\blocks.py", line 1051, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "D:\AI\sd-webui-aki-V4\sd-webui-aki-v4.1\python\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "D:\AI\sd-webui-aki-V4\sd-webui-aki-v4.1\python\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "D:\AI\sd-webui-aki-V4\sd-webui-aki-v4.1\python\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "D:\AI\sd-webui-aki-V4\sd-webui-aki-v4.1\extensions\sd-webui-supermerger\scripts\mergers\pluslora.py", line 159, in makelora
    svd(fullpathfromname(model_a),fullpathfromname(model_b),False,dim,precision,saveto,alpha,beta)
  File "D:\AI\sd-webui-aki-V4\sd-webui-aki-v4.1\extensions\sd-webui-supermerger\scripts\mergers\pluslora.py", line 453, in svd
    text_encoder_o, _, unet_o = load_models_from_stable_diffusion_checkpoint(v2, model_b)
  File "D:\AI\sd-webui-aki-V4\sd-webui-aki-v4.1\extensions\sd-webui-supermerger\scripts\mergers\model_util.py", line 748, in load_models_from_stable_diffusion_checkpoint
    info = vae.load_state_dict(converted_vae_checkpoint)
  File "D:\AI\sd-webui-aki-V4\sd-webui-aki-v4.1\python\lib\site-packages\torch\nn\modules\module.py", line 2041, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for AutoencoderKL:
提示：Python 运行时抛出了一个异常。请检查疑难解答页面。
	Missing key(s) in state_dict: "encoder.mid_block.attentions.0.to_q.weight", "encoder.mid_block.attentions.0.to_q.bias", "encoder.mid_block.attentions.0.to_k.weight", "encoder.mid_block.attentions.0.to_k.bias", "encoder.mid_block.attentions.0.to_v.weight", "encoder.mid_block.attentions.0.to_v.bias", "encoder.mid_block.attentions.0.to_out.0.weight", "encoder.mid_block.attentions.0.to_out.0.bias", "decoder.mid_block.attentions.0.to_q.weight", "decoder.mid_block.attentions.0.to_q.bias", "decoder.mid_block.attentions.0.to_k.weight", "decoder.mid_block.attentions.0.to_k.bias", "decoder.mid_block.attentions.0.to_v.weight", "decoder.mid_block.attentions.0.to_v.bias", "decoder.mid_block.attentions.0.to_out.0.weight", "decoder.mid_block.attentions.0.to_out.0.bias". 
	Unexpected key(s) in state_dict: "encoder.mid_block.attentions.0.key.bias", "encoder.mid_block.attentions.0.key.weight", "encoder.mid_block.attentions.0.proj_attn.bias", "encoder.mid_block.attentions.0.proj_attn.weight", "encoder.mid_block.attentions.0.query.bias", "encoder.mid_block.attentions.0.query.weight", "encoder.mid_block.attentions.0.value.bias", "encoder.mid_block.attentions.0.value.weight", "decoder.mid_block.attentions.0.key.bias", "decoder.mid_block.attentions.0.key.weight", "decoder.mid_block.attentions.0.proj_attn.bias", "decoder.mid_block.attentions.0.proj_attn.weight", "decoder.mid_block.attentions.0.query.bias", "decoder.mid_block.attentions.0.query.weight", "decoder

**Comment by hako-mikan** [comment]
`diffusers version : 0.17.1
version of diffusers must be 0.10.2 to 0.14.0`
