### ISSUE TITLE
After merge lora into a checkpoint model. i got this error when load this merged checkpoint into sd webui

### ISSUE THREAD

**Issue by tttonytan** [hako-mikan/sd-webui-supermerger#126]
Traceback (most recent call last):
  File "/home/ubuntu/stable-diffusion-webui/modules/shared.py", line 483, in set
    self.data_labels[key].onchange()
  File "/home/ubuntu/stable-diffusion-webui/modules/call_queue.py", line 15, in f
    res = func(*args, **kwargs)
  File "/home/ubuntu/stable-diffusion-webui/webui.py", line 149, in <lambda>
    shared.opts.onchange("sd_model_checkpoint", wrap_queued_call(lambda: modules.sd_models.reload_model_weights()))
  File "/home/ubuntu/stable-diffusion-webui/modules/sd_models.py", line 496, in reload_model_weights
    state_dict = get_checkpoint_state_dict(checkpoint_info, timer)
  File "/home/ubuntu/stable-diffusion-webui/modules/sd_models.py", line 262, in get_checkpoint_state_dict
    res = read_state_dict(checkpoint_info.filename)
  File "/home/ubuntu/stable-diffusion-webui/modules/sd_models.py", line 248, in read_state_dict
    sd = get_state_dict_from_checkpoint(pl_sd)
  File "/home/ubuntu/stable-diffusion-webui/modules/sd_models.py", line 197, in get_state_dict_from_checkpoint
    pl_sd = pl_sd.pop("state_dict", pl_sd)
AttributeError: 'NoneType' object has no attribute 'pop'

**Comment by tttonytan** [comment]
how can i solve this error to use the merged checkpoint

**Comment by hako-mikan** [comment]
try following,
restart web-ui
change filename of merged model
