### ISSUE TITLE
AttributeError: 'Namespace' object has no attribute 'upcast_sampling'

### ISSUE THREAD

**Issue by SimonY2** [hako-mikan/sd-webui-supermerger#14]
I found this error like that:
Traceback (most recent call last):
  File "/root/miniconda3/lib/python3.8/site-packages/gradio/routes.py", line 337, in run_predict
    output = await app.get_blocks().process_api(
  File "/root/miniconda3/lib/python3.8/site-packages/gradio/blocks.py", line 1015, in process_api
    result = await self.call_function(
  File "/root/miniconda3/lib/python3.8/site-packages/gradio/blocks.py", line 833, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/root/miniconda3/lib/python3.8/site-packages/anyio/to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/root/miniconda3/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "/root/miniconda3/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "/root/autodl-tmp/stable-diffusion-webui/extensions/sd-webui-supermerger-main/scripts/mergers/xyplot.py", line 26, in numanager
    result,currentmodel,xyimage,a,b,c= sgenxyplot(xtype,xmen,ytype,ymen,
  File "/root/autodl-tmp/stable-diffusion-webui/extensions/sd-webui-supermerger-main/scripts/mergers/xyplot.py", line 246, in sgenxyplot
    usemodelgen(theta_0,model_a)
  File "/root/autodl-tmp/stable-diffusion-webui/extensions/sd-webui-supermerger-main/scripts/mergers/model_util.py", line 806, in usemodelgen
    devices.unet_needs_upcast = shared.cmd_opts.upcast_sampling and devices.dtype == torch.float16 and devices.dtype_unet == torch.float16
AttributeError: 'Namespace' object has no attribute 'upcast_sampling'

I wonder if it's my fault.

**Comment by hako-mikan** [comment]
This error occurs when referring to data in web-ui itself, and may be resolved by restarting web-ui or updating to the latest version. If the error still occurs, please let us know the startup condition "--xformers" etc.

**Comment by hako-mikan** [comment]
This error occurs when referring to data in web-ui itself, and may be resolved by restarting web-ui or updating to the latest version. If the error still occurs, please let me know the startup condition "--xformers" etc.
