### ISSUE TITLE
Error On Saving Merged LoRA & Checkpoint w/Automatic1111-1.4.0

### ISSUE THREAD

**Issue by jrittvo** [hako-mikan/sd-webui-supermerger#145]
Since updating Automatic1111 to 1.4.0, I receive this error each time I try to merge a safetensors LoRA and a safeensors checkpoint.  Never has this issue before the update.  I have not tried with .ckpts instead of .safetensors yet.  LoRAs seem to always be .safetensors.

Any suggestions?

MacBook M1 Pro, 16GB,  macOS 13.4

python 3.10.12
diffusers 0.17.1
torch 2.0.1
safetensors 0.3.1 
gradio 3.32.0 
anyio 3.7.0

Saving...
Traceback (most recent call last):
  File "/Users/jrittvo/Auto1111/Auto1111 WebUI/venv/lib/python3.10/site-packages/gradio/routes.py", line 422, in run_predict
    output = await app.get_blocks().process_api(
  File "/Users/jrittvo/Auto1111/Auto1111 WebUI/venv/lib/python3.10/site-packages/gradio/blocks.py", line 1323, in process_api
    result = await self.call_function(
  File "/Users/jrittvo/Auto1111/Auto1111 WebUI/venv/lib/python3.10/site-packages/gradio/blocks.py", line 1051, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/Users/jrittvo/Auto1111/Auto1111 WebUI/venv/lib/python3.10/site-packages/anyio/to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/Users/jrittvo/Auto1111/Auto1111 WebUI/venv/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "/Users/jrittvo/Auto1111/Auto1111 WebUI/venv/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "/Users/jrittvo/Auto1111/Auto1111 WebUI/extensions/sd-webui-supermerger/scripts/mergers/pluslora.py", line 366, in pluslora
    result = savemodel(theta_0,dname,output,settings,model)
  File "/Users/jrittvo/Auto1111/Auto1111 WebUI/extensions/sd-webui-supermerger/scripts/mergers/model_util.py", line 708, in savemodel
    safetensors.torch.save_file(state_dict, fname, metadata=metadata)
  File "/Users/jrittvo/Auto1111/Auto1111 WebUI/venv/lib/python3.10/site-packages/safetensors/torch.py", line 232, in save_file
    serialize_file(_flatten(tensors), filename, metadata=metadata)
safetensors_rust.SafetensorError: Error while serializing: IoError(Os { code: 2, kind: NotFound, message: "No such file or directory" })

**Comment by hako-mikan** [comment]
It may be a file name issue. Are you specifying a file name?

**Comment by jrittvo** [comment]
Nope. Letting it create the name. 

I still have my Auto1111 1.3.2 install, and using the same models and merge settings, it works fine. 

Is there any way to see the name and path it is trying to use?  Like adding some sort of “print” command command a line or two ahead of the code, in that last script where the “save” triggers the trace back?
