### ISSUE TITLE
ModuleNotFoundError: No module named 'tkinter'

### ISSUE THREAD

**Issue by swumagic** [hako-mikan/sd-webui-supermerger#150]
*** Error loading script: supermerger.py
    Traceback (most recent call last):
      File "M:\SD\sdwebui\modules\scripts.py", line 274, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "M:\SD\sdwebui\modules\script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "M:\SD\sdwebui\extensions\sd-webui-supermerger\scripts\supermerger.py", line 10, in <module>
        from tkinter import W
    ModuleNotFoundError: No module named 'tkinter'

**Comment by xil64** [comment]
I have the same issue after update.

**Comment by hako-mikan** [comment]
Fixed.
