### ISSUE TITLE
Get an Error after "set to alpha"

### ISSUE THREAD

**Issue by miasik** [hako-mikan/sd-webui-supermerger#151]
I'm still getting the error

![изображение](https://github.com/hako-mikan/sd-webui-supermerger/assets/1073832/6a8fb802-c1c9-414a-b0f1-a75eb0ad204a)

> Traceback (most recent call last):
  File "e:\SD\automatic1111\venv\lib\site-packages\gradio\routes.py", line 422, in run_predict
    output = await app.get_blocks().process_api(
  File "e:\SD\automatic1111\venv\lib\site-packages\gradio\blocks.py", line 1323, in process_api
    result = await self.call_function(
  File "e:\SD\automatic1111\venv\lib\site-packages\gradio\blocks.py", line 1051, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "e:\SD\automatic1111\venv\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "e:\SD\automatic1111\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "e:\SD\automatic1111\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "E:\SD\automatic1111\extensions\sd-webui-supermerger\scripts\supermerger.py", line 623, in slider2text
    if any(element in w for element in RANCHA):return w
  File "E:\SD\automatic1111\extensions\sd-webui-supermerger\scripts\supermerger.py", line 623, in <genexpr>
    if any(element in w for element in RANCHA):return w
TypeError: argument of type 'NoneType' is not iterable

_Originally posted by @miasik in https://github.com/hako-mikan/sd-webui-supermerger/discussions/139#discussioncomment-6338304_

**Comment by miasik** [comment]
> Traceback (most recent call last):
  File "e:\SD\automatic1111\venv\lib\site-packages\gradio\routes.py", line 422, in run_predict
    output = await app.get_blocks().process_api(
  File "e:\SD\automatic1111\venv\lib\site-packages\gradio\blocks.py", line 1323, in process_api
    result = await self.call_function(
  File "e:\SD\automatic1111\venv\lib\site-packages\gradio\blocks.py", line 1051, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "e:\SD\automatic1111\venv\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "e:\SD\automatic1111\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "e:\SD\automatic1111\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "E:\SD\automatic1111\extensions\sd-webui-supermerger\scripts\supermerger.py", line 623, in slider2text
    if any(element in az for element in RANCHA):return az
  File "E:\SD\automatic1111\extensions\sd-webui-supermerger\scripts\supermerger.py", line 623, in <genexpr>
    if any(element in az for element in RANCHA):return az
TypeError: argument of type 'NoneType' is not iterable

**Comment by hako-mikan** [comment]
Fixed.
