### ISSUE TITLE
Error after update

### ISSUE THREAD

**Issue by Neytiri7** [hako-mikan/sd-webui-supermerger#160]
*** Error loading script: supermerger.py
    Traceback (most recent call last):
      File "O:\AI\SynologyDrive\stable-diffusion-webui\modules\scripts.py", line 274, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "O:\AI\SynologyDrive\stable-diffusion-webui\modules\script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "O:\AI\SynologyDrive\stable-diffusion-webui\extensions\sd-webui-supermerger\scripts\supermerger.py", line 26, in <module>
        from scripts.mergers.mergers import (TYPESEG, freezemtime, rwmergelog, simggen,smergegen, blockfromkey, numfromblock)
    ImportError: cannot import name 'numfromblock' from 'scripts.mergers.mergers' (O:\AI\SynologyDrive\stable-diffusion-webui\extensions\sd-webui-supermerger\scripts\mergers\mergers.py)

**Comment by hako-mikan** [comment]
Thanks!
Wrong file was uploaded.

**Comment by Neytiri7** [comment]
Thanks!
