### ISSUE TITLE
ValueError: too many values to unpack (expected 2) Error in Weight sum on recent commit

### ISSUE THREAD

**Issue by Nerogante** [hako-mikan/sd-webui-supermerger#161]
Default parameters, Use MBW
Console Output

Model loaded in 5.3s (load weights from disk: 1.0s, create model: 0.7s, apply weights to model: 0.7s, load VAE: 0.5s, load textual inversion embeddings: 0.1s, calculate empty prompt: 2.2s).
  model A       : colorful_v31
  model B       : r_asian
  model C       :
  alpha,beta    : (0.5, 0.25)
  weights_alpha : [0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5]
  weights_beta  : 0.2,0.2,0.2,0.2,0.2,0.2,0.2,0.2,0.2,0.2,0.2,0.2,0.2,0.2,0.2,0.2,0.2,0.2,0.2,0.2,0.2,0.2,0.2,0.2,0.2,0.2
  mode          : Weight sum:A*(1-alpha)+B*alpha
  MBW           : True
  CalcMode      : normal
  Elemental     :
  Weights Seed  : 3142284055
  Adjust        :
Unloaded weights 0.0s.
Loading weights [r_asian] from file
Loading weights [f04fdb4a9e] from C:\stable-diffusion-webui\models\Stable-diffusion\colorful_v31.safetensors
Creating model from config: C:\stable-diffusion-webui\configs\v1-inference.yaml
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
Loading VAE weights specified in settings: C:\stable-diffusion-webui\models\VAE\vae-ft-mse-840000-ema-pruned.ckpt
Applying attention optimization: xformers... done.
Model loaded in 2.7s (load weights from disk: 0.3s, create model: 0.5s, apply weights to model: 0.6s, load VAE: 0.8s, calculate empty prompt: 0.4s).
Loading weights [colorful_v31] from file
Stage 1/2:   0%|                                                                              | 0/1131 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "C:\stable-diffusion-webui\venv\lib\site-packages\gradio\routes.py", line 422, in run_predict
    output = await app.get_blocks().process_api(
  File "C:\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1323, in process_api
    result = await self.call_function(
  File "C:\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1051, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "C:\stable-diffusion-webui\venv\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "C:\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "C:\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "C:\stable-diffusion-webui\extensions\sd-webui-supermerger\scripts\mergers\mergers.py", line 89, in smergegen
    result,currentmodel,modelid,theta_0,metadata = smerge(
  File "C:\stable-diffusion-webui\extensions\sd-webui-supermerger\scripts\mergers\mergers.py", line 356, in smerge
    block,blocks26 = blockfromkey(key,isxl)
ValueError: too many values to unpack (expected 2)

(Don't know how to style this)

Manually reverted to commit https://github.com/hako-mikan/sd-webui-supermerger/tree/a027d5a9e1c7fc20a27df3882d0d914609953df0 stable and working

**Comment by Ketorami** [comment]
I also encountered an error, and I'm not sure why. It was working fine before

**Comment by Nerogante** [comment]
> I also encountered an error, and I'm not sure why. It was working fine before. ![Screenshot 2023-07-25 050909](https://user-images.githubusercontent.com/101268214/255732435-e9ca3161-cec5-48ee-a5a9-d5bdb7f4ab8c.png)

In the meantime you can download the commit I linked and replace your current folder ("C:\stable-diffusion-webui\extensions\sd-webui-supermerger" in my case) with the corresponding contents in the zip

**Comment by Neytiri7** [comment]
File "O:\AI\SynologyDrive\stable-diffusion-webui\venv\lib\site-packages\gradio\routes.py", line 422, in run_predict
    output = await app.get_blocks().process_api(
  File "O:\AI\SynologyDrive\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1323, in process_api
    result = await self.call_function(
  File "O:\AI\SynologyDrive\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1051, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "O:\AI\SynologyDrive\stable-diffusion-webui\venv\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "O:\AI\SynologyDrive\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "O:\AI\SynologyDrive\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "O:\AI\SynologyDrive\stable-diffusion-webui\extensions\sd-webui-supermerger\scripts\mergers\mergers.py", line 89, in smergegen
    result,currentmodel,modelid,theta_0,metadata = smerge(
  File "O:\AI\SynologyDrive\stable-diffusion-webui\extensions\sd-webui-supermerger\scripts\mergers\mergers.py", line 356, in smerge
    block,blocks26 = blockfromkey(key,isxl)
ValueError: too many values to unpack (expected 2)

**Comment by hako-mikan** [comment]
Thanks fixed.
