### ISSUE TITLE
not shown on UI

### ISSUE THREAD

**Issue by konokomi** [hako-mikan/sd-webui-supermerger#164]
Error executing callback ui_tabs_callback for E:\AI SD 1.5\stable-diffusion-webui-master\extensions\sd-webui-supermerger\scripts\supermerger.py
Traceback (most recent call last):
  File "E:\AI SD 1.5\stable-diffusion-webui-master\modules\script_callbacks.py", line 125, in ui_tabs_callback
    res += c.callback() or []
  File "E:\AI SD 1.5\stable-diffusion-webui-master\extensions\sd-webui-supermerger\scripts\supermerger.py", line 339, in on_ui_tabs
    smd_lora = gr.Dropdown(lora.available_loras.keys(),elem_id="model_converter_model_name",label="Checkpoint A",interactive=True)
  File "E:\AI SD 1.5\stable-diffusion-webui-master\venv\lib\site-packages\gradio\components.py", line 1306, in __init__
    self.test_input = self.choices[0] if len(self.choices) else None
TypeError: 'dict_keys' object is not subscriptable

**Comment by konokomi** [comment]
have to roll back to version 11.It's working now. Latest versions have the above problem.
