### ISSUE TITLE
Error when merging SDXL Model and SDXL Lora

### ISSUE THREAD

**Issue by Neytiri7** [hako-mikan/sd-webui-supermerger#168]
Traceback (most recent call last):
  File "O:\AI\SynologyDrive\venv\lib\site-packages\gradio\routes.py", line 422, in run_predict
    output = await app.get_blocks().process_api(
  File "O:\AI\SynologyDrive\venv\lib\site-packages\gradio\blocks.py", line 1323, in process_api
    result = await self.call_function(
  File "O:\AI\SynologyDrive\venv\lib\site-packages\gradio\blocks.py", line 1051, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "O:\AI\SynologyDrive\venv\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "O:\AI\SynologyDrive\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "O:\AI\SynologyDrive\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "O:\AI\SynologyDrive\extensions\sd-webui-supermerger\scripts\mergers\pluslora.py", line 524, in pluslora
    theta_0 = newpluslora(theta_0,filenames,lweis,names, isxl, keychanger)
  File "O:\AI\SynologyDrive\extensions\sd-webui-supermerger\scripts\mergers\pluslora.py", line 600, in newpluslora
    lbw(nets.loaded_networks[l],to26(lweis[n]))
  File "O:\AI\SynologyDrive\extensions\sd-webui-supermerger\scripts\mergers\pluslora.py", line 689, in lbw
    lora.modules[key].up.weight= torch.nn.Parameter(lora.modules[key].up.weight *ratio)
AttributeError: 'NetworkModuleHada' object has no attribute 'up'

**Comment by hako-mikan** [comment]
may be fixed
