### ISSUE TITLE
Error loading script.   

### ISSUE THREAD

**Issue by jcbordo** [hako-mikan/sd-webui-supermerger#173]
After the recent update I get an error loading script.  I think maybe components is not being called correctly?  This is the error:

*** Error loading script: supermerger.py
    Traceback (most recent call last):
      File "C:\Users\xxxx\Desktop\Automatic1111\stable-diffusion-webui\modules\scripts.py", line 319, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "C:\Users\xxxx\Desktop\Automatic1111\stable-diffusion-webui\modules\script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "C:\Users\xxxx\Desktop\Automatic1111\stable-diffusion-webui\extensions\sd-webui-supermerger\scripts\supermerger.py", line 20, in <module>
        import scripts.components.components as components
    ModuleNotFoundError: No module named 'scripts.components'

**Comment by hako-mikan** [comment]
Thanks fixed.

**Comment by jcbordo** [comment]
Awesome!  And thank you for all your hard work!
