### ISSUE TITLE
Error when launching Web UI with gradio version is latest

### ISSUE THREAD

**Issue by Uminosachi** [hako-mikan/sd-webui-supermerger#175]
If I update the version 3.39.0 of the Gradio package, an error occurs when launching the Web UI, specifically reporting that the 'gradio.components' module has no attribute 'BlockContext'.

```bash
*** Error executing callback app_started_callback for /stable-diffusion-webui/extensions/sd-webui-supermerger/scripts/GenParamGetter.py
    Traceback (most recent call last):
      File "/stable-diffusion-webui/modules/script_callbacks.py", line 126, in app_started_callback
        c.callback(demo, app)
      File "/stable-diffusion-webui/extensions/sd-webui-supermerger/scripts/GenParamGetter.py", line 54, in get_params_components
        outputs = GenParamGetter.get_components_by_ids(demo, d["outputs"])
      File "/stable-diffusion-webui/extensions/sd-webui-supermerger/scripts/GenParamGetter.py", line 37, in get_components_by_ids
        if isinstance(root, gr.components.BlockContext):
    AttributeError: module 'gradio.components' has no attribute 'BlockContext'
```

**Comment by Uminosachi** [comment]
Additional Information: This issue occurs within the 'dev' branch of the web UI.

**Comment by hako-mikan** [comment]
Maybe fixed.

**Comment by Uminosachi** [comment]
I checked with the latest dev branch of the web UI and it seems there is another issue.

```bash
*** Error executing callback app_started_callback for /stable-diffusion-webui/extensions/sd-webui-supermerger/scripts/GenParamGetter.py
    Traceback (most recent call last):
      File "/stable-diffusion-webui/modules/script_callbacks.py", line 126, in app_started_callback
        c.callback(demo, app)
      File "/stable-diffusion-webui/extensions/sd-webui-supermerger/scripts/GenParamGetter.py", line 57, in get_params_components
        output = outputs[0]
    IndexError: list index out of range
```

**Comment by hako-mikan** [comment]
I think it will be OK this time.

**Comment by Uminosachi** [comment]
I've confirmed that there are no errors, so I'm going to close this issue.
