### ISSUE TITLE
KeyError: 'lora_te_text_model_encoder_layers_0_mlp_fc1.hada_w1_'

### ISSUE THREAD

**Issue by aftermath0703** [hako-mikan/sd-webui-supermerger#177]
I got an error when merging LoHa into checkpoint.

The error is below.
```
merging D:\projects\stable-diffusion-webui\models\LyCORIS\multi-view-loha-000001.safetensors: [1.0, 0.0, 0.5, 0.0, 0.5, 0.5, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0]
dim: [], alpha: [64.0, 1.0]
merging...
Traceback (most recent call last):
  File "D:\projects\stable-diffusion-webui\extensions\sd-webui-supermerger\scripts\mergers\pluslora.py", line 283, in lmerge
    sd = merge_lora_models(ln, lr, settings, True)
  File "D:\projects\stable-diffusion-webui\extensions\sd-webui-supermerger\scripts\mergers\pluslora.py", line 338, in merge_lora_models
    base_alpha = base_alphas[lora_module_name]
KeyError: 'lora_te_text_model_encoder_layers_0_mlp_fc1.hada_w1_'
```

How can I solve it?

**Comment by aftermath0703** [comment]
I solved it, the end of the loha layer is named ".hada" instead of ".lora", seems like a bug?
