### ISSUE TITLE
"IndexError: list index out of range" for EX or custom in "dice roll"

### ISSUE THREAD

**Issue by miasik** [hako-mikan/sd-webui-supermerger#183]
I want to use full elemental random merging limiting only the base block but get the same error both for EX and custom

> Stage 1/2:   1%|█▌                                                                                                                                                        | 12/1143 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "e:\SD\automatic1111\venv\lib\site-packages\gradio\routes.py", line 422, in run_predict
    output = await app.get_blocks().process_api(
  File "e:\SD\automatic1111\venv\lib\site-packages\gradio\blocks.py", line 1323, in process_api
    result = await self.call_function(
  File "e:\SD\automatic1111\venv\lib\site-packages\gradio\blocks.py", line 1051, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "e:\SD\automatic1111\venv\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "e:\SD\automatic1111\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "e:\SD\automatic1111\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "E:\SD\automatic1111\extensions\sd-webui-supermerger\scripts\mergers\xyplot.py", line 68, in numanager
    result,currentmodel,xyimage,a,b,c= sgenxyplot(*allsets)
  File "E:\SD\automatic1111\extensions\sd-webui-supermerger\scripts\mergers\xyplot.py", line 381, in sgenxyplot
    _, currentmodel,modelid,theta_0, metadata =smerge(weights_a_in,weights_b_in, model_a,model_b,model_c, float(alpha),float(beta),mode,calcmode,
  File "E:\SD\automatic1111\extensions\sd-webui-supermerger\scripts\mergers\mergers.py", line 379, in smerge
    dr = eratiodealer(dr,randomer,weight_index+1,num,lucks)
  File "E:\SD\automatic1111\extensions\sd-webui-supermerger\scripts\mergers\mergers.py", line 924, in eratiodealer
    return round((float(low[block])-float(up[block]))* randomer[num+add] + float(up[block]),lucks["round"])
IndexError: list index out of range

![изображение](https://github.com/hako-mikan/sd-webui-supermerger/assets/1073832/f101abaa-3e24-4d2f-bfef-73b0f5ebd534)

**Comment by miasik** [comment]
I've just found that the mistakes happens if I set the last block (OUT11) to EX and it works with all other block set to EX (except OUT11)

> XY plot: X: random, , Y: random, , Z: none,  (1/1.0)
  model A       : Porn_(vrP3-TrD-MBW-iFM45-86045)-TrD-MBW-NePh3-86079.fp16
  model B       : Photo_UniverseStable.v6@sd.fp16
  model C       : v1-5-pruned-emaonly
  alpha,beta    : (0.0, 0.25)
  weights_alpha : [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
  weights_beta  : 0.2,0.2,0.2,0.2,0.2,0.2,0.2,0.2,0.2,0.2,0.2,0.2,0.2,0.2,0.2,0.2,0.2,0.2,0.2,0.2,0.2,0.2,0.2,0.2,0.2,0.2
  mode          : Weight sum:A*(1-alpha)+B*alpha
  MBW           : True
  CalcMode      : normal
  Elemental     : ['BASE IN00 IN01 IN02 IN03 IN04 IN05 IN06 IN07 IN08 IN09 IN10 IN11 M00 OUT00 OUT01 OUT02 OUT03 OUT04 OUT05 OUT06 OUT07 OUT08 OUT09 OUT10 OUT11::X']
  Weights Seed  : 1954068290
  Adjust        : [1.0, 1.0, 1.0, 1.0, 1.0, [0.0, 0.0, 0.0, 0.0]]
Loading weights [Photo_UniverseStable.v6@sd.fp16] from cache
Loading weights [Porn_(vrP3-TrD-MBW-iFM45-86045)-TrD-MBW-NePh3-86079.fp16] from cache
Stage 1/2:   1%|█▌                                                                                                                                                        | 12/1143 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "e:\SD\automatic1111\venv\lib\site-packages\gradio\routes.py", line 422, in run_predict
    output = await app.get_blocks().process_api(
  File "e:\SD\automatic1111\venv\lib\site-packages\gradio\blocks.py", line 1323, in process_api
    result = await self.call_function(
  File "e:\SD\automatic1111\venv\lib\site-packages\gradio\blocks.py", line 1051, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "e:\SD\automatic1111\venv\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "e:\SD\automatic1111\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "e:\SD\automatic1111\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "E:\SD\automatic1111\extensions\sd-webui-supermerger\scripts\mergers\xyplot.py", line 68, in numanager
    result,currentmodel,xyimage,a,b,c= sgenxyplot(*allsets)
  File "E:\SD\automatic1111\extensions\sd-webui-supermerger\scripts\mergers\xyplot.py", line 381, in sgenxyplot
    _, currentmodel,modelid,theta_0, metadata =smerge(weights_a_in,weights_b_in, model_a,model_b,model_c, float(alpha),float(beta),mode,calcmode,
  File "E:\SD\automatic1111\extensions\sd-webui-supermerger\scripts\mergers\mergers.py", line 379, in smerge
    dr = eratiodealer(dr,randomer,weight_index+1,num,lucks)
  File "E:\SD\automatic1111\extensions\sd-webui-supermerger\scripts\mergers\mergers.py", line 924, in eratiodealer
    return round((float(low[block])-float(up[block]))* randomer[num+add] + float(up[block]),lucks["round"])
IndexError: list index out of range

**Comment by hako-mikan** [comment]
fixed

**Comment by miasik** [comment]
Thank you!
