### ISSUE TITLE
Stopped working using the latest SD.Next build (Vladmatic)

### ISSUE THREAD

**Issue by Xerdunits** [hako-mikan/sd-webui-supermerger#187]
I can't seem to get Super-merger to work correctly. I think it has to do with available sampling methods.

`Creating model from config: /workspace/automatic/configs/v1-inference.yaml
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
13:52:29-879457 INFO     Applying scaled dot product cross attention optimization                                                                                                                                        
Model loaded in 2.4s (create model=0.6s apply weights to model=1.1s move model to device=0.6s calculate empty prompt=0.1s).
Traceback (most recent call last):
  File "/workspace/venv/lib/python3.10/site-packages/gradio/routes.py", line 422, in run_predict
    output = await app.get_blocks().process_api(
  File "/workspace/venv/lib/python3.10/site-packages/gradio/blocks.py", line 1323, in process_api
    result = await self.call_function(
  File "/workspace/venv/lib/python3.10/site-packages/gradio/blocks.py", line 1051, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/workspace/venv/lib/python3.10/site-packages/anyio/to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/workspace/venv/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "/workspace/venv/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "/workspace/automatic/extensions/sd-webui-supermerger/scripts/mergers/mergers.py", line 102, in smergegen
    images = simggen(s_prompt,s_nprompt,s_steps,s_sampler,s_cfg,s_seed,s_w,s_h,s_batch_size,
  File "/workspace/automatic/extensions/sd-webui-supermerger/scripts/mergers/mergers.py", line 942, in simggen
    override_settings = create_override_settings_dict(override_settings_texts)
  File "/workspace/automatic/modules/generation_parameters_copypaste.py", line 330, in create_override_settings_dict
    for pair in text_pairs:
TypeError: 'int' object is not iterable`
![image](https://github.com/hako-mikan/sd-webui-supermerger/assets/35238523/9f9068a9-aa19-4986-8280-000bf6047af4)
I'm not using all the samplers, but they are shown nonetheless.

**Comment by hako-mikan** [comment]
I've probably been able to fix it, but there are many changes, so there might be a bug somewhere. 
This is a fix for Vlad and web-ui 1.6.
