### ISSUE TITLE
Does not work at 1.6.0.

### ISSUE THREAD

**Issue by Neytiri7** [hako-mikan/sd-webui-supermerger#196]
This error is displayed when you start the webUI.

```
O:\AI\SynologyDrive\stable-diffusion-webui\extensions\sd-webui-supermerger\scripts\supermerger.py:56: GradioDeprecationWarning: The `style` method is deprecated. Please set these arguments in the constructor instead.
  with gr.Row().style(equal_height=False):
O:\AI\SynologyDrive\stable-diffusion-webui\extensions\sd-webui-supermerger\scripts\mergers\pluslora.py:70: GradioDeprecationWarning: The `style` method is deprecated. Please set these arguments in the constructor instead.
  with gr.Row().style(equal_height=False):
O:\AI\SynologyDrive\stable-diffusion-webui\extensions\sd-webui-supermerger\scripts\mergers\pluslora.py:77: GradioDeprecationWarning: The `style` method is deprecated. Please set these arguments in the constructor instead.
  with gr.Row().style(equal_height=False):
O:\AI\SynologyDrive\stable-diffusion-webui\extensions\sd-webui-supermerger\scripts\mergers\pluslora.py:81: GradioDeprecationWarning: The `style` method is deprecated. Please set these arguments in the constructor instead.
  with gr.Row().style(equal_height=False):
O:\AI\SynologyDrive\stable-diffusion-webui\extensions\sd-webui-supermerger\scripts\mergers\pluslora.py:84: GradioDeprecationWarning: The `style` method is deprecated. Please set these arguments in the constructor instead.
  with gr.Row().style(equal_height=False):
O:\AI\SynologyDrive\stable-diffusion-webui\extensions\sd-webui-supermerger\scripts\mergers\pluslora.py:89: GradioDeprecationWarning: The `style` method is deprecated. Please set these arguments in the constructor instead.
  with gr.Row().style(equal_height=False):
```

**Comment by wkpark** [comment]
style()` is deprecated in the latest version of gradio, which is why it shows deprecation warnings.

**Comment by Neytiri7** [comment]
I think it would be good if it was revised as soon as possible.

**Comment by wkpark** [comment]
deprecations are warnings, are you sure the latest supermerger is not working?
in my case, the latest supermerger works nicely without issue.

**Comment by Neytiri7** [comment]
The same issue was confirmed in dev branch and re branch where 1.6.0 was raised.

And now, 1.6.0 is up on the master, and it doesn't work.

**Comment by Neytiri7** [comment]
model A       : Dream-C3-v1.1
  model B       : hansChaosModelV4_v40
  model C       :
  alpha,beta    : (0.3, 0.25)
  weights_alpha :
  weights_beta  :
  mode          : Weight sum:A*(1-alpha)+B*alpha
  MBW           : False
  CalcMode      : normal
  Elemental     :
  Weights Seed  : 1220710345
  Adjust        :
Loading weights [hansChaosModelV4_v40] from file
Loading weights [1a39c2156e] from O:\AI\SynologyDrive\stable-diffusion-webui\models\Stable-diffusion\Dream-C3-v1.1.safetensors
Creating model from config: O:\AI\SynologyDrive\stable-diffusion-webui\configs\v1-inference.yaml
Loading VAE weights specified in settings: O:\AI\SynologyDrive\stable-diffusion-webui\models\VAE\vae-ft-mse-840000-ema-pruned.ckpt
Applying attention optimization: xformers... done.
Traceback (most recent call last):
  File "O:\AI\SynologyDrive\stable-diffusion-webui\venv\lib\site-packages\gradio\routes.py", line 488, in run_predict
    output = await app.get_blocks().process_api(
  File "O:\AI\SynologyDrive\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1431, in process_api
    result = await self.call_function(
  File "O:\AI\SynologyDrive\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1103, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "O:\AI\SynologyDrive\stable-diffusion-webui\venv\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "O:\AI\SynologyDrive\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "O:\AI\SynologyDrive\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "O:\AI\SynologyDrive\stable-diffusion-webui\venv\lib\site-packages\gradio\utils.py", line 707, in wrapper
    response = f(*args, **kwargs)
  File "O:\AI\SynologyDrive\stable-diffusion-webui\extensions\sd-webui-supermerger\scripts\mergers\mergers.py", line 85, in smergegen
    result,currentmodel,modelid,theta_0,metadata = smerge(
  File "O:\AI\SynologyDrive\stable-diffusion-webui\extensions\sd-webui-supermerger\scripts\mergers\mergers.py", line 266, in smerge
    theta_0=load_model_weights_m(model_a,True,False,save).copy()
  File "O:\AI\SynologyDrive\stable-diffusion-webui\extensions\sd-webui-supermerger\scripts\mergers\mergers.py", line 722, in load_model_weights_m
    load_model(checkpoint_info)
  File "O:\AI\SynologyDrive\stable-diffusion-webui\modules\sd_models.py", line 649, in load_model
    sd_model.cond_stage_model_empty_prompt = get_empty_cond(sd_model)
  File "O:\AI\SynologyDrive\stable-diffusion-webui\modules\sd_models.py", line 537, in get_empty_cond
    return sd_model.cond_stage_model([""])
  File "O:\AI\SynologyDrive\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "O:\AI\SynologyDrive\stable-diffusion-webui\modules\sd_hijack_clip.py", line 234, in forward
    z = self.process_tokens(tokens, multipliers)
  File "O:\AI\SynologyDrive\stable-diffusion-webui\modules\sd_hijack_clip.py", line 273, in process_tokens
    z = self.encode_with_transformers(tokens)
  File "O:\AI\SynologyDrive\stable-diffusion-webui\modules\sd_hijack_clip.py", line 326, in encode_with_transformers
    outputs = self.wrapped.transformer(input_ids=tokens, output_hidden_states=-opts.CLIP_stop_at_last_layers)
  File "O:\AI\SynologyDrive\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
    result = hook(self, args)
  File "O:\AI\SynologyDrive\stable-diffusion-webui\modules\lowvram.py", line 52, in send_me_to_gpu
    module_in_gpu.to(cpu)
  File "O:\AI\SynologyDrive\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1145, in to
    return self._apply(convert)
  File "O:\AI\SynologyDrive\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 797, in _apply
    module._apply(fn)
  File "O:\AI\SynologyDrive\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 797, in _apply
    module._apply(fn)
  File "O:\AI\SynologyDrive\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 797, in _apply
    module._apply(fn)
  [Previous line repeated 2 more times]
  File "O:\AI\SynologyDrive\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 820, in _apply
    param_applied = fn(param)
  File "O:\AI\SynologyDrive\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1143, in convert
    return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)
NotImplementedError: Cannot copy out of meta tensor; no data!

**Comment by rabidcopy** [comment]
Can confirm the above error when trying to merge.

**Comment by Neytiri7** [comment]
I changed it as above, but it's the same. Also, the UI is broken and displayed.

**Comment by rabidcopy** [comment]
I think another issue is lowvram/medvram merging is broken as of 1.6.0 with this extension. (I can't test without these launch options because limited VRAM.)

**Comment by Neytiri7** [comment]
> Change in the line 56 of `sd-webui-supermerger\scripts\supermerger.py` to `with gr.Row(equal_height=False):`
> 
> and change line 70 , 77 , 81 , 84 , 89 of `sd-webui-supermerger\scripts\mergers\pluslora.py` to `with gr.Row(equal_height=False):`
> 
> DONE!

I don't think there's an error at the start...
The feature does not work.

Also, the UI is broken and displayed.

**Comment by hako-mikan** [comment]
I will address the VRAM-related error later, but the Gradio-related error should be fixed now. In fact, that was just a warning, so it shouldn't affect the functionality.

**Comment by Neytiri7** [comment]
dev branch error.


 model A       : Dream-C3-v1.1
  model B       : a
  model C       :
  alpha,beta    : (0.3, 0.25)
  weights_alpha :
  weights_beta  :
  mode          : Weight sum
  MBW           : False
  CalcMode      : normal
  Elemental     :
  Weights Seed  : 2670411683
  Adjust        :
Loading weights [a] from file
Loading weights [1a39c2156e] from O:\AI\SynologyDrive\stable-diffusion-webui\models\Stable-diffusion\Dream-C3-v1.1.safetensors
Creating model from config: O:\AI\SynologyDrive\stable-diffusion-webui\configs\v1-inference.yaml
Loading VAE weights specified in settings: O:\AI\SynologyDrive\stable-diffusion-webui\models\VAE\vae-ft-mse-840000-ema-pruned.ckpt
Applying attention optimization: xformers... done.
Traceback (most recent call last):
  File "O:\AI\SynologyDrive\stable-diffusion-webui\venv\lib\site-packages\gradio\routes.py", line 488, in run_predict
    output = await app.get_blocks().process_api(
  File "O:\AI\SynologyDrive\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1431, in process_api
    result = await self.call_function(
  File "O:\AI\SynologyDrive\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1103, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "O:\AI\SynologyDrive\stable-diffusion-webui\venv\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "O:\AI\SynologyDrive\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "O:\AI\SynologyDrive\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "O:\AI\SynologyDrive\stable-diffusion-webui\venv\lib\site-packages\gradio\utils.py", line 707, in wrapper
    response = f(*args, **kwargs)
  File "O:\AI\SynologyDrive\stable-diffusion-webui\extensions\sd-webui-supermerger\scripts\mergers\mergers.py", line 90, in smergegen
    result,currentmodel,modelid,theta_0,metadata = smerge(
  File "O:\AI\SynologyDrive\stable-diffusion-webui\extensions\sd-webui-supermerger\scripts\mergers\mergers.py", line 298, in smerge
    theta_0=load_model_weights_m(model_a,True,False,save).copy()
  File "O:\AI\SynologyDrive\stable-diffusion-webui\extensions\sd-webui-supermerger\scripts\mergers\mergers.py", line 754, in load_model_weights_m
    load_model(checkpoint_info)
  File "O:\AI\SynologyDrive\stable-diffusion-webui\modules\sd_models.py", line 649, in load_model
    sd_model.cond_stage_model_empty_prompt = get_empty_cond(sd_model)
  File "O:\AI\SynologyDrive\stable-diffusion-webui\modules\sd_models.py", line 537, in get_empty_cond
    return sd_model.cond_stage_model([""])
  File "O:\AI\SynologyDrive\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "O:\AI\SynologyDrive\stable-diffusion-webui\modules\sd_hijack_clip.py", line 234, in forward
    z = self.process_tokens(tokens, multipliers)
  File "O:\AI\SynologyDrive\stable-diffusion-webui\modules\sd_hijack_clip.py", line 273, in process_tokens
    z = self.encode_with_transformers(tokens)
  File "O:\AI\SynologyDrive\stable-diffusion-webui\modules\sd_hijack_clip.py", line 326, in encode_with_transformers
    outputs = self.wrapped.transformer(input_ids=tokens, output_hidden_states=-opts.CLIP_stop_at_last_layers)
  File "O:\AI\SynologyDrive\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
    result = hook(self, args)
  File "O:\AI\SynologyDrive\stable-diffusion-webui\modules\lowvram.py", line 52, in send_me_to_gpu
    module_in_gpu.to(cpu)
  File "O:\AI\SynologyDrive\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1145, in to
    return self._apply(convert)
  File "O:\AI\SynologyDrive\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 797, in _apply
    module._apply(fn)
  File "O:\AI\SynologyDrive\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 797, in _apply
    module._apply(fn)
  File "O:\AI\SynologyDrive\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 797, in _apply
    module._apply(fn)
  [Previous line repeated 2 more times]
  File "O:\AI\SynologyDrive\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 820, in _apply
    param_applied = fn(param)
  File "O:\AI\SynologyDrive\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1143, in convert
    return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)
NotImplementedError: Cannot copy out of meta tensor; no data!

**Comment by Neytiri7** [comment]
I checked that it has been modified.
Thank you.
