### ISSUE TITLE
TypeError: unsupported operand type(s) for +=: 'Tensor' and 'tuple'

### ISSUE THREAD

**Issue by oliverban** [hako-mikan/sd-webui-supermerger#199]
Error in title occurs when trying to merge a XL lora into an XL checkpoint.

Plus LoRA start
Loading RealitiesEdge XL Anime.safetensors [105b4e2a18]
Loading weights [105b4e2a18] from C:\Users\Oliver\Documents\Github\stable-diffusion-webui\models\Stable-diffusion\RealitiesEdge XL Anime.safetensors
Creating model from config: C:\Users\Oliver\Documents\Github\stable-diffusion-webui\repositories\generative-models\configs\inference\sd_xl_base.yaml
Loading VAE weights specified in settings: C:\Users\Oliver\Documents\Github\stable-diffusion-webui\models\VAE\sd_xl_vae_0.9.safetensors
Applying attention optimization: sdp-no-mem... done.
Model loaded in 8.0s (unload existing model: 0.1s, load weights from disk: 0.9s, create model: 0.5s, apply weights to model: 5.4s, load VAE: 0.5s, move model to device: 0.1s, load textual inversion embeddings: 0.1s, calculate empty prompt: 0.1s).
sdxl_DetailedEyes_V3: Successfully set the ratio [0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5]
sdxl_DetailedEyes_V3:   0%|                                                                    | 0/560 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "C:\Users\Oliver\Documents\Github\stable-diffusion-webui\venv\lib\site-packages\gradio\routes.py", line 488, in run_predict
    output = await app.get_blocks().process_api(
  File "C:\Users\Oliver\Documents\Github\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1431, in process_api
    result = await self.call_function(
  File "C:\Users\Oliver\Documents\Github\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1103, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "C:\Users\Oliver\Documents\Github\stable-diffusion-webui\venv\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "C:\Users\Oliver\Documents\Github\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "C:\Users\Oliver\Documents\Github\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "C:\Users\Oliver\Documents\Github\stable-diffusion-webui\venv\lib\site-packages\gradio\utils.py", line 707, in wrapper
    response = f(*args, **kwargs)
  File "C:\Users\Oliver\Documents\Github\stable-diffusion-webui\extensions\sd-webui-supermerger\scripts\mergers\pluslora.py", line 569, in pluslora
    theta_0 = newpluslora(theta_0,filenames,lweis,names, isxl, keychanger)
  File "C:\Users\Oliver\Documents\Github\stable-diffusion-webui\extensions\sd-webui-supermerger\scripts\mergers\pluslora.py", line 663, in newpluslora
    theta_0[keychanger[msd_key]] = plusweights(theta_0[keychanger[msd_key]], name ,module, net)
  File "C:\Users\Oliver\Documents\Github\stable-diffusion-webui\extensions\sd-webui-supermerger\scripts\mergers\pluslora.py", line 683, in plusweights
    weight += updown
TypeError: unsupported operand type(s) for +=: 'Tensor' and 'tuple'

**Comment by retronomi** [comment]
Having this as well with merging 1.5 LoRAs/Lycos with models.

**Comment by hako-mikan** [comment]
Fixed.
