### ISSUE TITLE
KeyError: 'transformer_text_model_encoder_layers_0_mlp_fc1'

### ISSUE THREAD

**Issue by ddPn08** [hako-mikan/sd-webui-supermerger#2]
I got an error when merging LoRA into checkpoint.
Here is the model. https://huggingface.co/JosephusCheung/RuminationDiffusion

LoRA is also learned using Mr. kohya's script in the above model.

The error is below.
```
plus LoRA start
Loading ssd\Rumination.ckpt [53afdeb699]
Global Step: 0
loading: rumination-base-000006
merging... [1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0]
Traceback (most recent call last):
  File "C:\Users\ddPn08\AppData\Roaming\flat\miniconda\envs\stable-diffusion-webui\lib\site-packages\gradio\routes.py", line 337, in run_predict
    output = await app.get_blocks().process_api(
  File "C:\Users\ddPn08\AppData\Roaming\flat\miniconda\envs\stable-diffusion-webui\lib\site-packages\gradio\blocks.py", line 1015, in process_api
    result = await self.call_function(
  File "C:\Users\ddPn08\AppData\Roaming\flat\miniconda\envs\stable-diffusion-webui\lib\site-packages\gradio\blocks.py", line 833, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "C:\Users\ddPn08\AppData\Roaming\flat\miniconda\envs\stable-diffusion-webui\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "C:\Users\ddPn08\AppData\Roaming\flat\miniconda\envs\stable-diffusion-webui\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "C:\Users\ddPn08\AppData\Roaming\flat\miniconda\envs\stable-diffusion-webui\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "C:\Users\ddPn08\AppData\Roaming\flat\features\stable-diffusion-webui\repository\extensions\sd-webui-supermerger\scripts\mergers\pluslora.py", line 352, in pluslora
    weight = theta_0[keychanger[msd_key]]
KeyError: 'transformer_text_model_encoder_layers_0_mlp_fc1'
```

**Comment by hako-mikan** [comment]
This script does not support v2.x series merges at this time. I am trying now, so it may take some time. Until then, please use kohya's script.
