### ISSUE TITLE
Once you use the XYZ chart, this error will appear, and I want to ask how to solve it, and I have tried many methods

### ISSUE THREAD

**Issue by aoligeihaihai** [hako-mikan/sd-webui-supermerger#201]
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/gradio/routes.py", line 422, in run_predict
    output = await app.get_blocks().process_api(
  File "/usr/local/lib/python3.10/dist-packages/gradio/blocks.py", line 1323, in process_api
    result = await self.call_function(
  File "/usr/local/lib/python3.10/dist-packages/gradio/blocks.py", line 1051, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/usr/local/lib/python3.10/dist-packages/anyio/to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/usr/local/lib/python3.10/dist-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "/usr/local/lib/python3.10/dist-packages/anyio/_backends/_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "/mnt/data/stable-diffusion-webui/extensions/sd-webui-supermerger/scripts/mergers/xyplot.py", line 68, in numanager
    result,currentmodel,xyimage,a,b,c= sgenxyplot(*allsets)
  File "/mnt/data/stable-diffusion-webui/extensions/sd-webui-supermerger/scripts/mergers/xyplot.py", line 203, in sgenxyplot
    if gensets[11] == -1: gensets[11] = int(random.randrange(4294967294))

**Comment by miasik** [comment]
It looks like the error I had recently. Check if you updated SM to recent version.

**Comment by aoligeihaihai** [comment]
> 看起来像我最近遇到的错误。检查您是否将SM更新到最新版本。

I've tried updating Supermerger to the latest version and still get this code, which I think might be a programming problem

**Comment by hako-mikan** [comment]
fixing now.

**Comment by aoligeihaihai** [comment]
> 现在修复。

Thank you very much, hard work

**Comment by aoligeihaihai** [comment]
> fixing now.

Thank you very much

**Comment by hako-mikan** [comment]
Fixed.
