### ISSUE TITLE
Error when saving model

### ISSUE THREAD

**Issue by Nerogante** [hako-mikan/sd-webui-supermerger#208]
Stage 1/2: 100%|████████████████████████████████████████████████████████████████████████████████████████| 2918/2918 [00:00<00:00, 98043.60it/s]
Stage 2/2: 100%|██████████████████████████████████████████████████████████████████████████████████████| 2918/2918 [00:00<00:00, 2827206.99it/s]
Creating model from config: C:\stable-diffusion-webui\configs\v1-inference.yaml
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
Traceback (most recent call last):
  File "C:\stable-diffusion-webui\venv\lib\site-packages\gradio\routes.py", line 422, in run_predict
    output = await app.get_blocks().process_api(
  File "C:\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1323, in process_api
    result = await self.call_function(
  File "C:\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1051, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "C:\stable-diffusion-webui\venv\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "C:\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "C:\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "C:\stable-diffusion-webui\extensions\sd-webui-supermerger\scripts\mergers\mergers.py", line 121, in smergegen
    load_model(checkpoint_info, already_loaded_state_dict=theta_0)
  File "C:\stable-diffusion-webui\modules\sd_models.py", line 510, in load_model
    load_model_weights(sd_model, checkpoint_info, state_dict, timer)
  File "C:\stable-diffusion-webui\modules\sd_models.py", line 284, in load_model_weights
    sd_model_hash = checkpoint_info.calculate_shorthash()
  File "C:\stable-diffusion-webui\modules\sd_models.py", line 82, in calculate_shorthash
    checkpoints_list.pop(self.title)
KeyError: 'criminal_art_asian_porn_v1-FULL x (1-alpha) + criminal_art_hentai_hardcore_v1-FULL x alpha (0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0).safetensors [64c4af3322]'

welp

Last commit from Commits on Aug 30, 2023
[more compact size merge/gen buttons](https://github.com/hako-mikan/sd-webui-supermerger/commit/3a28aca7fc8f18cac1bbd868c1a1ad317104cbd3) works fine

If this should be working maybe I need to update Automatic

**Comment by Nerogante** [comment]
It's working now
