### ISSUE TITLE
Looks like there is error with Mering LORA with weight 

### ISSUE THREAD

**Issue by lunect** [hako-mikan/sd-webui-supermerger#21]
Hi, thank you for providing useful extension for WEBUI. 
I just started to use this extension, but I found few small error. 
The first error I found is it only accept float(1). If I input weight for block such as 0.25, it directly give errors. Also, I'm not sure the trigger for the glitch yet, but some case if I leave the filename as blank, it also gives the error. 

I also tried to use the block merger to adjsut the weight of the block of the LORA

1.5,1.6,1.1,1.4,0.6,0.3,0.2,0.1,0.3,0.25,0.1,1.2,0.7,1.4,0.8,2.1,2
"Base ,IN01 ...... OUT11"
I'm not sure if I'm doing it in right ways,  I duplicated the same LORA and set one to 0.1 and the other to (value-0.1).
But the result was quite different from I checked in LORA block weight extension. 
To make sure, I merged two same LORA with 0.5 weight for each,  and merged, but the merged LORA behave different from original one. I'm not sure if is the characteristic of some of the function in LORA but I wonder if you can check it. 
Thank you.

**Comment by hako-mikan** [comment]
For first issue, where did you input the value. "weights for alpha"?

For second issue, did you try "same to strength" mode? As described in "Difference between Normal Merge and SAME TO STRENGTH" merged LoRA is usually different.

**Comment by lunect** [comment]
1. I set the alpha and beta to 1. Then input following "LoRAname1:ratio1:Blocks1,LoRAname2:ratio2:Blocks2,...(":blocks" is option, not necessary)" window.  
 Lora2:0.1,Lora1:1.5:BASE,Lora1:1.6:IN01,Lora1:1.1:IN02,Lora1:1.4:IN04,Lora1:0.6:IN05,Lora1:0.3:IN07,Lora1:0.2:IN08,Lora1:0.1:M00,Lora1:0.3:OUT03,Lora1:0.25:OUT04,Lora1:0.1:OUT05,Lora1:12:OUT06,Lora1:0.7:OUT07,Lora1:1.4:OUT08,Lora1:0.8:OUT09,Lora1:2.1:OUT10,Lora1:2:OUT11,  

Then it gives error as following. 

Traceback (most recent call last):
  File "C:\WebUI\Stable Diffusion\venv\lib\site-packages\gradio\routes.py", line 337, in run_predict
    output = await app.get_blocks().process_api(
  File "C:\WebUI\Stable Diffusion\venv\lib\site-packages\gradio\blocks.py", line 1015, in process_api
    result = await self.call_function(
  File "C:\WebUI\Stable Diffusion\venv\lib\site-packages\gradio\blocks.py", line 833, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "C:\WebUI\Stable Diffusion\venv\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "C:\WebUI\Stable Diffusion\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "C:\WebUI\Stable Diffusion\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "C:\WebUI\Stable Diffusion\extensions\sd-webui-supermerger\scripts\mergers\pluslora.py", line 203, in lmerge
    else:ratio = [float(n[1])]*17
IndexError: list index out of range

I originally thought it is the error with the floating, but if I input as the following, it was ok. 

Lora2:0.1,Lora1:1.5:BASE,Lora1:1.6:IN01,Lora1:1.1:IN02,Lora1:1.4:IN04,Lora1:0.65:IN05,Lora1:0.3:IN07

but if I input more number of inputs, then it gives error again. 

Lora2:0.1,Lora1:1.5:BASE,Lora1:1.6:IN01,Lora1:1.1:IN02,Lora1:1.4:IN04,Lora1:0.65:IN05,Lora1:0.3:IN07, Lora1:0.2:IN08

Looks like if number of inputs are more certain number, then it gives error.  Is there better way to input weights without triggering this error?

2. I used same to strength mode, but not notice the much of difference with normal yet. I will try again after 1

**Comment by Kepler-16b** [comment]
remove the final ","

**Comment by ride5k** [comment]
believe i'm seeing a similar issue.  when inputting (for example):

LORAtest-5-5-5-7:1.0:0,0.75,0.75,0.75,0.75,0.75,0.75,0.75,0.75,0.75,0.75,0.75,0.75,0.75,0.75,0.75,0.75,0.75,0.75,0.75,0.75,0.75,0.75,0.75,0.75,0.75

which is a "flat75" blockweight, i get the same IndexError: list index out of range console message.
