### ISSUE TITLE
Bug  supermerger.py

### ISSUE THREAD

**Issue by XT-404** [hako-mikan/sd-webui-supermerger#210]
*** Error loading script: GenParamGetter.py
    Traceback (most recent call last):
      File "W:\A1111\stable-diffusion-webui\modules\scripts.py", line 274, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "W:\A1111\stable-diffusion-webui\modules\script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "W:\A1111\stable-diffusion-webui\extensions\sd-webui-supermerger\scripts\GenParamGetter.py", line 3, in <module>
        from scripts.mergers.mergers import smergegen, simggen
      File "W:\A1111\stable-diffusion-webui\extensions\sd-webui-supermerger\scripts\mergers\mergers.py", line 21, in <module>
        from modules import cache, shared, processing, sd_models, sd_vae, images, sd_samplers,scripts,devices
    ImportError: cannot import name 'cache' from 'modules' (unknown location)

---
*** Error loading script: supermerger.py
    Traceback (most recent call last):
      File "W:\A1111\stable-diffusion-webui\modules\scripts.py", line 274, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "W:\A1111\stable-diffusion-webui\modules\script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "W:\A1111\stable-diffusion-webui\extensions\sd-webui-supermerger\scripts\supermerger.py", line 17, in <module>
        import scripts.mergers.mergers
      File "W:\A1111\stable-diffusion-webui\extensions\sd-webui-supermerger\scripts\mergers\mergers.py", line 21, in <module>
        from modules import cache, shared, processing, sd_models, sd_vae, images, sd_samplers,scripts,devices
    ImportError: cannot import name 'cache' from 'modules' (unknown location)

**Comment by hako-mikan** [comment]
May be fixed.

**Comment by XT-404** [comment]
> Peut être corrigé.

Thx :)
