### ISSUE TITLE
Error with Automatic1111 1.5.2

### ISSUE THREAD

**Issue by Nerogante** [hako-mikan/sd-webui-supermerger#212]
I made a clean installation of Automatic1111 1.5.2 because 1.6 is broken, and latest supermerger commit throws error when saving model.

Stage 1/2: 100%|███████████████████████████████████████████████████████████████| 1133/1133 [00:00<00:00, 162239.13it/s]
Stage 2/2: 100%|██████████████████████████████████████████████████████████████| 2918/2918 [00:00<00:00, 2826554.06it/s]
Creating model from config: C:\stable-diffusion-webui-1.5.2\configs\v1-inference.yaml
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
Traceback (most recent call last):
  File "C:\stable-diffusion-webui-1.5.2\venv\lib\site-packages\gradio\routes.py", line 422, in run_predict
    output = await app.get_blocks().process_api(
  File "C:\stable-diffusion-webui-1.5.2\venv\lib\site-packages\gradio\blocks.py", line 1323, in process_api
    result = await self.call_function(
  File "C:\stable-diffusion-webui-1.5.2\venv\lib\site-packages\gradio\blocks.py", line 1051, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "C:\stable-diffusion-webui-1.5.2\venv\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "C:\stable-diffusion-webui-1.5.2\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "C:\stable-diffusion-webui-1.5.2\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "C:\stable-diffusion-webui-1.5.2\extensions\sd-webui-supermerger\scripts\mergers\mergers.py", line 138, in smergegen
    load_model(checkpoint_info, already_loaded_state_dict=theta_0)
  File "C:\stable-diffusion-webui-1.5.2\modules\sd_models.py", line 510, in load_model
    load_model_weights(sd_model, checkpoint_info, state_dict, timer)
  File "C:\stable-diffusion-webui-1.5.2\modules\sd_models.py", line 284, in load_model_weights
    sd_model_hash = checkpoint_info.calculate_shorthash()
  File "C:\stable-diffusion-webui-1.5.2\modules\sd_models.py", line 82, in calculate_shorthash
    checkpoints_list.pop(self.title)
KeyError: 'criminal_art_hentai_hardcore_v1-pruned-FP32 x (1-alpha) + r_human x alpha (0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0).safetensors [64c4af3322]'

**Comment by hako-mikan** [comment]
Fixed.

**Comment by Nerogante** [comment]
Thanks 👍
