### ISSUE TITLE
an error for cosA/B modes: IndexError: cannot do a non-empty take from an empty axes.

### ISSUE THREAD

**Issue by miasik** [hako-mikan/sd-webui-supermerger#213]
Some models started producing an error for calc modes cosA/B,
In the case below it is absolutereality_v181 and there are a plenty of them I found during testing. They all work well in normal mode.

>   model A       : Photo_UnSt6-(simple-91153)-91164.fp16
  model B       : Photo_absolutereality_v181
  model C       : v1-5-pruned-emaonly
  alpha,beta    : (0.75, 0.5)
  weights_alpha : [0.75, 0.75, 0.75, 0.75, 0.75, 0.75, 0.75, 0.75, 0.75, 0.75, 0.75, 0.75, 0.75, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5]
  weights_beta  : 0.2,0.2,0.2,0.2,0.2,0.2,0.2,0.2,0.2,0.2,0.2,0.2,0.2,0.2,0.2,0.2,0.2,0.2,0.2,0.2,0.2,0.2,0.2,0.2,0.2,0.2
  mode          : Weight sum
  MBW           : True
  CalcMode      : cosineA
  Elemental     :
  Weights Seed  : 4231443087.0
  Adjust        :
Loading weights [Photo_absolutereality_v181] from file
Loading weights [Photo_UnSt6-(simple-91153)-91164.fp16] from file
Stage 0/2: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 415/415 [00:00<00:00, 416220.99it/s]
Traceback (most recent call last):
  File "e:\SD\automatic1111\venv\lib\site-packages\gradio\routes.py", line 488, in run_predict
    output = await app.get_blocks().process_api(
  File "e:\SD\automatic1111\venv\lib\site-packages\gradio\blocks.py", line 1431, in process_api
    result = await self.call_function(
  File "e:\SD\automatic1111\venv\lib\site-packages\gradio\blocks.py", line 1103, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "e:\SD\automatic1111\venv\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "e:\SD\automatic1111\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "e:\SD\automatic1111\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "e:\SD\automatic1111\venv\lib\site-packages\gradio\utils.py", line 707, in wrapper
    response = f(*args, **kwargs)
  File "E:\SD\automatic1111\extensions\sd-webui-supermerger\scripts\mergers\mergers.py", line 120, in smergegen
    result,currentmodel,modelid,theta_0,metadata = smerge(
  File "E:\SD\automatic1111\extensions\sd-webui-supermerger\scripts\mergers\mergers.py", line 372, in smerge
    sims = np.delete(sims, np.where(sims<np.percentile(sims, 1 ,method = 'midpoint')))
  File "<__array_function__ internals>", line 180, in percentile
  File "e:\SD\automatic1111\venv\lib\site-packages\numpy\lib\function_base.py", line 4166, in percentile
    return _quantile_unchecked(
  File "e:\SD\automatic1111\venv\lib\site-packages\numpy\lib\function_base.py", line 4424, in _quantile_unchecked
    r, k = _ureduce(a,
  File "e:\SD\automatic1111\venv\lib\site-packages\numpy\lib\function_base.py", line 3725, in _ureduce
    r = func(a, **kwargs)
  File "e:\SD\automatic1111\venv\lib\site-packages\numpy\lib\function_base.py", line 4593, in _quantile_ureduce_func
    result = _quantile(arr,
  File "e:\SD\automatic1111\venv\lib\site-packages\numpy\lib\function_base.py", line 4699, in _quantile
    take(arr, indices=-1, axis=DATA_AXIS)
  File "<__array_function__ internals>", line 180, in take
  File "e:\SD\automatic1111\venv\lib\site-packages\numpy\core\fromnumeric.py", line 190, in take
    return _wrapfunc(a, 'take', indices, axis=axis, out=out, mode=mode)
  File "e:\SD\automatic1111\venv\lib\site-packages\numpy\core\fromnumeric.py", line 57, in _wrapfunc
    return bound(*args, **kwds)
IndexError: cannot do a non-empty take from an empty axes.

**Comment by miasik** [comment]
My bad again :-(
Will add more later

**Comment by ajunkdha** [comment]
Yah me to, what Can the stable version be used??

**Comment by ajunkdha** [comment]
> My bad again :-( Will add more later

What ver 10 or 15 is stable version?

**Comment by miasik** [comment]
> 
> What ver 10 or 15 is stable version?

I'm on SD 1.6 and it works well.

**Comment by miasik** [comment]
Could be the same as #214
