### ISSUE TITLE
Typo in model_util.py causes: "NameError: name 'enumerage' is not defined" when saving merge - GPT-4 suggested cause was typo / edited and works now - FYI for review

### ISSUE THREAD

**Issue by CCpt5** [hako-mikan/sd-webui-supermerger#234]
Hi! Love your extension.

Recently I've been merging SDXL models and using them in A1111 w/o issue. However, when I attempt to save them I'd either get a broken file (not recognized by kohya scripts/a1111/ and a model-toolkit extension for A1111 says it's mostly junk data). The error I started getting eventually was:

```
`Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Startup time: 16.1s (prepare environment: 6.0s, import torch: 1.6s, import gradio: 0.5s, setup paths: 0.6s, initialize shared: 0.2s, other imports: 0.6s, setup codeformer: 0.2s, list SD models: 0.2s, load scripts: 4.9s, create ui: 0.9s, gradio launch: 0.3s, app_started_callback: 0.1s).
Loading VAE weights specified in settings: D:\Stable-Diffusion-Webui-Dev\sdxl\stable-diffusion-webui\models\VAE\sdxl_vae.safetensors
Applying attention optimization: sdp... done.
Model loaded in 7.4s (load weights from disk: 0.9s, create model: 0.5s, apply weights to model: 3.0s, load VAE: 0.9s, calculate empty prompt: 2.0s).
Unloaded weights 0.0s.
  model A       : SDXL_2023-09-08 - Topnotch Artstyle #29 - Mostly MJ - 18img - TXT ON - B4-step00001600
  model B       : SDXL_2023-09-03 - Topnotch Artstyle #29 (Knowlin Box etc) - 20img - TXT ON - B4 - 1e5-step00002400
  model C       : SDXL_2023-08-31 - Topnotch Artstyle (Mj greed theme park 3 - TXT enc on) - 12img-step00002000
  alpha,beta    : (0.56, 0.282)
  weights_alpha :
  weights_beta  :
  mode          : Triple sum
  MBW           : False
  CalcMode      : normal
  Elemental     :
  Weights Seed  : 4057641481.0
  Adjust        :
Loading weights [SDXL_2023-09-03 - Topnotch Artstyle #29 (Knowlin Box etc) - 20img - TXT ON - B4 - 1e5-step00002400] from file
Loading weights [SDXL_2023-09-08 - Topnotch Artstyle #29 - Mostly MJ - 18img - TXT ON - B4-step00001600] from file
Loading weights [SDXL_2023-08-31 - Topnotch Artstyle (Mj greed theme park 3 - TXT enc on) - 12img-step00002000] from file
Stage 1/2: 100%|██████████████████████████████████████████████████████████████████| 2515/2515 [00:11<00:00, 222.64it/s]
Stage 2/2: 100%|███████████████████████████████████████████████████████████████████████████| 2515/2515 [00:00<?, ?it/s]
Saving...
Traceback (most recent call last):
  File "D:\Stable-Diffusion-Webui-Dev\sdxl\stable-diffusion-webui\venv\lib\site-packages\gradio\routes.py", line 488, in run_predict
    output = await app.get_blocks().process_api(
  File "D:\Stable-Diffusion-Webui-Dev\sdxl\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1431, in process_api
    result = await self.call_function(
  File "D:\Stable-Diffusion-Webui-Dev\sdxl\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1103, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "D:\Stable-Diffusion-Webui-Dev\sdxl\stable-diffusion-webui\venv\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "D:\Stable-Diffusion-Webui-Dev\sdxl\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "D:\Stable-Diffusion-Webui-Dev\sdxl\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "D:\Stable-Diffusion-Webui-Dev\sdxl\stable-diffusion-webui\venv\lib\site-packages\gradio\utils.py", line 707, in wrapper
    response = f(*args, **kwargs)
  File "D:\Stable-Diffusion-Webui-Dev\sdxl\stable-diffusion-webui\extensions\sd-webui-supermerger\scripts\mergers\mergers.py", line 137, in smergegen
    result = savemodel(theta_0,currentmodel,custom_name,save_sets,metadata) if save else "Merged model loaded:"+currentmodel
  File "D:\Stable-Diffusion-Webui-Dev\sdxl\stable-diffusion-webui\extensions\sd-webui-supermerger\scripts\mergers\model_util.py", line 757, in savemodel
    for i, key in enumerage(state_dict.keys()):
NameError: name 'enumerage' is not defined`

```

I copy pasted that into GPT-4 which gave the following reply:

```
`It appears that there's an error in the codebase you provided. The line that throws the error is:

python
Copy code
for i, key in enumerage(state_dict.keys()):
The error indicates that enumerage is not defined. It seems like a typo. The correct Python built-in function for enumerating over an iterable (like a list or dictionary) is enumerate. You should correct the line to:

python
Copy code
for i, key in enumerate(state_dict.keys()):
Replace enumerage with enumerate, and the error should be resolved.`
```

I edited the file model_util.py and changed "enumerage" to "enumerate" and saving sdxl models (perhaps other models) is working again. They're also being recognized properly and are usable.  
  
I don't know if this is affecting everyone or just me, but I wanted to report it in case that file needs to be updated.

Thanks!

**Comment by wkpark** [comment]
oops my bad.. `s/enumerage/enumerate/' introduced by 33b8ddd4 commit
