### ISSUE TITLE
ModuleNotFoundError: No module named 'diffusers'

### ISSUE THREAD

**Issue by myndxero** [hako-mikan/sd-webui-supermerger#24]
Despite following directions and running the command "pip install diffusers" via cmd in the webui folder, getting the following error trying to extract from a model trained on base SD1.5.

make LoRA start
loading SD model : Q:\stable diffusion\_models\__1.X\v1-5-pruned.ckpt
Traceback (most recent call last):
  File "C:\stable-diffusion-webui\venv\lib\site-packages\gradio\routes.py", line 337, in run_predict
    output = await app.get_blocks().process_api(
  File "C:\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1015, in process_api
    result = await self.call_function(
  File "C:\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 833, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "C:\stable-diffusion-webui\venv\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "C:\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "C:\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "C:\stable-diffusion-webui\extensions\sd-webui-supermerger\scripts\mergers\pluslora.py", line 173, in makelora
    svd(fullpathfromname(model_a),fullpathfromname(model_b),False,dim,"float",saveto,alpha,beta)
  File "C:\stable-diffusion-webui\extensions\sd-webui-supermerger\scripts\mergers\pluslora.py", line 390, in svd
    text_encoder_o, _, unet_o = load_models_from_stable_diffusion_checkpoint(v2, model_b)
  File "C:\stable-diffusion-webui\extensions\sd-webui-supermerger\scripts\mergers\model_util.py", line 718, in load_models_from_stable_diffusion_checkpoint
    import diffusers
ModuleNotFoundError: No module named 'diffusers'

**Comment by ClashSAN** [comment]
add `diffusers` to `requirements.txt` and double-click `webui-user.bat`, after it is installed you should remove diffusers from requirements.txt.

**Comment by myndxero** [comment]
I tried a plethora of things including putting it in my custom
webui-user.bat and update.bat. I also somehow broke Dreambooth too and
ended up deleting venv directory and dreambooth. One I did that everything
worked.

I kick myself if all I had to do was do it your way instead of my mess
haha. Thank you for your response!

**Comment by Dessper** [comment]
I haven't installed anything. The same error keeps occurring

**Comment by Dessper** [comment]
Why are diffusers not installed?

**Comment by Ev-Bro** [comment]
I am having this same issue. I have Diffuserrs installed. I also tried re-installing but am still getting the same error message. Let me know if there is any info I can gather! Thx.

**Comment by hako-mikan** [comment]
Perhaps they are installed in different locations. It is difficult for me to say what the cause is, as there are multiple possible causes, including virtual environments and operating systems and so on.
See below.
https://huggingface.co/docs/diffusers/installation
