### ISSUE TITLE
Couldn't perform 'git pull'

### ISSUE THREAD

**Issue by Neytiri7** [hako-mikan/sd-webui-supermerger#243]
error: Pulling is not possible because you have unmerged files.
hint: Fix them up in the work tree, and then use 'git add/rm <file>'
hint: as appropriate to mark resolution and make a commit.
fatal: Exiting because of an unresolved conflict.
Couldn't perform 'git pull' on repository in 'O:\AI\SynologyDrive\stable-diffusion-webui\extensions\sd-webui-supermerger':

**Comment by Neytiri7** [comment]
*** Error loading script: supermerger.py
    Traceback (most recent call last):
      File "O:\AI\SynologyDrive\stable-diffusion-webui\modules\scripts.py", line 382, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "O:\AI\SynologyDrive\stable-diffusion-webui\modules\script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 879, in exec_module
      File "<frozen importlib._bootstrap_external>", line 1017, in get_code
      File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "O:\AI\SynologyDrive\stable-diffusion-webui\extensions\sd-webui-supermerger\scripts\supermerger.py", line 340
        <<<<<<< Updated upstream
    IndentationError: expected an indented block after 'with' statement on line 339

---
Checkpoint H7_002.safetensors [daf7229999] not found; loading fallback BracingEvoMix_v1.safetensors [5bc5a45624]
Loading weights [5bc5a45624] from O:\AI\SynologyDrive\stable-diffusion-webui\models\Stable-diffusion\BracingEvoMix_v1.safetensors
Creating model from config: O:\AI\SynologyDrive\stable-diffusion-webui\configs\v1-inference.yaml
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
*** Error executing callback app_started_callback for O:\AI\SynologyDrive\stable-diffusion-webui\extensions\sd-webui-supermerger\scripts\GenParamGetter.py
    Traceback (most recent call last):
      File "O:\AI\SynologyDrive\stable-diffusion-webui\modules\script_callbacks.py", line 139, in app_started_callback
        c.callback(demo, app)
      File "O:\AI\SynologyDrive\stable-diffusion-webui\extensions\sd-webui-supermerger\scripts\GenParamGetter.py", line 87, in get_params_components
        components.merge.click(
    AttributeError: 'NoneType' object has no attribute 'click'

---
Startup time: 59.4s (prepare environment: 31.4s, import torch: 8.5s, import gradio: 2.4s, setup paths: 1.9s, initialize shared: 0.5s, other imports: 1.5s, setup codeformer: 0.5s, list SD models: 0.1s, load scripts: 9.8s, create ui: 1.5s, gradio launch: 0.7s, app_started_callback: 0.5s).
Loading VAE weights specified in settings: O:\AI\SynologyDrive\stable-diffusion-webui\models\VAE\vae-ft-mse-840000-ema-pruned.ckpt
Traceback (most recent call last):
  File "O:\AI\SynologyDrive\stable-diffusion-webui\venv\lib\site-packages\gradio\routes.py", line 488, in run_predict
    output = await app.get_blocks().process_api(
  File "O:\AI\SynologyDrive\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1431, in process_api
    result = await self.call_function(
  File "O:\AI\SynologyDrive\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1103, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "O:\AI\SynologyDrive\stable-diffusion-webui\venv\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "O:\AI\SynologyDrive\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "O:\AI\SynologyDrive\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "O:\AI\SynologyDrive\stable-diffusion-webui\venv\lib\site-packages\gradio\utils.py", line 707, in wrapper
    response = f(*args, **kwargs)
  File "O:\AI\SynologyDrive\stable-diffusion-webui\modules\ui_extensions.py", line 157, in extension_table
    ext.read_info_from_repo()
  File "O:\AI\SynologyDrive\stable-diffusion-webui\modules\extensions.py", line 61, in read_info_from_repo
    self.from_dict(d)
  File "O:\AI\SynologyDrive\stable-diffusion-webui\modules\extensions.py", line 45, in from_dict
    setattr(self, field, d[field])
TypeError: 'NoneType' object is not subscriptable
Applying attention optimization: xformers... done.
Traceback (most recent call last):
  File "O:\AI\SynologyDrive\stable-diffusion-webui\venv\lib\site-packages\gradio\routes.py", line 488, in run_predict
    output = await app.get_blocks().process_api(
  File "O:\AI\SynologyDrive\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1431, in process_api
    result = await self.call_function(
  File "O:\AI\SynologyDrive\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1103, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "O:\AI\SynologyDrive\stable-diffusion-webui\venv\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "O:\AI\SynologyDrive\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "O:\AI\SynologyDrive\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "O:\AI\SynologyDrive\stable-diffusion-webui\venv\lib\site-packages\gradio\utils.py", line 707, in wrapper
    response = f(*args, **kwargs)
  File "O:\AI\SynologyDrive\stable-diffusion-webui\modules\ui_extensions.py", line 195, in update_config_states_table
    config_state = config_states.get_config()
  File "O:\AI\SynologyDrive\stable-diffusion-webui\modules\config_states.py", line 107, in get_config
    ext_config = get_extension_config()
  File "O:\AI\SynologyDrive\stable-diffusion-webui\modules\config_states.py", line 85, in get_extension_config
    ext.read_info_from_repo()
  File "O:\AI\SynologyDrive\stable-diffusion-webui\modules\extensions.py", line 61, in read_info_from_repo
    self.from_dict(d)
  File "O:\AI\SynologyDrive\stable-diffusion-webui\modules\extensions.py", line 45, in from_dict
    setattr(self, field, d[field])
TypeError: 'NoneType' object is not subscriptable

**Comment by Neytiri7** [comment]
I reinstalled it just in case, and it ran normally without any errors.
I think it's a problem when updating.

**Comment by hako-mikan** [comment]
It's an error I haven't seen before, but doing a clean install as you did should resolve it.
