### ISSUE TITLE
Bug multiple Weight sum | Add difference | Triple sum | sum Twice

### ISSUE THREAD

**Issue by XT-404** [hako-mikan/sd-webui-supermerger#244]
Hello, I'm writing to report a bug.
If I happen to touch the following elements:

Weight sum | Add difference | Triple sum | Sum Twice

I encounter errors in the console just by selecting the specific modules.

Since the update, I also find myself unable to use this feature: Beta. I have a crossed-out circular cursor, preventing me from interacting (see screenshot).

I've reinstalled "Super merge" several times, but to no avail. I constantly face the issue of console errors and this circle that prevents me from using the Beta function.

<img width="1052" alt="image" src="https://github.com/hako-mikan/sd-webui-supermerger/assets/128090530/5c22ab48-e2c6-4b42-a1bf-9259decdeea8">
--------------------------------------------------------------------------------------------------------------------------------------------
Traceback (most recent call last):
  File "W:\A1111\stable-diffusion-webui\venv\lib\site-packages\gradio\routes.py", line 422, in run_predict
    output = await app.get_blocks().process_api(
  File "W:\A1111\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1326, in process_api
    data = self.postprocess_data(fn_index, result["prediction"], state)
  File "W:\A1111\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1251, in postprocess_data
    prediction_value = postprocess_update_dict(
  File "W:\A1111\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 423, in postprocess_update_dict
    update_dict = block.get_specific_update(update_dict)
  File "W:\A1111\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 308, in get_specific_update
    specific_update = cls.update(**generic_update)
TypeError: Radio.update() got an unexpected keyword argument 'info'
Traceback (most recent call last):
  File "W:\A1111\stable-diffusion-webui\venv\lib\site-packages\gradio\routes.py", line 422, in run_predict
    output = await app.get_blocks().process_api(
  File "W:\A1111\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1326, in process_api
    data = self.postprocess_data(fn_index, result["prediction"], state)
  File "W:\A1111\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1251, in postprocess_data
    prediction_value = postprocess_update_dict(
  File "W:\A1111\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 423, in postprocess_update_dict
    update_dict = block.get_specific_update(update_dict)
  File "W:\A1111\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 308, in get_specific_update
    specific_update = cls.update(**generic_update)
TypeError: Radio.update() got an unexpected keyword argument 'info'
Traceback (most recent call last):
  File "W:\A1111\stable-diffusion-webui\venv\lib\site-packages\gradio\routes.py", line 422, in run_predict
    output = await app.get_blocks().process_api(
  File "W:\A1111\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1326, in process_api
    data = self.postprocess_data(fn_index, result["prediction"], state)
  File "W:\A1111\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1251, in postprocess_data
    prediction_value = postprocess_update_dict(
  File "W:\A1111\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 423, in postprocess_update_dict
    update_dict = block.get_specific_update(update_dict)
  File "W:\A1111\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 308, in get_specific_update
    specific_update = cls.update(**generic_update)
TypeError: Radio.update() got an unexpected keyword argument 'info'
Traceback (most recent call last):
  File "W:\A1111\stable-diffusion-webui\venv\lib\site-packages\gradio\routes.py", line 422, in run_predict
    output = await app.get_blocks().process_api(
  File "W:\A1111\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1326, in process_api
    data = self.postprocess_data(fn_index, result["prediction"], state)
  File "W:\A1111\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1251, in postprocess_data
    prediction_value = postprocess_update_dict(
  File "W:\A1111\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 423, in postprocess_update_dict
    update_dict = block.get_specific_update(update_dict)
  File "W:\A1111\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 308, in get_specific_update
    specific_update = cls.update(**generic_update)
TypeError: Radio.update() got an unexpected keyword argument 'info'
Traceback (most recent call last):
  File "W:\A1111\stable-diffusion-webui\venv\lib\site-packages\gradio\routes.py", line 422, in run_predict
    output = await app.get_blocks().process_api(
  File "W:\A1111\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1326, in process_api
    data = self.postprocess_data(fn_index, result["prediction"], state)
  File "W:\A1111\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1251, in postprocess_data
    prediction_value = postprocess_update_dict(
  File "W:\A1111\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 423, in postprocess_update_dict
    update_dict = block.get_specific_update(update_dict)
  File "W:\A1111\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 308, in get_specific_update
    specific_update = cls.update(**generic_update)
TypeError: Radio.update() got an unexpected keyword argument 'info'
Traceback (most recent call last):
  File "W:\A1111\stable-diffusion-webui\venv\lib\site-packages\gradio\routes.py", line 422, in run_predict
    output = await app.get_blocks().process_api(
  File "W:\A1111\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1326, in process_api
    data = self.postprocess_data(fn_index, result["prediction"], state)
  File "W:\A1111\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1251, in postprocess_data
    prediction_value = postprocess_update_dict(
  File "W:\A1111\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 423, in postprocess_update_dict
    update_dict = block.get_specific_update(update_dict)
  File "W:\A1111\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 308, in get_specific_update
    specific_update = cls.update(**generic_update)
TypeError: Radio.update() got an unexpected keyword argument 'info'
Traceback (most recent call last):
  File "W:\A1111\stable-diffusion-webui\venv\lib\site-packages\gradio\routes.py", line 422, in run_predict
    output = await app.get_blocks().process_api(
  File "W:\A1111\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1326, in process_api
    data = self.postprocess_data(fn_index, result["prediction"], state)
  File "W:\A1111\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1251, in postprocess_data
    prediction_value = postprocess_update_dict(
  File "W:\A1111\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 423, in postprocess_update_dict
    update_dict = block.get_specific_update(update_dict)
  File "W:\A1111\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 308, in get_specific_update
    specific_update = cls.update(**generic_update)
TypeError: Radio.update() got an unexpected keyword argument 'info'
Traceback (most recent call last):
  File "W:\A1111\stable-diffusion-webui\venv\lib\site-packages\gradio\routes.py", line 422, in run_predict
    output = await app.get_blocks().process_api(
  File "W:\A1111\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1326, in process_api
    data = self.postprocess_data(fn_index, result["prediction"], state)
  File "W:\A1111\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1251, in postprocess_data
    prediction_value = postprocess_update_dict(
  File "W:\A1111\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 423, in postprocess_update_dict
    update_dict = block.get_specific_update(update_dict)
  File "W:\A1111\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 308, in get_specific_update
    specific_update = cls.update(**generic_update)
TypeError: Radio.update() got an unexpected keyword argument 'info'
Traceback (most recent call last):
  File "W:\A1111\stable-diffusion-webui\venv\lib\site-packages\gradio\routes.py", line 422, in run_predict
    output = await app.get_blocks().process_api(
  File "W:\A1111\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1326, in process_api
    data = self.postprocess_data(fn_index, result["prediction"], state)
  File "W:\A1111\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1251, in postprocess_data
    prediction_value = postprocess_update_dict(
  File "W:\A1111\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 423, in postprocess_update_dict
    update_dict = block.get_specific_update(update_dict)
  File "W:\A1111\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 308, in get_specific_update
    specific_update = cls.update(**generic_update)
TypeError: Radio.update() got an unexpected keyword argument 'info'

**Comment by wkpark** [comment]
`beta` slider is only activated when mode is "Triple sum" or "sum Twice" or calcmode is "tensor" or "tensor2"

**Comment by XT-404** [comment]
@wkpark 


I can activate any model, the cursor remains blocked I have done multiple tests I have the cursor permanently blocked

**Comment by XT-404** [comment]
thx

**Comment by hako-mikan** [comment]
Is the issue still persisting?

**Comment by XT-404** [comment]
> Le problème persiste-t-il ?

YES

**Comment by XT-404** [comment]
> Le problème persiste-t-il ?

the problem and resolve yes thank you very much for the information

**Comment by hako-mikan** [comment]
Could you please tell me the version of gradio?

**Comment by wkpark** [comment]
@XT-404 // recommended gradio version is `gradio==3.41.2`, and you can check your gradio version with `pip show gradio` command (in windows, you can prepare your venv environment, with `venv\activate\activate` command)
~~~bash
pip show gradio
WARNING: Ignoring invalid distribution -rotobuf (f:\webui\webui\stable-diffusion-webui\venv\lib\site-packages)
Name: gradio
Version: 3.41.2
Summary: Python library for easily interacting with trained machine learning models
Home-page:
Author:
Author-email: Abubakar Abid <team@gradio.app>, Ali Abid <team@gradio.app>, Ali Abdalla <team@gradio.app>, Dawood Khan <team@gradio.app>, Ahsen Khaliq <team@gradio.app>, Pete Allen <team@gradio.app>, Ömer Faruk Özdemir <team@gradio.app>
License:
Location: f:\webui\webui\stable-diffusion-webui\venv\lib\site-packages
Requires: aiofiles, altair, fastapi, ffmpy, gradio-client, httpx, huggingface-hub, importlib-resources, jinja2, markupsafe, matplotlib, numpy, orjson, packaging, pandas, pillow, pydantic, pydub, python-multipart, pyyaml, requests, semantic-version, typing-extensions, uvicorn, websockets
Required-by:
~~~

**Comment by wkpark** [comment]
I can reproduce this error with sd-webui v1.5.2

simply upgrade the gradio version will solve it. (e.g. `pip install gradio==3.35.2`)
or fix `requirements.txt`

~~~diff
diff --git a/requirements.txt b/requirements.txt
index b3f8a7f4..03cfc7aa 100644
--- a/requirements.txt
+++ b/requirements.txt
@@ -7,7 +7,7 @@ blendmodes
 clean-fid
 einops
 gfpgan
-gradio==3.32.0
+gradio==3.35.2
 inflection
 jsonmerge
 kornia
~~~
