### ISSUE TITLE
Error merging Lora into checkpoint

### ISSUE THREAD

**Issue by Karsten385** [hako-mikan/sd-webui-supermerger#252]
`boldline: Successfully set the ratio [0.8, 0.8, 0.8, 0.8, 0.8, 0.8, 0.8, 0.8, 0.8, 0.8, 0.8, 0.8, 0.8, 0.8, 0.8, 0.8, 0.8, 0.8, 0.8, 0.8, 0.8, 0.8, 0.8, 0.8, 0.8, 0.8]
boldline:   0%|                                                                                | 0/264 [00:00<?, ?it/s]transformer_text_model_encoder_layers_0_mlp_fc1
transformer_text_model_encoder_layers_0_mlp_fc2
boldline:   1%|▌                                                                               | 2/264 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "C:\Users\user\Desktop\SD\system\python\lib\site-packages\gradio\routes.py", line 488, in run_predict
    output = await app.get_blocks().process_api(
  File "C:\Users\user\Desktop\SD\system\python\lib\site-packages\gradio\blocks.py", line 1431, in process_api
    result = await self.call_function(
  File "C:\Users\user\Desktop\SD\system\python\lib\site-packages\gradio\blocks.py", line 1103, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "C:\Users\user\Desktop\SD\system\python\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "C:\Users\user\Desktop\SD\system\python\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "C:\Users\user\Desktop\SD\system\python\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "C:\Users\user\Desktop\SD\system\python\lib\site-packages\gradio\utils.py", line 707, in wrapper
    response = f(*args, **kwargs)
  File "C:\Users\user\Desktop\SD\webui\extensions\sd-webui-supermerger\scripts\mergers\pluslora.py", line 569, in pluslora
    theta_0 = newpluslora(theta_0,filenames,lweis,names, isxl, keychanger)
  File "C:\Users\user\Desktop\SD\webui\extensions\sd-webui-supermerger\scripts\mergers\pluslora.py", line 675, in newpluslora
    bkey = keychanger[outkey].replace("wieght","bias")
KeyError: 'transformer_text_model_encoder_layers_0_self_attn_out_proj'`

**Comment by hako-mikan** [comment]
Could you please tell me used LoRA and checkpoint?

**Comment by hako-mikan** [comment]
Please try the latest version. It might have been fixed.
