### ISSUE TITLE
Unable to combine xy plots

### ISSUE THREAD

**Issue by uiuiuiui987654** [hako-mikan/sd-webui-supermerger#254]
When using the xy function, after the xy parameters are run, they cannot be combined into an xy graph and the following error occurs.:
[FABRIC] Restoring original U-Net forward pass
Traceback (most recent call last):
  File "G:\stable-diffusion-webui\venv\lib\site-packages\gradio\routes.py", line 422, in run_predict
    output = await app.get_blocks().process_api(
  File "G:\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1323, in process_api
    result = await self.call_function(
  File "G:\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1051, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "G:\stable-diffusion-webui\venv\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "G:\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "G:\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "G:\stable-diffusion-webui\extensions\sd-webui-supermerger\scripts\mergers\xyplot.py", line 77, in numanager
    result,currentmodel,xyimage,a,b,c= sgenxyplot(*allsets)
  File "G:\stable-diffusion-webui\extensions\sd-webui-supermerger\scripts\mergers\xyplot.py", line 455, in sgenxyplot
    grid = smakegrid(xyimage,xs_t,ys_t,gridmodel,image_temp[4])
  File "G:\stable-diffusion-webui\extensions\sd-webui-supermerger\scripts\mergers\xyplot.py", line 480, in smakegrid
    grid = draw_grid_annotations(grid,w,h, hor_texts, ver_texts)
  File "G:\stable-diffusion-webui\extensions\sd-webui-supermerger\scripts\mergers\xyplot.py", line 681, in draw_grid_annotations
    color_active = ImageColor.getcolor(opts.grid_text_active_color, 'RGB')
  File "G:\stable-diffusion-webui\modules\shared.py", line 589, in __getattr__
    return super(Options, self).__getattribute__(item)
AttributeError: 'Options' object has no attribute 'grid_text_active_color'

**Comment by hako-mikan** [comment]
That's a rare error. 
Could you please tell me the version of your web-ui?
