### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'keys'

### ISSUE THREAD

**Issue by guahunyo** [hako-mikan/sd-webui-supermerger#261]
Traceback (most recent call last):
  File "F:\qiuye\sd-webui-aki-v4.4\python\lib\site-packages\gradio\routes.py", line 488, in run_predict
    output = await app.get_blocks().process_api(
  File "F:\qiuye\sd-webui-aki-v4.4\python\lib\site-packages\gradio\blocks.py", line 1431, in process_api
    result = await self.call_function(
  File "F:\qiuye\sd-webui-aki-v4.4\python\lib\site-packages\gradio\blocks.py", line 1103, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "F:\qiuye\sd-webui-aki-v4.4\python\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "F:\qiuye\sd-webui-aki-v4.4\python\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "F:\qiuye\sd-webui-aki-v4.4\python\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "F:\qiuye\sd-webui-aki-v4.4\python\lib\site-packages\gradio\utils.py", line 707, in wrapper
    response = f(*args, **kwargs)
  File "F:\qiuye\sd-webui-aki-v4.4\extensions\sd-webui-supermerger\scripts\mergers\pluslora.py", line 216, in makelora
    result = svd(fullpathfromname(model_a),fullpathfromname(model_b),False,dim,precision,saveto,alpha,beta)
  File "F:\qiuye\sd-webui-aki-v4.4\extensions\sd-webui-supermerger\scripts\mergers\pluslora.py", line 810, in svd
    text_encoder_o, _, unet_o, result  = load_models_from_stable_diffusion_checkpoint(v2, model_b)
  File "F:\qiuye\sd-webui-aki-v4.4\extensions\sd-webui-supermerger\scripts\mergers\model_util.py", line 792, in load_models_from_stable_diffusion_checkpoint
    text_model = CLIPTextModel.from_pretrained("openai/clip-vit-large-patch14")
  File "F:\qiuye\sd-webui-aki-v4.4\python\lib\site-packages\transformers\modeling_utils.py", line 2657, in from_pretrained
    loaded_state_dict_keys = list(state_dict.keys())
AttributeError: 'NoneType' object has no attribute 'keys'

秋叶整合包 最新的 super merger 会报这个 没法两个checkpoint相减出lora 我把super merger 回退到9月5号都不管用

**Comment by hako-mikan** [comment]
I couldn't find cause, please try latest version.
