### ISSUE TITLE
Block weight fail to merge LoRA into checkpoint

### ISSUE THREAD

**Issue by DavideAlidosi** [hako-mikan/sd-webui-supermerger#268]
I'm try to merge a lora into a checkpoint by using a block, but give me this error:
```
Traceback (most recent call last):
  File "L:\A1111 Portable\sd.webui\system\python\lib\site-packages\gradio\routes.py", line 488, in run_predict
    output = await app.get_blocks().process_api(
  File "L:\A1111 Portable\sd.webui\system\python\lib\site-packages\gradio\blocks.py", line 1431, in process_api
    result = await self.call_function(
  File "L:\A1111 Portable\sd.webui\system\python\lib\site-packages\gradio\blocks.py", line 1103, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "L:\A1111 Portable\sd.webui\system\python\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "L:\A1111 Portable\sd.webui\system\python\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "L:\A1111 Portable\sd.webui\system\python\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "L:\A1111 Portable\sd.webui\system\python\lib\site-packages\gradio\utils.py", line 707, in wrapper
    response = f(*args, **kwargs)
  File "L:\A1111 Portable\sd.webui\webui\extensions\sd-webui-supermerger\scripts\mergers\pluslora.py", line 550, in pluslora
    ratio = [float(r)*float(n[1]) for r in ldict[n[2]].split(",")]
  File "L:\A1111 Portable\sd.webui\webui\extensions\sd-webui-supermerger\scripts\mergers\pluslora.py", line 550, in <listcomp>
    ratio = [float(r)*float(n[1]) for r in ldict[n[2]].split(",")]
ValueError: could not convert string to float: 'ratio1'
```
This appening on all LoRAs and model.

**Comment by hako-mikan** [comment]
You need to enter the intensity as using LoRA on the prompt.
`<lora:testlora:1:MIDD>`
