### ISSUE TITLE
cant merge lora to checkpoint

### ISSUE THREAD

**Issue by guahunyo** [hako-mikan/sd-webui-supermerger#282]
Plus LoRA start
Loading chilloutmix_NiPrunedFp32Fix.safetensors [fc2511737a]
Traceback (most recent call last):
  File "D:\BaiduNetdiskDownload\01-01HH\novelai-webui-aki-v3A\py310\lib\site-packages\gradio\routes.py", line 488, in run_predict
    output = await app.get_blocks().process_api(
  File "D:\BaiduNetdiskDownload\01-01HH\novelai-webui-aki-v3A\py310\lib\site-packages\gradio\blocks.py", line 1431, in process_api
    result = await self.call_function(
  File "D:\BaiduNetdiskDownload\01-01HH\novelai-webui-aki-v3A\py310\lib\site-packages\gradio\blocks.py", line 1103, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "D:\BaiduNetdiskDownload\01-01HH\novelai-webui-aki-v3A\py310\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "D:\BaiduNetdiskDownload\01-01HH\novelai-webui-aki-v3A\py310\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "D:\BaiduNetdiskDownload\01-01HH\novelai-webui-aki-v3A\py310\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "D:\BaiduNetdiskDownload\01-01HH\novelai-webui-aki-v3A\py310\lib\site-packages\gradio\utils.py", line 707, in wrapper
    response = f(*args, **kwargs)
  File "D:\BaiduNetdiskDownload\01-01HH\novelai-webui-aki-v3A\extensions\sd-webui-supermerger\scripts\mergers\pluslora.py", line 691, in pluslora
    orig_checkpoint = shared.sd_model.sd_checkpoint_info
AttributeError: 'NoneType' object has no attribute 'sd_checkpoint_info'

Newest sd webui
newest supermerger

cant merge lora to checkpoint  and  cant  make a lora(A-B)

**Comment by hako-mikan** [comment]
Dose your Newest sd webui mean Automatic1111 web-ui ver 1.6.0?

**Comment by guahunyo** [comment]
> Dose your Newest sd webui mean Automatic1111 web-ui ver 1.6.0?

1.6.1

**Comment by guahunyo** [comment]
> > Dose your Newest sd webui mean Automatic1111 web-ui ver 1.6.0?
> 
> 1.6.1

https://github.com/AUTOMATIC1111/stable-diffusion-webui/commit/4afaaf8a020c1df457bcf7250cb1c7f609699fa7

**Comment by hako-mikan** [comment]
Thanks, fixed.

**Comment by guahunyo** [comment]
> Thanks, fixed.

thanks its ok now

**Comment by shfeat** [comment]
![image](https://github.com/hako-mikan/sd-webui-supermerger/assets/10511524/5bc0ea03-ddc6-404e-99fb-b46c519712f7)

same error when make lora (modelA - modelB)
