### ISSUE TITLE
*** Error loading script: supermerger.py

### ISSUE THREAD

**Issue by ivever2** [hako-mikan/sd-webui-supermerger#283]
[v1.6.0-2-g4afaaf8a]  •  python: 3.10.8  •  torch: 2.1.0+cu121  •  xformers: 0.0.22.post7  •  gradio: 3.41.2  

---------------------------------------------------

*** Error loading script: supermerger.py
    Traceback (most recent call last):
      File "D:\AI\novelai-webui-aki-v3\modules\scripts.py", line 382, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "D:\AI\novelai-webui-aki-v3\modules\script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "D:\AI\novelai-webui-aki-v3\extensions\sd-webui-supermerger\scripts\supermerger.py", line 23, in <module>
        import scripts.mergers.pluslora
      File "D:\AI\novelai-webui-aki-v3\extensions\sd-webui-supermerger\scripts\mergers\pluslora.py", line 19, in <module>
        from scripts.kohyas import extract_lora_from_models as ext
      File "D:\AI\novelai-webui-aki-v3\extensions\sd-webui-supermerger\scripts\kohyas\extract_lora_from_models.py", line 12, in <module>
        from scripts.kohyas import sai_model_spec,model_util,sdxl_model_util,lora
      File "D:\AI\novelai-webui-aki-v3\extensions\sd-webui-supermerger\scripts\kohyas\sdxl_model_util.py", line 7, in <module>
        from diffusers import AutoencoderKL, EulerDiscreteScheduler, UNet2DConditionModel
    ImportError: cannot import name 'EulerDiscreteScheduler' from 'diffusers' (D:\AI\novelai-webui-aki-v3\py310\lib\site-packages\diffusers\__init__.py)
提示：Python 运行时抛出了一个异常。请检查疑难解答页面。

**Comment by hako-mikan** [comment]
Maybe version of diffusers is wrong. Check it.

**Comment by ivever2** [comment]
Does not support version 1.6.0?

**Comment by hako-mikan** [comment]
This is not the version of the Web-ui. It seems likely that the version of the module called 'diffusers' is small. You need to update it. The method of updating varies depending on the environment, so please look it up.

**Comment by wkpark** [comment]
the minimal version of diffusers is 0.21.1, I think (SDXL supported diffusers). you can check the version of installed diffusers with the following
~~~
pip show diffusers
~~~

**Comment by ivever2** [comment]
The version is like this.Still displaying Error loading script....

>pip show diffusers
Name: diffusers
Version: 0.23.0
Summary: State-of-the-art diffusion in PyTorch and JAX.
Home-page: https://github.com/huggingface/diffusers
Author: The HuggingFace team
Author-email: patrick@huggingface.co
License: Apache
Location: c:\users\wangfan\appdata\local\programs\python\python310\lib\site-packages
Requires: filelock, huggingface-hub, importlib-metadata, numpy, Pillow, regex, requests, safetensors
Required-by:

**Comment by wkpark** [comment]
EulerDiscreteScheduler was added from v0.7.0

you've installed v0.23.0 but webui use `venv` and the library location is different from it. (not  `c:\users\wangfan\appdata...`)

- activate `venv` --> `(venv)` prompt appeard
- check `diffusers` version with `pip show diffusers`
- update `diffusers` with `pip install diffusers`
~~~cmd
cd your_webui_dir
venv\Scripts\activate.bat
(venv) pip show diffusers
...
(venv) pip uninstall diffusers
(venv) pip install diffusers (or diffusers==0.23.0)
~~~

**Comment by ivever2** [comment]
I have already installed diffusers in venv：
-----------------------
D:\AI\novelai-webui-aki-v3\venv\Scripts>pip show diffusers
Name: diffusers
Version: 0.23.0
Summary: State-of-the-art diffusion in PyTorch and JAX.
Home-page: https://github.com/huggingface/diffusers
Author: The HuggingFace team
Author-email: patrick@huggingface.co
License: Apache
Location: d:\ai\novelai-webui-aki-v3\venv\lib\site-packages
Requires: filelock, huggingface-hub, importlib-metadata, numpy, Pillow, regex, requests, safetensors
Required-by:
==============

But when the webui launch, it still prompts:
-----------------
*** Error loading script: supermerger.py
    Traceback (most recent call last):
      File "D:\AI\novelai-webui-aki-v3\modules\scripts.py", line 382, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "D:\AI\novelai-webui-aki-v3\modules\script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "D:\AI\novelai-webui-aki-v3\extensions\sd-webui-supermerger\scripts\supermerger.py", line 23, in <module>
        import scripts.mergers.pluslora
      File "D:\AI\novelai-webui-aki-v3\extensions\sd-webui-supermerger\scripts\mergers\pluslora.py", line 19, in <module>
        from scripts.kohyas import extract_lora_from_models as ext
      File "D:\AI\novelai-webui-aki-v3\extensions\sd-webui-supermerger\scripts\kohyas\extract_lora_from_models.py", line 12, in <module>
        from scripts.kohyas import sai_model_spec,model_util,sdxl_model_util,lora
      File "D:\AI\novelai-webui-aki-v3\extensions\sd-webui-supermerger\scripts\kohyas\sdxl_model_util.py", line 7, in <module>
        from diffusers import AutoencoderKL, EulerDiscreteScheduler, UNet2DConditionModel
    ImportError: cannot import name 'EulerDiscreteScheduler' from 'diffusers' (D:\AI\novelai-webui-aki-v3\py310\lib\site-packages\diffusers\__init__.py)

**Comment by ivever2** [comment]
I have already installed diffusers in venv：
-------------
D:\AI\novelai-webui-aki-v3\venv\Scripts>pip show diffusers
Name: diffusers
Version: 0.23.0
Summary: State-of-the-art diffusion in PyTorch and JAX.
Home-page: https://github.com/huggingface/diffusers
Author: The HuggingFace team
Author-email: [patrick@huggingface.co](mailto:patrick@huggingface.co)
License: Apache
Location: d:\ai\novelai-webui-aki-v3\venv\lib\site-packages
Requires: filelock, huggingface-hub, importlib-metadata, numpy, Pillow, regex, requests, safetensors
Required-by:

==============
But when the webui launch, it still prompts:
------------
*** Error loading script: supermerger.py
Traceback (most recent call last):
File "D:\AI\novelai-webui-aki-v3\modules\scripts.py", line 382, in load_scripts
script_module = script_loading.load_module(scriptfile.path)
File "D:\AI\novelai-webui-aki-v3\modules\script_loading.py", line 10, in load_module
module_spec.loader.exec_module(module)
File "", line 883, in exec_module
File "", line 241, in call_with_frames_removed
File "D:\AI\novelai-webui-aki-v3\extensions\sd-webui-supermerger\scripts\supermerger.py", line 23, in
import scripts.mergers.pluslora
File "D:\AI\novelai-webui-aki-v3\extensions\sd-webui-supermerger\scripts\mergers\pluslora.py", line 19, in
from scripts.kohyas import extract_lora_from_models as ext
File "D:\AI\novelai-webui-aki-v3\extensions\sd-webui-supermerger\scripts\kohyas\extract_lora_from_models.py", line 12, in
from scripts.kohyas import sai_model_spec,model_util,sdxl_model_util,lora
File "D:\AI\novelai-webui-aki-v3\extensions\sd-webui-supermerger\scripts\kohyas\sdxl_model_util.py", line 7, in
from diffusers import AutoencoderKL, EulerDiscreteScheduler, UNet2DConditionModel
ImportError: cannot import name 'EulerDiscreteScheduler' from 'diffusers' (D:\AI\novelai-webui-aki-v3\py310\lib\site-packages\diffusers_init.py)

**Comment by wkpark** [comment]
your log says
~~~
ImportError: cannot import name 'EulerDiscreteScheduler' from 'diffusers' (D:\AI\novelai-webui-aki-v3\py310\lib\site-packages\diffusers_init.py)
~~~
there is another `diffusers` package found at `D:\AI\novelai-webui-aki-v3\py310\lib\site-packages`
check the path `D:\AI\novelai-webui-aki-v3\py310\lib\site-packages`

**Comment by ivever2** [comment]
The problem has been resolved. After deleting the diffusers directory in py310, no longer report any errors.
**Thank you very much for your help!! :D**
