### ISSUE TITLE
Error with "Use Cuda"

### ISSUE THREAD

**Issue by TigonTX** [hako-mikan/sd-webui-supermerger#288]
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!

**Comment by Neytiri7** [comment]
same issue

**Comment by hako-mikan** [comment]
Tell me your environment.
Start up settings, Web-ui versions, extensions.
When dose this error occur?

**Comment by Neytiri7** [comment]
I got a log like this.
ver. [v1.6.0-2-g4afaaf8a]

`Traceback (most recent call last):
  File "O:\AI\SynologyDrive\stable-diffusion-webui\venv\lib\site-packages\gradio\routes.py", line 488, in run_predict
    output = await app.get_blocks().process_api(
  File "O:\AI\SynologyDrive\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1431, in process_api
    result = await self.call_function(
  File "O:\AI\SynologyDrive\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1103, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "O:\AI\SynologyDrive\stable-diffusion-webui\venv\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "O:\AI\SynologyDrive\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "O:\AI\SynologyDrive\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "O:\AI\SynologyDrive\stable-diffusion-webui\venv\lib\site-packages\gradio\utils.py", line 707, in wrapper
    response = f(*args, **kwargs)
  File "O:\AI\SynologyDrive\stable-diffusion-webui\extensions\sd-webui-supermerger\scripts\mergers\mergers.py", line 106, in smergegen
    result,currentmodel,modelid,theta_0,metadata = smerge(
  File "O:\AI\SynologyDrive\stable-diffusion-webui\extensions\sd-webui-supermerger\scripts\mergers\mergers.py", line 417, in smerge
    theta_0_a =lerp(theta_0_a.to(torch.float32),lerp(theta_1[key].to(torch.float32),theta_2[key].to(torch.float32),current_beta/(current_alpha + current_beta)),current_alpha + current_beta).to(theta_0_a.dtype)
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!`


Another log just came out.

`Traceback (most recent call last):
  File "O:\AI\SynologyDrive\stable-diffusion-webui\venv\lib\site-packages\gradio\routes.py", line 488, in run_predict
    output = await app.get_blocks().process_api(
  File "O:\AI\SynologyDrive\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1431, in process_api
    result = await self.call_function(
  File "O:\AI\SynologyDrive\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1103, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "O:\AI\SynologyDrive\stable-diffusion-webui\venv\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "O:\AI\SynologyDrive\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "O:\AI\SynologyDrive\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "O:\AI\SynologyDrive\stable-diffusion-webui\venv\lib\site-packages\gradio\utils.py", line 707, in wrapper
    response = f(*args, **kwargs)
  File "O:\AI\SynologyDrive\stable-diffusion-webui\extensions\sd-webui-supermerger\scripts\mergers\mergers.py", line 106, in smergegen
    result,currentmodel,modelid,theta_0,metadata = smerge(
  File "O:\AI\SynologyDrive\stable-diffusion-webui\extensions\sd-webui-supermerger\scripts\mergers\mergers.py", line 417, in smerge
    theta_0_a =lerp(theta_0_a.to(torch.float32),lerp(theta_1[key].to(torch.float32),theta_2[key].to(torch.float32),current_beta/(current_alpha + current_beta)),current_alpha + current_beta).to(theta_0_a.dtype)
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 50.00 MiB (GPU 0; 4.00 GiB total capacity; 18.03 GiB already allocated; 0 bytes free; 18.67 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF`

**Comment by hako-mikan** [comment]
It seems that you are currently using 'sum twice', but does this error occur in other modes as well?
An error indicating insufficient memory is appearing, so there may not be enough VRAM. Merging three 2G models requires at least 8G of VRAM, but this may not be sufficient.

**Comment by Neytiri7** [comment]
Both "Weight sum" and "Triple sum" modes, which are mainly used, occur the same.

"sum wise" This mode is not used.

And, with USE CUDA, memory is accumulated intermittently, and if you merge it a few times, you need to reboot your computer.

If you don't check that USE CUDA, it usually takes a long time to merge and check.

**Comment by zzz7xz** [comment]
When using "use cuda" and "Adjust" together, I got the same error.
Merge mode: Weight sum, Calculation mode: normal.
Web UI and this extension are the latest.

```
  File "J:\\stable-diffusion-webui\extensions\sd-webui-supermerger\scripts\mergers\mergers.py", line 106, in smergegen
    result,currentmodel,modelid,theta_0,metadata = smerge(
  File "J:\\stable-diffusion-webui\extensions\sd-webui-supermerger\scripts\mergers\mergers.py", line 494, in smerge
    else :theta_0[key] =theta_0[key] + torch.tensor(fine[5])
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!
```
