### ISSUE TITLE
TypeError: can't convert cuda:0 device type tensor to numpy. (cosineAB + use cuda)

### ISSUE THREAD

**Issue by zzz7xz** [hako-mikan/sd-webui-supermerger#289]
cosineA / cosineBとuse cudaの併用で以下のエラーが出ました。
```
Traceback (most recent call last):
  File "J:\\stable-diffusion-webui\extensions\sd-webui-supermerger\scripts\mergers\mergers.py", line 106, in smergegen
    result,currentmodel,modelid,theta_0,metadata = smerge(
  File "J:\\stable-diffusion-webui\extensions\sd-webui-supermerger\scripts\mergers\mergers.py", line 349, in smerge
    sim, sims = precosine("A" in calcmode,theta_0,theta_1)
  File "J:\\stable-diffusion-webui\extensions\sd-webui-supermerger\scripts\mergers\mergers.py", line 588, in precosine
    sims = np.append(sims,simab.numpy())
TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.
```
mergers.pyの588行目を
`sims = np.append(sims,simab.detach().cpu().numpy())`
に変更したところ、コード的に正しいかはわからないですが、
一応エラーは出なくなりました。

※追記です。
上記だけだとcosineBで同じエラーが出たので604行目を
`sims = np.append(sims, combined_similarity.detach().cpu().numpy())`
に変更したところ、エラーは出なくなりました。

**Comment by hako-mikan** [comment]
cosineA / cosineBだとCPUに切り替えて計算する過程が入るので、エラーの有無にかかわらず、cudaを指定する意味がありません。

**Comment by zzz7xz** [comment]
こちらのPCではuse cudaで
normal 6s -> 4s
cosineA 24s -> 18s
にそれぞれ短縮しました。

**Comment by hako-mikan** [comment]
なるほど他の部分で短縮になるのですね。
修正しておきました。ありがとうございます。

**Comment by zzz7xz** [comment]
ありがとうございます！修正確認しました。
