### ISSUE TITLE
Error Merge LoRA to Checkpoint

### ISSUE THREAD

**Issue by YinnVI** [hako-mikan/sd-webui-supermerger#29]
plus LoRA start
Loading Hakoyume BETA v1b-NoiseOffset.safetensors
loading: Fuzicho2s1
merging... [1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0]
Traceback (most recent call last):
  File "C:\Stable Diffusion WebUI\venv\lib\site-packages\gradio\routes.py", line 337, in run_predict
    output = await app.get_blocks().process_api(
  File "C:\Stable Diffusion WebUI\venv\lib\site-packages\gradio\blocks.py", line 1015, in process_api
    result = await self.call_function(
  File "C:\Stable Diffusion WebUI\venv\lib\site-packages\gradio\blocks.py", line 833, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "C:\Stable Diffusion WebUI\venv\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "C:\Stable Diffusion WebUI\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "C:\Stable Diffusion WebUI\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "C:\Stable Diffusion WebUI\extensions\sd-webui-supermerger\scripts\mergers\pluslora.py", line 305, in pluslora
    weight = theta_0[keychanger[msd_key]]
KeyError: 'lora_unet_down_blocks_0_downsamplers_0_conv'

**Comment by HeavyTony2** [comment]
Can't tell if my error is related, but here's mine
Traceback (most recent call last):
```
  File "/usr/local/lib/python3.9/dist-packages/gradio/routes.py", line 337, in run_predict
    output = await app.get_blocks().process_api(
  File "/usr/local/lib/python3.9/dist-packages/gradio/blocks.py", line 1015, in process_api
    result = await self.call_function(
  File "/usr/local/lib/python3.9/dist-packages/gradio/blocks.py", line 833, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/usr/local/lib/python3.9/dist-packages/anyio/to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/usr/local/lib/python3.9/dist-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "/usr/local/lib/python3.9/dist-packages/anyio/_backends/_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/sd-webui-supermerger/scripts/mergers/pluslora.py", line 309, in pluslora
    weight = weight  + ratio * (up_weight @ down_weight) * scale
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!
```

**Comment by hako-mikan** [comment]
LoCON/LyCORIS cannot be fully supported due to its special structure. The author of LoCON/LyCORIS provides a merge tool, so you may want to use that.
