### ISSUE TITLE
Error when merging

### ISSUE THREAD

**Issue by Nalwonk** [hako-mikan/sd-webui-supermerger#3]
When I attempt to merge I get the following error:
```Loading weights [Anything-V3.0-pruned-fp16] from file
Stage 1/2: 100%|██████████████████████████████████████████████████████████████████| 1133/1133 [00:09<00:00, 125.59it/s]
Stage 2/2: 100%|██████████████████████████████████████████████████████████████| 1143/1143 [00:00<00:00, 1142810.36it/s]
Applying xformers cross attention optimization.
Traceback (most recent call last):
  File "G:\difuse\SD\Frig\frig2\stable-diffusion-webui\venv\lib\site-packages\gradio\routes.py", line 337, in run_predict
    output = await app.get_blocks().process_api(
  File "G:\difuse\SD\Frig\frig2\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1015, in process_api
    result = await self.call_function(
  File "G:\difuse\SD\Frig\frig2\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 833, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "G:\difuse\SD\Frig\frig2\stable-diffusion-webui\venv\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "G:\difuse\SD\Frig\frig2\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "G:\difuse\SD\Frig\frig2\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "G:\difuse\SD\Frig\frig2\stable-diffusion-webui\extensions\sd-webui-supermerger\scripts\mergers\mergers.py", line 51, in smergegen
    usemodelgen(theta_0,model_a)
  File "G:\difuse\SD\Frig\frig2\stable-diffusion-webui\extensions\sd-webui-supermerger\scripts\mergers\model_util.py", line 816, in usemodelgen
    lowvram.setup_for_low_vram(model, shared.cmd_opts.medvram)
  File "G:\difuse\SD\Frig\frig2\stable-diffusion-webui\modules\lowvram.py", line 60, in setup_for_low_vram
    stored = sd_model.cond_stage_model.transformer, sd_model.first_stage_model, getattr(sd_model, 'depth_model', None), sd_model.model
  File "G:\difuse\SD\Frig\frig2\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1269, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'FrozenCLIPEmbedderWithCustomWords' object has no attribute 'transformer'```

**Comment by hako-mikan** [comment]
Thanks for reporting
Fixed what appeared to be a bug. It should now work.

**Comment by ljleb** [comment]
Hi, I'm currently looking to do merges in memory for a different extension. I believe this issue is the origin of this diff:
https://github.com/hako-mikan/sd-webui-supermerger/commit/01f13c300c468426f90923930ac0d85a454a4292

Is it possible not registering hooks for `sd_model.cond_stage_model.transformer` and `sd_model.embedder` could create a problem when generating? I would think the webui calls these functions for a reason.

I am confused at the moment, as I have little insight on the purpose of these arbitrary lines of code.
I would appreciate it a lot if you could help me figure this one @hako-mikan!

**Comment by hako-mikan** [comment]
Is this issue still occurring?

**Comment by ljleb** [comment]
Hi, sorry if my comment above was unclear. No error here, I was just trying to get a better grasp of the internals of the webui and the interactions with this extension.

**Comment by hako-mikan** [comment]
Understood. 
I am also just copying the original code, so I don't fully understand what is happening here, especially you mentioned.
