### ISSUE TITLE
Error with pluslora

### ISSUE THREAD

**Issue by slimybastard** [hako-mikan/sd-webui-supermerger#30]
After updating the script I am getting the following error in the cmd window, and the extension fails to load.

```
Error loading script: supermerger.py
Traceback (most recent call last):
  File "D:\SD\stable-diffusion-webui\modules\scripts.py", line 229, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "D:\SD\stable-diffusion-webui\modules\script_loading.py", line 11, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\SD\stable-diffusion-webui\extensions\sd-webui-supermerger\scripts\supermerger.py", line 13, in <module>
    import scripts.mergers.pluslora as pluslora
  File "D:\SD\stable-diffusion-webui\extensions\sd-webui-supermerger\scripts\mergers\pluslora.py", line 2, in <module>
    from sklearn.linear_model import PassiveAggressiveClassifier
ModuleNotFoundError: No module named 'sklearn'
```

I have installed sklearn, which did not fix the error. After some googling, it seems like it has been replaced by scikit-learn, which I have also installed, but it did not fix the error. 
Note: I'm not using this for Loras, so I was able to get around this and benefit from hiresfix by commenting out anything to do with pluslora in supermerger.py

**Comment by frugally9415** [comment]
Up. I am having the same issue.

**Comment by bbaaxx** [comment]
I was able to get it to work by installing `scikit-learn`  manually:

`pip install scikit-learn`

**Comment by frugally9415** [comment]
@bbaaxx
Thank you. It work.

**Comment by slimybastard** [comment]
@bbaaxx That's what I did as well, but it didn't solve the issue unfortunately.

**Comment by Lifecycle612** [comment]
possibly
`pip install --upgrade pip`
after that
`pip install scikit-learn`
