### ISSUE TITLE
モデルへのLoRAマージが失敗するケースがある

### ISSUE THREAD

**Issue by JujoHotaru** [hako-mikan/sd-webui-supermerger#303]
いつもお世話になっております。

12月7日時点の最新リビジョンで、モデルへのLoRAマージが失敗するケースがありました。
10月16日コミット（d929669d98c1107f2fa6635272692e4f84f3d659）の状態で保存していたSuperMerger環境(WebUI 1.5.1)ですとエラーが起こらずマージできましたので、SuperMerger側の問題かなと判断してご報告します。

ひとまず発生した状態を記載します。

モデル：anitoonByAgress_v13.safetensors https://civitai.com/models/209385/anitoon-by-agress
LoRA：HyperDetailer 0.95 https://civitai.com/models/196752?modelVersionId=229782

通常の生成（LoRAをプロンプトに記載して生成）は動作する状態です。

SuperMergerのLoRAページでanitoonByAgress_v13のモデルを選択し、LoRA入力欄に「`hyperdetailer_v095:1.0`」と入力、あとはデフォルト設定でマージすると、以下のエラーが発生しました。
なお、LoRAを「flat2」にすると正常にマージできたので、成否はLoRAの種類にもよるようです。

```
Loading anitoonByAgress_v13.safetensors [2de157e61a]
Reusing loaded model HotaruBreed_RealMix_v30_base1.fp16.safetensors [04b374145b] to load anitoonByAgress_v13.safetensors [2de157e61a]
Loading weights [2de157e61a] from C:\stable-diffusion-webui\models\Stable-diffusion\anitoonByAgress_v13.safetensors
Loading VAE weights specified in settings: C:\stable-diffusion-webui\models\VAE\clearvae_main.safetensors
Applying attention optimization: sdp-no-mem... done.
Weights loaded in 2.0s (calculate hash: 0.7s, load weights from disk: 0.2s, apply weights to model: 0.3s, load VAE: 0.2s, move model to device: 0.6s).
hyperdetailer_v095: Successfully set the ratio [1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0]
hyperdetailer_v095:   0%|                                                                      | 0/264 [00:00<?, ?it/s]transformer_text_model_encoder_layers_0_mlp_fc1
transformer_text_model_encoder_layers_0_mlp_fc2
hyperdetailer_v095:   1%|▌                                                                     | 2/264 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "C:\stable-diffusion-webui\venv\lib\site-packages\gradio\routes.py", line 488, in run_predict
    output = await app.get_blocks().process_api(
  File "C:\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1431, in process_api
    result = await self.call_function(
  File "C:\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1103, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "C:\stable-diffusion-webui\venv\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "C:\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "C:\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "C:\stable-diffusion-webui\venv\lib\site-packages\gradio\utils.py", line 707, in wrapper
    response = f(*args, **kwargs)
  File "C:\stable-diffusion-webui\extensions\sd-webui-supermerger\scripts\mergers\pluslora.py", line 728, in pluslora
    theta_0 = newpluslora(theta_0,filenames,lweis,names, isxl,isv2, keychanger)
  File "C:\stable-diffusion-webui\extensions\sd-webui-supermerger\scripts\mergers\pluslora.py", line 835, in newpluslora
    bkey = keychanger[outkey].replace("wieght","bias")
KeyError: 'transformer_text_model_encoder_layers_0_self_attn_out_proj'
```

追伸ですが、エラーログ下から2行目、「keychanger[outkey].replace("wieght","bias")」の部分は「weight」のミスでしょうか？（書き換えて実行してみましたがエラー内容は変わりませんでした）

**Comment by JujoHotaru** [comment]
補足になります。

10月16日版でも、組み合わせによって同じエラーが生じる場合があるようでした。

**Comment by hako-mikan** [comment]
モデルは普通に生成する分には使えてるので正常のようですが、keyの値が他とは違うようです。このモデルでもマージできるよう修正しました。

**Comment by JujoHotaru** [comment]
マイナー不具合にもかかわらずご対応ありがとうございました。
当該モデルマージができるようになりました。
