### ISSUE TITLE
Can not merge block weights of most loras to checkpoints, extract lora also does not work with most loras

### ISSUE THREAD

**Issue by Deathawaits4** [hako-mikan/sd-webui-supermerger#307]
when merging certain models with block weight i get this:

`2023-12-10T04:59:21.975267536+01:00 Applying attention optimization: xformers... done.
2023-12-10T04:59:22.124172292+01:00 Model loaded in 5.2s (load weights from disk: 0.6s, create model: 3.2s, apply weights to model: 1.1s, calculate empty prompt: 0.1s).
2023-12-10T05:00:34.669961929+01:00 Plus LoRA start
2023-12-10T05:00:34.670007809+01:00 Loading sd_xl_base_1.0.safetensors [31e35c80fc]
2023-12-10T05:00:45.211789885+01:00 unchanged modules: ['1_model_transformer_resblocks_0_mlp_c_fc', '1_model_transformer_resblocks_0_mlp_c_proj', '1_model_transformer_resblocks_0_attn_k_proj', '1_model_transformer_resblocks_0_attn_out_proj', '1_model_transformer_resblocks_0_attn_q_proj', '1_model_transformer_resblocks_0_attn_v_proj', '1_model_transformer_resblocks_10_mlp_c_fc', '1_model_transformer_resblocks_10_mlp_c_proj', '1_model_transformer_resblocks_10_attn_k_proj', '1_model_transformer_resblocks_10_attn_out_proj', '1_model_transformer_resblocks_10_attn_q_proj', '1_model_transformer_resblocks_10_attn_v_proj', '1_model_transformer_resblocks_11_mlp_c_fc', '1_model_transformer_resblocks_11_mlp_c_proj', '1_model_transformer_resblocks_11_attn_k_proj', '1_model_transformer_resblocks_11_attn_out_proj', '1_model_transformer_resblocks_11_attn_q_proj', '1_model_transformer_resblocks_11_attn_v_proj', '1_model_transformer_resblocks_12_mlp_c_fc', '1_model_transformer_resblocks_12_mlp_c_proj', '1_model_transformer_resblocks_12_attn_k_proj', '1_model_transformer_resblocks_12_attn_out_proj', '1_model_transformer_resblocks_12_attn_q_proj', '1_model_transformer_resblocks_12_attn_v_proj', '1_model_transformer_resblocks_13_mlp_c_fc', '1_model_transformer_resblocks_13_mlp_c_proj', '1_model_transformer_resblocks_13_attn_k_proj', '1_model_transformer_resblocks_13_attn_out_proj', '1_model_transformer_resblocks_13_attn_q_proj', '1_model_transformer_resblocks_13_attn_v_proj', '1_model_transformer_resblocks_14_mlp_c_fc', '1_model_transformer_resblocks_14_mlp_c_proj', '1_model_transformer_resblocks_14_attn_k_proj', '1_model_transformer_resblocks_14_attn_out_proj', '1_model_transformer_resblocks_14_attn_q_proj', '1_model_transformer_resblocks_14_attn_v_proj', '1_model_transformer_resblocks_15_mlp_c_fc', '1_model_transformer_resblocks_15_mlp_c_proj', '1_model_transformer_resblocks_15_attn_k_proj', '1_model_transformer_resblocks_15_attn_out_proj', '1_model_transformer_resblocks_15_attn_q_proj', '1_model_transformer_resblocks_15_attn_v_proj', '1_model_transformer_resblocks_16_mlp_c_fc', '1_model_transformer_resblocks_16_mlp_c_proj', '1_model_transformer_resblocks_16_attn_k_proj', '1_model_transformer_resblocks_16_attn_out_proj', '1_model_transformer_resblocks_16_attn_q_proj', '1_model_transformer_resblocks_16_attn_v_proj', '1_model_transformer_resblocks_17_mlp_c_fc', '1_model_transformer_resblocks_17_mlp_c_proj', '1_model_transformer_resblocks_17_attn_k_proj', '1_model_transformer_resblocks_17_attn_out_proj', '1_model_transformer_resblocks_17_attn_q_proj', '1_model_transformer_resblocks_17_attn_v_proj', '1_model_transformer_resblocks_18_mlp_c_fc', '1_model_transformer_resblocks_18_mlp_c_proj', '1_model_transformer_resblocks_18_attn_k_proj', '1_model_transformer_resblocks_18_attn_out_proj', '1_model_transformer_resblocks_18_attn_q_proj', '1_model_transformer_resblocks_18_attn_v_proj', '1_model_transformer_resblocks_19_mlp_c_fc', '1_model_transformer_resblocks_19_mlp_c_proj', '1_model_transformer_resblocks_19_attn_k_proj', '1_model_transformer_resblocks_19_attn_out_proj', '1_model_transformer_resblocks_19_attn_q_proj', '1_model_transformer_resblocks_19_attn_v_proj', '1_model_transformer_resblocks_1_mlp_c_fc', '1_model_transformer_resblocks_1_mlp_c_proj', '1_model_transformer_resblocks_1_attn_k_proj', '1_model_transformer_resblocks_1_attn_out_proj', '1_model_transformer_resblocks_1_attn_q_proj', '1_model_transformer_resblocks_1_attn_v_proj', '1_model_transformer_resblocks_20_mlp_c_fc', '1_model_transformer_resblocks_20_mlp_c_proj', '1_model_transformer_resblocks_20_attn_k_proj', '1_model_transformer_resblocks_20_attn_out_proj', '1_model_transformer_resblocks_20_attn_q_proj', '1_model_transformer_resblocks_20_attn_v_proj', '1_model_transformer_resblocks_21_mlp_c_fc', '1_model_transformer_resblocks_21_mlp_c_proj', '1_model_transformer_resblocks_21_attn_k_proj', '1_model_transformer_resblocks_21_attn_out_proj', '1_model_transformer_resblocks_21_attn_q_proj', '1_model_transformer_resblocks_21_attn_v_proj', '1_model_transformer_resblocks_22_mlp_c_fc', '1_model_transformer_resblocks_22_mlp_c_proj', '1_model_transformer_resblocks_22_attn_k_proj', '1_model_transformer_resblocks_22_attn_out_proj', '1_model_transformer_resblocks_22_attn_q_proj', '1_model_transformer_resblocks_22_attn_v_proj', '1_model_transformer_resblocks_23_mlp_c_fc', '1_model_transformer_resblocks_23_mlp_c_proj', '1_model_transformer_resblocks_23_attn_k_proj', '1_model_transformer_resblocks_23_attn_out_proj', '1_model_transformer_resblocks_23_attn_q_proj', '1_model_transformer_resblocks_23_attn_v_proj', '1_model_transformer_resblocks_24_mlp_c_fc', '1_model_transformer_resblocks_24_mlp_c_proj', '1_model_transformer_resblocks_24_attn_k_proj', '1_model_transformer_resblocks_24_attn_out_proj', '1_model_transformer_resblocks_24_attn_q_proj', '1_model_transformer_resblocks_24_attn_v_proj', '1_model_transformer_resblocks_25_mlp_c_fc', '1_model_transformer_resblocks_25_mlp_c_proj', '1_model_transformer_resblocks_25_attn_k_proj', '1_model_transformer_resblocks_25_attn_out_proj', '1_model_transformer_resblocks_25_attn_q_proj', '1_model_transformer_resblocks_25_attn_v_proj', '1_model_transformer_resblocks_26_mlp_c_fc', '1_model_transformer_resblocks_26_mlp_c_proj', '1_model_transformer_resblocks_26_attn_k_proj', '1_model_transformer_resblocks_26_attn_out_proj', '1_model_transformer_resblocks_26_attn_q_proj', '1_model_transformer_resblocks_26_attn_v_proj', '1_model_transformer_resblocks_27_mlp_c_fc', '1_model_transformer_resblocks_27_mlp_c_proj', '1_model_transformer_resblocks_27_attn_k_proj', '1_model_transformer_resblocks_27_attn_out_proj', '1_model_transformer_resblocks_27_attn_q_proj', '1_model_transformer_resblocks_27_attn_v_proj', '1_model_transformer_resblocks_28_mlp_c_fc', '1_model_transformer_resblocks_28_mlp_c_proj', '1_model_transformer_resblocks_28_attn_k_proj', '1_model_transformer_resblocks_28_attn_out_proj', '1_model_transformer_resblocks_28_attn_q_proj', '1_model_transformer_resblocks_28_attn_v_proj', '1_model_transformer_resblocks_29_mlp_c_fc', '1_model_transformer_resblocks_29_mlp_c_proj', '1_model_transformer_resblocks_29_attn_k_proj', '1_model_transformer_resblocks_29_attn_out_proj', '1_model_transformer_resblocks_29_attn_q_proj', '1_model_transformer_resblocks_29_attn_v_proj', '1_model_transformer_resblocks_2_mlp_c_fc', '1_model_transformer_resblocks_2_mlp_c_proj', '1_model_transformer_resblocks_2_attn_k_proj', '1_model_transformer_resblocks_2_attn_out_proj', '1_model_transformer_resblocks_2_attn_q_proj', '1_model_transformer_resblocks_2_attn_v_proj', '1_model_transformer_resblocks_30_mlp_c_fc', '1_model_transformer_resblocks_30_mlp_c_proj', '1_model_transformer_resblocks_30_attn_k_proj', '1_model_transformer_resblocks_30_attn_out_proj', '1_model_transformer_resblocks_30_attn_q_proj', '1_model_transformer_resblocks_30_attn_v_proj', '1_model_transformer_resblocks_31_mlp_c_fc', '1_model_transformer_resblocks_31_mlp_c_proj', '1_model_transformer_resblocks_31_attn_k_proj', '1_model_transformer_resblocks_31_attn_out_proj', '1_model_transformer_resblocks_31_attn_q_proj', '1_model_transformer_resblocks_31_attn_v_proj', '1_model_transformer_resblocks_3_mlp_c_fc', '1_model_transformer_resblocks_3_mlp_c_proj', '1_model_transformer_resblocks_3_attn_k_proj', '1_model_transformer_resblocks_3_attn_out_proj', '1_model_transformer_resblocks_3_attn_q_proj', '1_model_transformer_resblocks_3_attn_v_proj', '1_model_transformer_resblocks_4_mlp_c_fc', '1_model_transformer_resblocks_4_mlp_c_proj', '1_model_transformer_resblocks_4_attn_k_proj', '1_model_transformer_resblocks_4_attn_out_proj', '1_model_transformer_resblocks_4_attn_q_proj', '1_model_transformer_resblocks_4_attn_v_proj', '1_model_transformer_resblocks_5_mlp_c_fc', '1_model_transformer_resblocks_5_mlp_c_proj', '1_model_transformer_resblocks_5_attn_k_proj', '1_model_transformer_resblocks_5_attn_out_proj', '1_model_transformer_resblocks_5_attn_q_proj', '1_model_transformer_resblocks_5_attn_v_proj', '1_model_transformer_resblocks_6_mlp_c_fc', '1_model_transformer_resblocks_6_mlp_c_proj', '1_model_transformer_resblocks_6_attn_k_proj', '1_model_transformer_resblocks_6_attn_out_proj', '1_model_transformer_resblocks_6_attn_q_proj', '1_model_transformer_resblocks_6_attn_v_proj', '1_model_transformer_resblocks_7_mlp_c_fc', '1_model_transformer_resblocks_7_mlp_c_proj', '1_model_transformer_resblocks_7_attn_k_proj', '1_model_transformer_resblocks_7_attn_out_proj', '1_model_transformer_resblocks_7_attn_q_proj', '1_model_transformer_resblocks_7_attn_v_proj', '1_model_transformer_resblocks_8_mlp_c_fc', '1_model_transformer_resblocks_8_mlp_c_proj', '1_model_transformer_resblocks_8_attn_k_proj', '1_model_transformer_resblocks_8_attn_out_proj', '1_model_transformer_resblocks_8_attn_q_proj', '1_model_transformer_resblocks_8_attn_v_proj', '1_model_transformer_resblocks_9_mlp_c_fc', '1_model_transformer_resblocks_9_mlp_c_proj', '1_model_transformer_resblocks_9_attn_k_proj', '1_model_transformer_resblocks_9_attn_out_proj', '1_model_transformer_resblocks_9_attn_q_proj', '1_model_transformer_resblocks_9_attn_v_proj']
2023-12-10T05:00:46.499599509+01:00 
test1:   0%|          | 0/986 [00:00<?, ?it/s]
test1:   6%|▋         | 62/986 [00:00<00:01, 619.91it/s]
test1:  18%|█▊        | 176/986 [00:00<00:00, 922.31it/s]
test1:  28%|██▊       | 279/986 [00:00<00:00, 971.02it/s]
test1:  38%|███▊      | 377/986 [00:00<00:00, 741.09it/s]
test1:  46%|████▋     | 458/986 [00:00<00:00, 753.38it/s]
test1:  55%|█████▍    | 538/986 [00:00<00:00, 760.71it/s]
test1:  63%|██████▎   | 617/986 [00:00<00:00, 763.09it/s]
test1:  71%|███████   | 696/986 [00:00<00:00, 764.38it/s]
test1:  78%|███████▊  | 774/986 [00:00<00:00, 765.92it/s]
test1:  86%|████████▋ | 852/986 [00:01<00:00, 763.63it/s]
test1:  94%|█████████▍| 929/986 [00:01<00:00, 763.02it/s]
test1: 100%|██████████| 986/986 [00:01<00:00, 765.95it/s]
2023-12-10T05:00:46.709789470+01:00 Saving...
2023-12-10T05:00:51.873971638+01:00 Done!`

It merges the lora but without the block weights. I double checked if everything is correctly set and some other loras work without issues.

when extracting from 2 loras i get this:

`2023-12-10T05:03:18.225045831+01:00 merging /workspace/stable-diffusion-webui/models/Lora/test1.safetensors: [1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0]
2023-12-10T05:03:20.518790039+01:00 dim: [64], alpha: [64.0]
2023-12-10T05:03:20.518828999+01:00 merging...
2023-12-10T05:03:21.103219494+01:00 merged model
2023-12-10T05:03:21.103252724+01:00 dim: [64], alpha: [64.0]
2023-12-10T05:03:21.103328813+01:00 merging /workspace/stable-diffusion-webui/models/Lora/TEST333_10.safetensors: [1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0]
2023-12-10T05:03:21.368088196+01:00 dim: [32], alpha: [0.800000011920929, 32]
2023-12-10T05:03:21.368110346+01:00 merging...
2023-12-10T05:03:21.505905013+01:00 merged model
2023-12-10T05:03:21.505926822+01:00 dim: [32], alpha: [0.800000011920929, 32]
2023-12-10T05:03:21.514256292+01:00 dim: [32], alpha: []
2023-12-10T05:03:21.514277442+01:00 merging...
2023-12-10T05:03:21.514612601+01:00 Traceback (most recent call last):
2023-12-10T05:03:21.514617081+01:00   File "/workspace/stable-diffusion-webui/extensions/sd-webui-supermerger/scripts/mergers/pluslora.py", line 395, in lmerge
2023-12-10T05:03:21.514619441+01:00     sd = extract_two(a,b,alpha,beta,smooth)
2023-12-10T05:03:21.514621641+01:00   File "/workspace/stable-diffusion-webui/extensions/sd-webui-supermerger/scripts/mergers/pluslora.py", line 590, in extract_two
2023-12-10T05:03:21.514623601+01:00     alpha_b = alphas_b[lora_module_name]
2023-12-10T05:03:21.514625451+01:00 KeyError: 'lora_te1_text_model_encoder_layers_0_mlp_fc1'`

It doesnt matter which lora, it seems none are working. Lora merging seems to be non functional at the moment and its also impossible to determine what the issue is because there is no real error logging. 

Hope someone can help me out!

Thanks

**Comment by silveroxides** [comment]
You should probably provide more than just the logs such as sd-webui commit, supermerger commit, the actual input you tried.

If you are still on main branch of sd-webui then you will encounter issues.
Can't really help more than that due to the lack of actual details. You can activate full debug logging in console from the webui via commandline if you believe there is an actual error.

Other than that I would recommend you read my response [here](https://github.com/hako-mikan/sd-webui-supermerger/issues/306#issuecomment-1848408144) and check the links I gave in case you input wrong amount of blocks for sdxl (just a hunch)

**Comment by hako-mikan** [comment]
If the model or LoRA which you got errors is uploaded to Civitai or huggingface tell me url.
