### ISSUE TITLE
ModuleNotFoundError: No module named 'scripts.mergers'

### ISSUE THREAD

**Issue by jason571** [hako-mikan/sd-webui-supermerger#315]
I can find it in the scripts directory.  I'm curious why there is the following error
mbwpresets_master.txt  mergers  supermerger.py

sd-webui-prompt-all-in-one background API service started successfully.
*** Error loading script: GenParamGetter.py
    Traceback (most recent call last):
      File "/mnt/p/home/flyang/stable-diffusion-webui/modules/scripts.py", line 381, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "/mnt/p/home/flyang/stable-diffusion-webui/modules/script_loading.py", line 12, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "/mnt/p/home/flyang/stable-diffusion-webui/extensions/sd-webui-supermerger/scripts/GenParamGetter.py", line 2, in <module>
        import scripts.mergers.components as components
    ModuleNotFoundError: No module named 'scripts.mergers'

---
*** Error loading script: supermerger.py
    Traceback (most recent call last):
      File "/mnt/p/home/flyang/stable-diffusion-webui/modules/scripts.py", line 381, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "/mnt/p/home/flyang/stable-diffusion-webui/modules/script_loading.py", line 12, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "/mnt/p/home/flyang/stable-diffusion-webui/extensions/sd-webui-supermerger/scripts/supermerger.py", line 22, in <module>
        import scripts.mergers.mergers
    ModuleNotFoundError: No module named 'scripts.mergers'

---

**Comment by hako-mikan** [comment]
It seems that it has not been installed correctly. I recommend reinstalling.

**Comment by AccSrd** [comment]
I meet the same problem, for me, this is because that python import another `scripts` module in the `sys.path` instead of the `scripts` folder under `/.../stable-diffusion-webui/extensions/sd-webui-supermerger`, even if this path is the first value in `sys.path` list.
The solution is add an empty `__init__.py` file under `/.../stable-diffusion-webui/extensions/sd-webui-supermerger` to tell the python loading this first.
