### ISSUE TITLE
Copy Config not checking for existing config when overwrite is active.

### ISSUE THREAD

**Issue by silveroxides** [hako-mikan/sd-webui-supermerger#316]
This causes it to error out which seems unnecessary. Why not just check if file is same, if it is, do not copy config and continue generating since it loaded another models config for the one merger loads for generating?

Here is log:

`Traceback (most recent call last):
  File "D:\stable-diffusion-webui\system\python\lib\site-packages\gradio\routes.py", line 488, in run_predict
    output = await app.get_blocks().process_api(
  File "D:\stable-diffusion-webui\system\python\lib\site-packages\gradio\blocks.py", line 1431, in process_api
    result = await self.call_function(
  File "D:\stable-diffusion-webui\system\python\lib\site-packages\gradio\blocks.py", line 1103, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "D:\stable-diffusion-webui\system\python\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "D:\stable-diffusion-webui\system\python\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "D:\stable-diffusion-webui\system\python\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "D:\stable-diffusion-webui\system\python\lib\site-packages\gradio\utils.py", line 707, in wrapper
    response = f(*args, **kwargs)
  File "D:\stable-diffusion-webui\webui\extensions\sd-webui-supermerger\scripts\mergers\mergers.py", line 134, in smergegen
    if ("copy config" in save_sets) and ("(" not in result): extras.create_config(result.replace("Merged model saved in ",""), 0, informer(model_a), informer(model_b), informer(model_b))
  File "D:\stable-diffusion-webui\webui\modules\extras.py", line 62, in create_config
    shutil.copyfile(cfg, checkpoint_filename)
  File "shutil.py", line 234, in copyfile
shutil.SameFileError: 'D:\\stable-diffusion-webui\\webui\\models\\Stable-diffusion\\e6-laion-576-704-832-lion-e99-terminal-snr-vpred-e48-cyberrealistic_classicV17_nonPlusUltra_modded-alphaTango_sumRealmode_AbsoluteCRC_train-sborka2_NSin_Scrim13_in95_nmix2_gasmZ_best-tens.yaml' and 'D:\\stable-diffusion-webui\\webui\\models\\Stable-diffusion\\e6-laion-576-704-832-lion-e99-terminal-snr-vpred-e48-cyberrealistic_classicV17_nonPlusUltra_modded-alphaTango_sumRealmode_AbsoluteCRC_train-sborka2_NSin_Scrim13_in95_nmix2_gasmZ_best-tens.yaml' are the same file`

**Comment by hako-mikan** [comment]
Fixed.
