### ISSUE TITLE
Can't run SM after updating a1111 to 1.7

### ISSUE THREAD

**Issue by miasik** [hako-mikan/sd-webui-supermerger#317]
SM version: [f2be9fa8](https://github.com/hako-mikan/sd-webui-supermerger/commit/f2be9fa878fa0c5ee8f6e1beac64e592f088520f)
I see two blocks of related messages in my starting log:
`*** Error executing callback ui_tabs_callback for E:\SD\automatic1111\extensions\sd-webui-supermerger\scripts\supermerger.py
    Traceback (most recent call last):
      File "E:\SD\automatic1111\modules\script_callbacks.py", line 166, in ui_tabs_callback
        res += c.callback() or []
      File "E:\SD\automatic1111\extensions\sd-webui-supermerger\scripts\supermerger.py", line 265, in on_ui_tabs
        xyzpresets = gr.Dropdown(label="Preset name",allow_custom_value=True,choices=get_xyzpreset_keylist(),scale=10)
      File "E:\SD\automatic1111\extensions\sd-webui-supermerger\scripts\supermerger.py", line 954, in get_xyzpreset_keylist
        keys_list = list(get_xyzpreset_data())
      File "E:\SD\automatic1111\extensions\sd-webui-supermerger\scripts\supermerger.py", line 947, in get_xyzpreset_data
        return json.load(file)
      File "C:\Users\miasik\AppData\Local\Programs\Python\Python310\lib\json\__init__.py", line 293, in load
        return loads(fp.read(),
      File "C:\Users\miasik\AppData\Local\Programs\Python\Python310\lib\json\__init__.py", line 346, in loads
        return _default_decoder.decode(s)
      File "C:\Users\miasik\AppData\Local\Programs\Python\Python310\lib\json\decoder.py", line 337, in decode
        obj, end = self.raw_decode(s, idx=_w(s, 0).end())
      File "C:\Users\miasik\AppData\Local\Programs\Python\Python310\lib\json\decoder.py", line 355, in raw_decode
        raise JSONDecodeError("Expecting value", s, err.value) from None
    json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)`

`*** Error executing callback app_started_callback for E:\SD\automatic1111\extensions\sd-webui-supermerger\scripts\GenParamGetter.py
    Traceback (most recent call last):
      File "E:\SD\automatic1111\modules\script_callbacks.py", line 139, in app_started_callback
        c.callback(demo, app)
      File "E:\SD\automatic1111\extensions\sd-webui-supermerger\scripts\GenParamGetter.py", line 90, in get_params_components
        inputs=[*components.msettings,components.esettings1,*components.genparams,*components.hiresfix,*components.lucks,components.currentmodel,components.dfalse,*components.txt2img_params],
    TypeError: Value after * must be an iterable, not NoneType`

**Comment by groinge** [comment]
Your xyzpresets.json is likely completely blank, causing an error when loaded. Deleting it will fix the issue.

**Comment by miasik** [comment]
@groinge 
it helped.
Thank you!

**Comment by CyberLykan** [comment]
@groinge I deleted my xyzpresets.json and it's still empty when I restart Stable Diffusion.

**Comment by CyberLykan** [comment]
> > @groinge I deleted my xyzpresets.json and it's still empty when I restart Stable Diffusion.
> 
> Put "{}" (No quotes) in it.

Actually, I don't think xyzpresets.json is the issue anymore. Instead, I have this.

```
*** Error executing callback ui_tabs_callback for D:\My Stuff\Extra Stuff\stable-diffusion-webui\extensions\sd-webui-supermerger\scripts\supermerger.py
    Traceback (most recent call last):
      File "D:\My Stuff\Extra Stuff\stable-diffusion-webui\modules\script_callbacks.py", line 166, in ui_tabs_callback
        res += c.callback() or []
      File "D:\My Stuff\Extra Stuff\stable-diffusion-webui\extensions\sd-webui-supermerger\scripts\supermerger.py", line 406, in on_ui_tabs
        mgallery, mgeninfo, mhtmlinfo, mhtmllog = create_output_panel("txt2img", opts.outdir_txt2img_samples)
    TypeError: cannot unpack non-iterable OutputPanel object

---
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
*** Error executing callback app_started_callback for D:\My Stuff\Extra Stuff\stable-diffusion-webui\extensions\sd-webui-supermerger\scripts\GenParamGetter.py
    Traceback (most recent call last):
      File "D:\My Stuff\Extra Stuff\stable-diffusion-webui\modules\script_callbacks.py", line 139, in app_started_callback
        c.callback(demo, app)
      File "D:\My Stuff\Extra Stuff\stable-diffusion-webui\extensions\sd-webui-supermerger\scripts\GenParamGetter.py", line 90, in get_params_components
        inputs=[*components.msettings,components.esettings1,*components.genparams,*components.hiresfix,*components.lucks,components.currentmodel,components.dfalse,*components.txt2img_params],
    TypeError: Value after * must be an iterable, not NoneType

---
```
