### ISSUE TITLE
mergehistory.csv field size limit

### ISSUE THREAD

**Issue by silveroxides** [hako-mikan/sd-webui-supermerger#319]
Encountering this when it is attempting to save:

```
Traceback (most recent call last):
  File "D:\stable-diffusion-webui\system\python\lib\site-packages\gradio\routes.py", line 488, in run_predict
    output = await app.get_blocks().process_api(
  File "D:\stable-diffusion-webui\system\python\lib\site-packages\gradio\blocks.py", line 1431, in process_api
    result = await self.call_function(
  File "D:\stable-diffusion-webui\system\python\lib\site-packages\gradio\blocks.py", line 1103, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "D:\stable-diffusion-webui\system\python\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "D:\stable-diffusion-webui\system\python\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "D:\stable-diffusion-webui\system\python\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "D:\stable-diffusion-webui\system\python\lib\site-packages\gradio\utils.py", line 707, in wrapper
    response = f(*args, **kwargs)
  File "D:\stable-diffusion-webui\webui\extensions\sd-webui-supermerger\scripts\mergers\mergers.py", line 108, in smergegen
    result,currentmodel,modelid,theta_0,metadata = smerge(
  File "D:\stable-diffusion-webui\webui\extensions\sd-webui-supermerger\scripts\mergers\mergers.py", line 539, in smerge
    modelid = rwmergelog(currentmodel,mergedmodel)
  File "D:\stable-diffusion-webui\webui\extensions\sd-webui-supermerger\scripts\mergers\mergers.py", line 947, in rwmergelog
    #         mlist = [raw for raw in reader]
  File "D:\stable-diffusion-webui\webui\extensions\sd-webui-supermerger\scripts\mergers\mergers.py", line 947, in <listcomp>
    #         mlist = [raw for raw in reader]
_csv.Error: field larger than field limit (131072)

**Comment by hako-mikan** [comment]
Fixed.
