### ISSUE TITLE
Error merge locon to checkpoint

### ISSUE THREAD

**Issue by RefirmSaky** [hako-mikan/sd-webui-supermerger#32]
I have updated to the latest version, but I get the following error when fusing locon, which I guess is due to incompatibility with locon_kohya

```
Traceback (most recent call last):
  File "D:\DeepLearning\novelai-webui-aki-v3\py310\lib\site-packages\gradio\routes.py", line 337, in run_predict
    output = await app.get_blocks().process_api(
  File "D:\DeepLearning\novelai-webui-aki-v3\py310\lib\site-packages\gradio\blocks.py", line 1015, in process_api
    result = await self.call_function(
  File "D:\DeepLearning\novelai-webui-aki-v3\py310\lib\site-packages\gradio\blocks.py", line 833, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "D:\DeepLearning\novelai-webui-aki-v3\py310\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "D:\DeepLearning\novelai-webui-aki-v3\py310\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "D:\DeepLearning\novelai-webui-aki-v3\py310\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "D:\DeepLearning\novelai-webui-aki-v3\extensions\sd-webui-supermerger\scripts\mergers\pluslora.py", line 308, in pluslora
    weight = weight  + ratio * (up_weight.squeeze(3).squeeze(2) @ down_weight.squeeze(3).squeeze(2)
RuntimeError: mat1 and mat2 shapes cannot be multiplied (3840x3 and 4x320)
```

**Comment by Ev-Bro** [comment]
I am getting  a similar result when I try to merge 2 checkpoints:


Traceback (most recent call last):
  File "C:\Users\user1\stable-diffusion-webui\venv\lib\site-packages\gradio\routes.py", line 337, in run_predict
    output = await app.get_blocks().process_api(
  File "C:\Users\user1\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1015, in process_api
    result = await self.call_function(
  File "C:\Users\user1\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 833, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "C:\Users\user1\stable-diffusion-webui\venv\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "C:\Users\user1\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "C:\Users\user1\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "C:\Users\user1\stable-diffusion-webui\extensions\sd-webui-supermerger\scripts\mergers\mergers.py", line 51, in smergegen
    result,currentmodel,modelid,theta_0 = smerge(weights_a,weights_b,model_a,model_b,model_c,base_alpha,base_beta,mode,useblocks,custom_name,save_sets,id_sets,wpresets,deep,deepprint=deepprint)
  File "C:\Users\user1\stable-diffusion-webui\extensions\sd-webui-supermerger\scripts\mergers\mergers.py", line 255, in smerge
    theta_0[key] = (1 - current_alpha) * theta_0[key] + current_alpha * theta_1[key]
RuntimeError: The size of tensor a (4) must match the size of tensor b (9) at non-singleton dimension 1
