### ISSUE TITLE
Doesn't work on latest dev of auto1111.

### ISSUE THREAD

**Issue by Panchovix** [hako-mikan/sd-webui-supermerger#322]
Hi there, since some dev updates, and up to the https://github.com/AUTOMATIC1111/stable-diffusion-webui/commit/6869d95890849c9b209bb66774539bfdf870df2c commit, the extension fails to load.

The error in the middle when launching the webui:

```
*** Error executing callback ui_tabs_callback for G:\Stable difussion\stable-diffusion-webui\extensions\sd-webui-supermerger\scripts\supermerger.py
    Traceback (most recent call last):
      File "G:\Stable difussion\stable-diffusion-webui\modules\script_callbacks.py", line 169, in ui_tabs_callback
        res += c.callback() or []
               ^^^^^^^^^^^^
      File "G:\Stable difussion\stable-diffusion-webui\extensions\sd-webui-supermerger\scripts\supermerger.py", line 406, in on_ui_tabs
        mgallery, mgeninfo, mhtmlinfo, mhtmllog = create_output_panel("txt2img", opts.outdir_txt2img_samples)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    TypeError: cannot unpack non-iterable OutputPanel object

---
```

and at the end

```
*** Error executing callback app_started_callback for G:\Stable difussion\stable-diffusion-webui\extensions\sd-webui-supermerger\scripts\GenParamGetter.py
    Traceback (most recent call last):
      File "G:\Stable difussion\stable-diffusion-webui\modules\script_callbacks.py", line 142, in app_started_callback
        c.callback(demo, app)
      File "G:\Stable difussion\stable-diffusion-webui\extensions\sd-webui-supermerger\scripts\GenParamGetter.py", line 90, in get_params_components
        inputs=[*components.msettings,components.esettings1,*components.genparams,*components.hiresfix,*components.lucks,components.currentmodel,components.dfalse,*components.txt2img_params],
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    TypeError: Value after * must be an iterable, not NoneType

---
```

**Comment by hako-mikan** [comment]
Thanks @Janca
Fixed.
