### ISSUE TITLE
After the update, an error occurred, and it does not appear in a1111.

### ISSUE THREAD

**Issue by Neytiri7** [hako-mikan/sd-webui-supermerger#327]
To create a public link, set `share=True` in `launch()`.
*** Error executing callback app_started_callback for O:\AI\SynologyDrive\stable-diffusion-webui\extensions\sd-webui-supermerger\scripts\GenParamGetter.py
    Traceback (most recent call last):
      File "O:\AI\SynologyDrive\stable-diffusion-webui\modules\script_callbacks.py", line 139, in app_started_callback
        c.callback(demo, app)
      File "O:\AI\SynologyDrive\stable-diffusion-webui\extensions\sd-webui-supermerger\scripts\GenParamGetter.py", line 90, in get_params_components
        inputs=[*components.msettings,components.esettings1,*components.genparams,*components.hiresfix,*components.lucks,components.currentmodel,components.dfalse,*components.txt2img_params],
    TypeError: Value after * must be an iterable, not NoneType

**Comment by hako-mikan** [comment]
Fixed.
