### ISSUE TITLE
Make LoRA from two models doesn't work: "Error(s) in loading state_dict for CLIPTextModel"

### ISSUE THREAD

**Issue by Muxropendiy** [hako-mikan/sd-webui-supermerger#329]
Maybe this is a duplicate, I see several similar issues that are marked as fixed and closed. But this feature is still not working for me. When I try to create a LoRA from the difference of two models, I get this error:
```
 INFO Select: model="SD/v1-5-pruned-emaonly" 
Loading model: /home/***/SD.Next/models/Stable-diffusion/SD/v1-5-pruned-emaonly.safetensors ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 0.0/4.3 GB -:--:--
 INFO Setting Torch parameters: device=cuda dtype=torch.float16 vae=torch.float16 unet=torch.float16 context=no_grad fp16=True bf16=False 
 INFO LDM: LatentDiffusion: mode=eps 
 INFO LDM: DiffusionWrapper params=859.52M 
 INFO Autodetect: model="Stable Diffusion" class=StableDiffusionPipeline file="/home/***/SD.Next/models/Stable-diffusion/SD/v1-5-pruned-emaonly.safetensors" size=4068MB 
Calculating hash: /home/***/SD.Next/models/Stable-diffusion/SD/v1-5-pruned-emaonly.safetensors ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.3/4.3 GB 0:00:00
 INFO Cross-attention: optimization=Split attention options=[] 
 INFO Model loaded in 9.07 { create=5.23 apply=0.47 vae=2.82 move=0.47 } 
 INFO Model load finished: {'ram': {'used': 14.2, 'total': 31.25}, 'gpu': {'used': 2.23, 'total': 7.98}, 'retries': 0, 'oom': 0} cached=0 
make LoRA start
Detected model type: SDXL: False, SD2.X: False, SD1.X: True
loading original SD model : /home/***/SD.Next/models/Stable-diffusion/SD/v1-5-pruned-emaonly.safetensors
UNet2DConditionModel: 64, 8, 768, False, False
loading u-net: <All keys matched successfully>
Traceback (most recent call last):
 File "/home/***/SD.Next/venv/lib64/python3.10/site-packages/gradio/queueing.py", line 388, in call_prediction
 output = await route_utils.call_process_api(
 File "/home/***/SD.Next/venv/lib64/python3.10/site-packages/gradio/route_utils.py", line 219, in call_process_api
 output = await app.get_blocks().process_api(
 File "/home/***/SD.Next/venv/lib64/python3.10/site-packages/gradio/blocks.py", line 1437, in process_api
 result = await self.call_function(
 File "/home/***/SD.Next/venv/lib64/python3.10/site-packages/gradio/blocks.py", line 1109, in call_function
 prediction = await anyio.to_thread.run_sync(
 File "/home/***/SD.Next/venv/lib64/python3.10/site-packages/anyio/to_thread.py", line 56, in run_sync
 return await get_async_backend().run_sync_in_worker_thread(
 File "/home/***/SD.Next/venv/lib64/python3.10/site-packages/anyio/_backends/_asyncio.py", line 2134, in run_sync_in_worker_thread
 return await future
 File "/home/***/SD.Next/venv/lib64/python3.10/site-packages/anyio/_backends/_asyncio.py", line 851, in run
 result = context.run(func, *args)
 File "/home/***/SD.Next/venv/lib64/python3.10/site-packages/gradio/utils.py", line 641, in wrapper
 response = f(*args, **kwargs)
 File "/home/***/SD.Next/extensions/sd-webui-supermerger/scripts/mergers/pluslora.py", line 293, in makelora
 result = ext.svd(args)
 File "/home/***/SD.Next/extensions/sd-webui-supermerger/scripts/kohyas/extract_lora_from_models.py", line 52, in svd
 text_encoder_o, _, unet_o = model_util.load_models_from_stable_diffusion_checkpoint(args.v2, args.model_org)
 File "/home/***/SD.Next/extensions/sd-webui-supermerger/scripts/kohyas/model_util.py", line 1066, in load_models_from_stable_diffusion_checkpoint
 info = text_model.load_state_dict(converted_text_encoder_checkpoint)
 File "/home/***/SD.Next/venv/lib64/python3.10/site-packages/torch/nn/modules/module.py", line 2153, in load_state_dict
 raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for CLIPTextModel:
 Unexpected key(s) in state_dict: "text_model.embeddings.position_ids". 
```
This error occurs with any models, but in this case i am using original SD-1.5 and SD-1.5-inpainting
I run SD.Next with PyTorch nightly and AMD ROCm 5.7, but i think exact versions doesn't matter, because it doesn't work since forever.

**Comment by nCoderGit** [comment]
_**Disclaimer:**
I know next to nothing about all this stuff or transformers in general, 
so I hope someone who does could join in on this._ 😄

Found this in another repo, where it is a `transformers` version issue: https://github.com/explosion/spaCy/issues/12982
___
I suppose you could just get rid of the `Unexpected key(s)` exception and continue the calculation up to extracting LoRA weights by changing this...
https://github.com/hako-mikan/sd-webui-supermerger/blob/b9229d754fb7911cd29d1eaa7e5fde016286b5fd/scripts/kohyas/model_util.py#L1066
to `info = text_model.load_state_dict(converted_text_encoder_checkpoint, strict=False)` .
___
Here's the output with `strict=False`:
```
make LoRA start
Detected model type: SDXL: False, SD2.X: False, SD1.X: True
loading original SD model : C:\StableDiffusion\SDNext\models\Stable-diffusion\Checkpoint_Original.fp16.safetensors
UNet2DConditionModel: 64, 8, 768, False, False
loading u-net: <All keys matched successfully>
loading text encoder: _IncompatibleKeys(missing_keys=[], unexpected_keys=['text_model.embeddings.position_ids'])
loading tuned SD model : C:\StableDiffusion\SDNext\models\Stable-diffusion\Checkpoint_Tuned.fp16.safetensors
UNet2DConditionModel: 64, 8, 768, False, False
loading u-net: <All keys matched successfully>
loading text encoder: _IncompatibleKeys(missing_keys=[], unexpected_keys=['text_model.embeddings.position_ids'])
create LoRA network. base dim (rank): 128, alpha: 128
neuron dropout: p=None, rank dropout: p=None, module dropout: p=None
create LoRA for Text Encoder:
create LoRA for Text Encoder: 72 modules.
create LoRA for U-Net: 192 modules.
create LoRA network. base dim (rank): 128, alpha: 128
neuron dropout: p=None, rank dropout: p=None, module dropout: p=None
create LoRA for Text Encoder:
create LoRA for Text Encoder: 72 modules.
create LoRA for U-Net: 192 modules.
Text encoder is same. Extract U-Net only.
calculating by svd
100%|████████████████████████████████████████████████████████████████████████████████████████████████████| 192/192 [00:22<00:00,  8.70it/s]
create LoRA network from weights
create LoRA for Text Encoder:
create LoRA for Text Encoder: 0 modules.
create LoRA for U-Net: 192 modules.
enable LoRA for text encoder
enable LoRA for U-Net
Loading extracted LoRA weights: <All keys matched successfully>
Traceback (most recent call last):
  File "C:\StableDiffusion\SDNext\venv\lib\site-packages\gradio\queueing.py", line 388, in call_prediction
    output = await route_utils.call_process_api(
  File "C:\StableDiffusion\SDNext\venv\lib\site-packages\gradio\route_utils.py", line 219, in call_process_api
    output = await app.get_blocks().process_api(
  File "C:\StableDiffusion\SDNext\venv\lib\site-packages\gradio\blocks.py", line 1437, in process_api
    result = await self.call_function(
  File "C:\StableDiffusion\SDNext\venv\lib\site-packages\gradio\blocks.py", line 1109, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "C:\StableDiffusion\SDNext\venv\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "C:\StableDiffusion\SDNext\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "C:\StableDiffusion\SDNext\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "C:\StableDiffusion\SDNext\venv\lib\site-packages\gradio\utils.py", line 641, in wrapper
    response = f(*args, **kwargs)
  File "C:\StableDiffusion\SDNext\extensions\sd-webui-supermerger\scripts\mergers\pluslora.py", line 302, in makelora
    result = ext.svd(args)
  File "C:\StableDiffusion\SDNext\extensions\sd-webui-supermerger\scripts\kohyas\extract_lora_from_models.py", line 206, in svd
    lora_network_save.save_weights(args.save_to, save_dtype, metadata)
  File "C:\StableDiffusion\SDNext\extensions\sd-webui-supermerger\scripts\kohyas\lora.py", line 1091, in save_weights
    from scripts.kohyas import train_util
  File "C:\StableDiffusion\SDNext\extensions\sd-webui-supermerger\scripts\kohyas\train_util.py", line 1257, in <module>
    def replace_unet_modules(unet: diffusers.models.unet_2d_condition.UNet2DConditionModel, mem_eff_attn, xformers):
  File "C:\StableDiffusion\SDNext\venv\lib\site-packages\diffusers\utils\import_utils.py", line 697, in __getattr__
    raise AttributeError(f"module {self.__name__} has no attribute {name}")
AttributeError: module diffusers.models has no attribute unet_2d_condition
```
___
As you can see, going with `strict=False` will still eventually fail on `replace_unet_modules`, though. 
And I don't know it this is a seperate issue or connected to the transformers version...

**Comment by nCoderGit** [comment]
Okay, got it fixed. 😊
Took some code from kohya's latest [sd-scripts](https://github.com/kohya-ss/sd-scripts) rep for the new transformers versions.

Merge request incoming

**Comment by hako-mikan** [comment]
Thanks @nCoderGit 
Fixed.

**Comment by xjdeng** [comment]
Still not working for me in the latest update:

```
Traceback (most recent call last):
  File "C:\Users\xjd00\miniconda3\envs\pytorch2\lib\site-packages\gradio\routes.py", line 488, in run_predict
    output = await app.get_blocks().process_api(
  File "C:\Users\xjd00\miniconda3\envs\pytorch2\lib\site-packages\gradio\blocks.py", line 1431, in process_api
    result = await self.call_function(
  File "C:\Users\xjd00\miniconda3\envs\pytorch2\lib\site-packages\gradio\blocks.py", line 1103, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "C:\Users\xjd00\miniconda3\envs\pytorch2\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "C:\Users\xjd00\miniconda3\envs\pytorch2\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "C:\Users\xjd00\miniconda3\envs\pytorch2\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "C:\Users\xjd00\miniconda3\envs\pytorch2\lib\site-packages\gradio\utils.py", line 707, in wrapper
    response = f(*args, **kwargs)
  File "Z:\stable-diffusion-webui\extensions\sd-webui-supermerger\scripts\mergers\pluslora.py", line 302, in makelora
    result = ext.svd(args)
  File "Z:\stable-diffusion-webui\extensions\sd-webui-supermerger\scripts\kohyas\extract_lora_from_models.py", line 52, in svd
    text_encoder_o, _, unet_o = model_util.load_models_from_stable_diffusion_checkpoint(args.v2, args.model_org)
  File "Z:\stable-diffusion-webui\extensions\sd-webui-supermerger\scripts\kohyas\model_util.py", line 1066, in load_models_from_stable_diffusion_checkpoint
    info = text_model.load_state_dict(converted_text_encoder_checkpoint)
  File "C:\Users\xjd00\miniconda3\envs\pytorch2\lib\site-packages\torch\nn\modules\module.py", line 2152, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for CLIPTextModel:
        Missing key(s) in state_dict: "text_model.embeddings.position_ids".
```

**Comment by nCoderGit** [comment]
Are you running A1111 or SD.Next? Which version?

**Comment by xjdeng** [comment]
Right now, the latest commit of A1111 on their main branch.

**Comment by nCoderGit** [comment]
Okay, I can reproduce this on A1111.

For reference:
- Latest version of A1111 (v1.8.0) still uses the outdated transformers 4.30.2
- Latest version of SD.Next (hash:bc4b633e 2024-03-07) uses transformers 4.38.1

To make it short: Transformers <4.31 expected position_ids, Transformers >=4.31 treats position_ids as unexpected.

I would need to do a few more tests on both A1111 and SD.Next, but so far it appears to work with strict=False
(in model_util.py, change line 1066: `info = text_model.load_state_dict(converted_text_encoder_checkpoint, strict=False)` [*1] ).

There will be a few warnings in A1111 while SuperMerger creates the LoRA, but it's being saved and the LoRA appears to work just fine.

[*1] see https://github.com/huggingface/transformers/issues/25330
___

What do you think, @hako-mikan ?
`strict=False` and just ignore the warnings? Or do you know a better solution?

**Comment by hako-mikan** [comment]
@nCoderGit, thank you for analyzing the issue. F
or now, I will use the try, except syntax to set strict=false only when an error occurs.
