### ISSUE TITLE
Pinpoint blocks for XY plot broken for SDXL

### ISSUE THREAD

**Issue by AvrikV** [hako-mikan/sd-webui-supermerger#338]
This happens whenever you try to do an XY plot and pinpoint blocks above IN08 with SDXL merging. I think the issue is that even when you select SDXL, it still uses the labels from 1.5. For example, M00 = IN09, OUT00 = IN10, OUT01 = IN11, etc.

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/gradio/routes.py", line 488, in run_predict
    output = await app.get_blocks().process_api(
  File "/usr/local/lib/python3.10/dist-packages/gradio/blocks.py", line 1431, in process_api
    result = await self.call_function(
  File "/usr/local/lib/python3.10/dist-packages/gradio/blocks.py", line 1103, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/usr/local/lib/python3.10/dist-packages/anyio/to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/usr/local/lib/python3.10/dist-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "/usr/local/lib/python3.10/dist-packages/anyio/_backends/_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "/usr/local/lib/python3.10/dist-packages/gradio/utils.py", line 707, in wrapper
    response = f(*args, **kwargs)
  File "/notebooks/stable-diffusion-webui/extensions/sd-webui-supermerger/scripts/mergers/xyplot.py", line 78, in numanager
    result,currentmodel,xyimage,a,b,c= sgenxyplot(*allsets)
  File "/notebooks/stable-diffusion-webui/extensions/sd-webui-supermerger/scripts/mergers/xyplot.py", line 409, in sgenxyplot
    weights_a_in = weightsdealer(xyzv,xyzt,weights_a,"alpha")
  File "/notebooks/stable-diffusion-webui/extensions/sd-webui-supermerger/scripts/mergers/xyplot.py", line 321, in weightsdealer
    if f:weights_t[i]=wa
IndexError: list assignment index out of range
```

**Comment by Temix0** [comment]
I had the same issue. You need to treat it as sd1.5 blocks. 
I09=M00, I10=OUT00, etc. 

Now I'm trying to figure out how to do similar to the random function.

**Comment by hako-mikan** [comment]
Fixed, thanks!
