### ISSUE TITLE
argument of type 'NoneType' is not iterable

### ISSUE THREAD

**Issue by chriperseo** [hako-mikan/sd-webui-supermerger#343]
change demension to  16
merging G:\AI\SD-FORGE-26-02-2024\webui_forge_cu121_torch21\webui\models\Lora\Zyv45ac.safetensors: [0.8, 0.8, 0.8, 0.8, 0.8, 0.8, 0.8, 0.8, 0.8, 0.8, 0.8, 0.8, 0.8, 0.8, 0.8, 0.8, 0.8, 0.8, 0.8, 0.8, 0.8, 0.8, 0.8, 0.8, 0.8, 0.8]
  0%|▏                                                                                                                                                                  | 1/792 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "G:\AI\SD-FORGE-26-02-2024\webui_forge_cu121_torch21\webui\extensions\sd-webui-supermerger\scripts\mergers\pluslora.py", line 390, in lmerge
    sd = merge_lora_models_dim(ln, lr, dim,settings,device,calc_precision)
  File "G:\AI\SD-FORGE-26-02-2024\webui_forge_cu121_torch21\webui\extensions\sd-webui-supermerger\scripts\mergers\pluslora.py", line 515, in merge_lora_models_dim
    ratio = ratios[blockfromkey(key, LBLCOKS26,isv2)]
  File "G:\AI\SD-FORGE-26-02-2024\webui_forge_cu121_torch21\webui\extensions\sd-webui-supermerger\scripts\mergers\pluslora.py", line 1082, in blockfromkey
    if "lora_unet" in fullkey:
TypeError: argument of type 'NoneType' is not iterable

Inable to merge 2 Lora files, they can be merged when using the a1111 default ui with an older version extension, but after updating to the latest extension, i tried with a1111 and sdforge. The merging dosnt work. 

I am new to this, i may not be very technical, so kindly treat me as a layman and try to help me or investigate the bug.
thanks

**Comment by ResidentChief** [comment]
Same issue as #334

**Comment by chriperseo** [comment]
Is there a solution yet ?

**Comment by hako-mikan** [comment]
Same issue as https://github.com/hako-mikan/sd-webui-supermerger/issues/334 and fixed.
