### ISSUE TITLE
supermerger won't load！

### ISSUE THREAD

**Issue by design61** [hako-mikan/sd-webui-supermerger#354]
`*** Error loading script: GenParamGetter.py
    Traceback (most recent call last):
      File "E:\StableDiffusion\WebUI\modules\scripts.py", line 527, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "E:\StableDiffusion\WebUI\modules\script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "E:\StableDiffusion\WebUI\extensions\sd-webui-supermerger\scripts\GenParamGetter.py", line 5, in <module>
        from scripts.mergers.pluslora import frompromptf
      File "E:\StableDiffusion\WebUI\extensions\sd-webui-supermerger\scripts\mergers\pluslora.py", line 19, in <module>
        from scripts.kohyas import extract_lora_from_models as ext
      File "E:\StableDiffusion\WebUI\extensions\sd-webui-supermerger\scripts\kohyas\extract_lora_from_models.py", line 12, in <module>
        from scripts.kohyas import sai_model_spec,model_util,sdxl_model_util,lora
      File "E:\StableDiffusion\WebUI\extensions\sd-webui-supermerger\scripts\kohyas\sdxl_model_util.py", line 7, in <module>
        from diffusers import AutoencoderKL, EulerDiscreteScheduler, UNet2DConditionModel
    ImportError: cannot import name 'EulerDiscreteScheduler' from 'diffusers' (E:\StableDiffusion\WebUI\py310\lib\site-packages\diffusers\__init__.py)

---
*** Error loading script: supermerger.py
    Traceback (most recent call last):
      File "E:\StableDiffusion\WebUI\modules\scripts.py", line 527, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "E:\StableDiffusion\WebUI\modules\script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "E:\StableDiffusion\WebUI\extensions\sd-webui-supermerger\scripts\supermerger.py", line 23, in <module>
        import scripts.mergers.pluslora
      File "E:\StableDiffusion\WebUI\extensions\sd-webui-supermerger\scripts\mergers\pluslora.py", line 19, in <module>
        from scripts.kohyas import extract_lora_from_models as ext
      File "E:\StableDiffusion\WebUI\extensions\sd-webui-supermerger\scripts\kohyas\extract_lora_from_models.py", line 12, in <module>
        from scripts.kohyas import sai_model_spec,model_util,sdxl_model_util,lora
      File "E:\StableDiffusion\WebUI\extensions\sd-webui-supermerger\scripts\kohyas\sdxl_model_util.py", line 7, in <module>
        from diffusers import AutoencoderKL, EulerDiscreteScheduler, UNet2DConditionModel
    ImportError: cannot import name 'EulerDiscreteScheduler' from 'diffusers' (E:\StableDiffusion\WebUI\py310\lib\site-packages\diffusers\__init__.py)`

 •  python: 3.10.7  •  torch: 2.2.0+cu121  •  xformers: 0.0.24  •  gradio: 3.41.2

**Comment by nCoderGit** [comment]
Can't repro on the latest version for both A1111 and SD.Next.

Are you running A1111 or SD.Next? Which version?

**Comment by celluuuu** [comment]
> Can't repro on the latest version for both A1111 and SD.Next.
> 
> Are you running A1111 or SD.Next? Which version?

have you found a solution already? I'm having the same issue and can't see the Supermerger tab

**Comment by hako-mikan** [comment]
The cause of this error is version of diffusers.
Check your version.

**Comment by hako-mikan** [comment]
May be fixed.
