### ISSUE TITLE
supermerger can't load in webui 1.8 (pytorch 2.2.1+cu121+xformers 0.0.25)

### ISSUE THREAD

**Issue by Array-Cats** [hako-mikan/sd-webui-supermerger#358]
error info

```
ControlNet preprocessor location: W:\stable-diffusion-webui\extensions\sd-webui-controlnet\annotator\downloads
2024-03-18 21:01:10,375 - ControlNet - INFO - ControlNet v1.1.441
2024-03-18 21:01:11,130 - ControlNet - INFO - ControlNet v1.1.441
sd-webui-prompt-all-in-one background API service started successfully.
*** Error loading script: GenParamGetter.py
    Traceback (most recent call last):
      File "W:\stable-diffusion-webui\modules\scripts.py", line 527, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "W:\stable-diffusion-webui\modules\script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "W:\stable-diffusion-webui\extensions\sd-webui-supermerger\scripts\GenParamGetter.py", line 5, in <module>
        from scripts.mergers.pluslora import frompromptf
      File "W:\stable-diffusion-webui\extensions\sd-webui-supermerger\scripts\mergers\pluslora.py", line 19, in <module>
        from scripts.kohyas import extract_lora_from_models as ext
      File "W:\stable-diffusion-webui\extensions\sd-webui-supermerger\scripts\kohyas\extract_lora_from_models.py", line 12, in <module>
        from scripts.kohyas import sai_model_spec,model_util,sdxl_model_util,lora
      File "W:\stable-diffusion-webui\extensions\sd-webui-supermerger\scripts\kohyas\model_util.py", line 14, in <module>
        import diffusers
      File "W:\stable-diffusion-webui\venv\lib\site-packages\diffusers\__init__.py", line 5, in <module>
        from .utils import (
      File "W:\stable-diffusion-webui\venv\lib\site-packages\diffusers\utils\__init__.py", line 21, in <module>
        from .constants import (
      File "W:\stable-diffusion-webui\venv\lib\site-packages\diffusers\utils\constants.py", line 17, in <module>
        from huggingface_hub.constants import HF_HOME
    ImportError: cannot import name 'HF_HOME' from 'huggingface_hub.constants' (W:\stable-diffusion-webui\venv\lib\site-packages\huggingface_hub\constants.py)

---
*** Error loading script: supermerger.py
    Traceback (most recent call last):
      File "W:\stable-diffusion-webui\modules\scripts.py", line 527, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "W:\stable-diffusion-webui\modules\script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "W:\stable-diffusion-webui\extensions\sd-webui-supermerger\scripts\supermerger.py", line 23, in <module>
        import scripts.mergers.pluslora
      File "W:\stable-diffusion-webui\extensions\sd-webui-supermerger\scripts\mergers\pluslora.py", line 19, in <module>
        from scripts.kohyas import extract_lora_from_models as ext
      File "W:\stable-diffusion-webui\extensions\sd-webui-supermerger\scripts\kohyas\extract_lora_from_models.py", line 12, in <module>
        from scripts.kohyas import sai_model_spec,model_util,sdxl_model_util,lora
      File "W:\stable-diffusion-webui\extensions\sd-webui-supermerger\scripts\kohyas\model_util.py", line 14, in <module>
        import diffusers
      File "W:\stable-diffusion-webui\venv\lib\site-packages\diffusers\__init__.py", line 5, in <module>
        from .utils import (
      File "W:\stable-diffusion-webui\venv\lib\site-packages\diffusers\utils\__init__.py", line 21, in <module>
        from .constants import (
      File "W:\stable-diffusion-webui\venv\lib\site-packages\diffusers\utils\constants.py", line 17, in <module>
        from huggingface_hub.constants import HF_HOME
    ImportError: cannot import name 'HF_HOME' from 'huggingface_hub.constants' (W:\stable-diffusion-webui\venv\lib\site-packages\huggingface_hub\constants.py)

---
== WD14 tagger /gpu:0, uname_result(system='Windows', node='FlyingCats-PC', release='10', version='10.0.22621', machine='AMD64') ==
```

**Comment by celluuuu** [comment]
have you found a solution already? I'm having the same issue and can't see the Supermerger tab @Array-Cats

**Comment by Array-Cats** [comment]
> have you found a solution already? I'm having the same issue and can't see the Supermerger tab @Array-Cats

No, maybe use old pytorch +xformers (like pytorch 2.2.0 + xformers 0.0.24) can running. I found this problem was after update pytorch

**Comment by Array-Cats** [comment]
> have you found a solution already? I'm having the same issue and can't see the Supermerger tab @Array-Cats

I find a solution, update huggingface_hub to new version(I update huggingface_hub to 0.22.2 ), because environment variables name was changed in diffusers, but old huggingface_hub use old name

**Comment by Array-Cats** [comment]
> have you found a solution already? I'm having the same issue and can't see the Supermerger tab @Array-Cats

I find a solution, update huggingface_hub to new version(I update huggingface_hub to 0.22.2 ), because environment variables name was changed in diffusers, but old huggingface_hub use old name
