### ISSUE TITLE
error when making inpainting sdxl model by add difference

### ISSUE THREAD

**Issue by zhuliyi0** [hako-mikan/sd-webui-supermerger#368]
Following this post but for SDXL
https://civitai.com/articles/1045/inpainting-for-any-model

and the error message:

  model A       : sdxl_sd_xl_base_1.0_inpainting_0.1
  model B       : sdxl_juggernautXL_v9Rundiffusionphoto2
  model C       : sdxl_sd_xl_base_1.0
  alpha,beta    : (1, 0.25)
  weights_alpha :
  weights_beta  :
  mode          : Add difference
  MBW           : False
  CalcMode      : normal
  Elemental     :
  Weights Seed  : 82735682
  Off   : ([], '')
  Adjust        :
Loading weights [sdxl_juggernautXL_v9Rundiffusionphoto2] from file
Loading weights [sdxl_sd_xl_base_1.0] from file
  5%|████▏                                                                         | 136/2513 [00:00<00:03, 741.40i  8%|██████▌                                                                       | 211/2513 [00:00<00:04, 512.8 11%|████████▎                                                                     | 269/2513 [00:00<00:05, 428 13%|█████████▊                                                                    | 317/2513 [00:00<00:05, 38 14%|███████████▏                                                                  | 359/2513 [00:00<00:06,  16%|████████████▎                                                                 | 397/2513 [00:01<00:06, 17%|█████████████▍                                                                | 433/2513 [00:01<00:06 19%|██████████████▌                                                               | 468/2513 [00:01<00:0 20%|███████████████▌                                                              | 502/2513 [00:01<00: 21%|████████████████▌                                                             | 535/2513 [00:01<00 23%|█████████████████▋                                                            | 568/2513 [00:01<0 27%|████████████████████▉                                                         | 673/2513 [00:0 32%|████████████████████████▋                                                     | 797/2513 [ 37%|████████████████████████████▋                                                 | 925/25 40%|███████████████████████████████                                              | 1014/ 43%|█████████████████████████████████▍                                           | 10 46%|███████████████████████████████████▎                                         |  48%|████████████████████████████████████▉                                        | 50%|██████████████████████████████████████▎                                      51%|███████████████████████████████████████▌                                    53%|████████████████████████████████████████▋                                  54%|█████████████████████████████████████████▊                                56%|██████████████████████████████████████████▊                              57%|███████████████████████████████████████████▊                            58%|████████████████████████████████████████████▊                          60%|█████████████████████████████████████████████▊                        61%|██████████████████████████████████████████████▊                      62%|███████████████████████████████████████████████▊                    63%|████████████████████████████████████████████████▊                  65%|█████████████████████████████████████████████████▋                66%|██████████████████████████████████████████████████▌              67%|███████████████████████████████████████████████████▋            68%|████████████████████████████████████████████████████▍          70%|█████████████████████████████████████████████████████▌        71%|██████████████████████████████████████████████████████▍      72%|███████████████████████████████████████████████████████▍    73%|████████████████████████████████████████████████████████▎  74%|█████████████████████████████████████████████████████████  75%|█████████████████████████████████████████████████████████  77%|█████████████████████████████████████████████████████████  78%|█████████████████████████████████████████████████████████  79%|█████████████████████████████████████████████████████████  80%|█████████████████████████████████████████████████████████  81%|█████████████████████████████████████████████████████████  83%|█████████████████████████████████████████████████████████  84%|█████████████████████████████████████████████████████████  85%|█████████████████████████████████████████████████████████  86%|█████████████████████████████████████████████████████████  87%|█████████████████████████████████████████████████████████  89%|█████████████████████████████████████████████████████████  90%|█████████████████████████████████████████████████████████  91%|█████████████████████████████████████████████████████████  92%|█████████████████████████████████████████████████████████  96%|█████████████████████████████████████████████████████████  99%|█████████████████████████████████████████████████████████ 100%|█████████████████████████████████████████████████████████ ████████████████████| 2513/2513 [00:07<00:00, 345.37it/s]
Loading weights [sdxl_sd_xl_base_1.0_inpainting_0.1] from file
Stage 1/2:   4%|██▍                                                                 | 91/2515 [00:00<00:04, 513.46it/Stage 1/2:   7%|████▉                                                              | 185/2515 [00:00<00:03, 687.12iStage 1/2:  10%|██████▊                                                            | 254/2515 [00:00<00:06, 335.5Stage 1/2:  12%|████████                                                           | 303/2515 [00:00<00:07, 300.Stage 1/2:  14%|█████████▏                                                         | 343/2515 [00:01<00:07, 29Stage 1/2:  15%|██████████                                                         | 379/2515 [00:01<00:07, 27Stage 1/2:  16%|██████████▉                                                        | 411/2515 [00:01<00:08, 2Stage 1/2:  17%|███████████▋                                                       | 440/2515 [00:01<00:07, Stage 1/2:  19%|████████████▍                                                      | 469/2515 [00:01<00:08,Stage 1/2:  20%|█████████████▏                                                     | 495/2515 [00:01<00:08Stage 1/2:  21%|█████████████▉                                                     | 521/2515 [00:01<00:08Stage 1/2:  22%|██████████████▌                                                    | 547/2515 [00:01<00:0Stage 1/2:  23%|███████████████▎                                                   | 573/2515 [00:02<00:Stage 1/2:  27%|█████████████████▉                                                 | 675/2515 [00:02<0Stage 1/2:  32%|█████████████████████▎                                             | 799/2515 [00:Stage 1/2:  36%|████████████████████████▏                                          | 909/2515 [Stage 1/2:  39%|██████████████████████████▎                                        | 990/2515Stage 1/2:  42%|███████████████████████████▊                                      | 1062/251Stage 1/2:  45%|█████████████████████████████▍                                    | 1120/2Stage 1/2:  46%|██████████████████████████████▋                                   | 1167/Stage 1/2:  48%|███████████████████████████████▋                                  | 1206Stage 1/2:  49%|████████████████████████████████▌                                 | 124Stage 1/2:  51%|█████████████████████████████████▍                                | 12Stage 1/2:  52%|██████████████████████████████████▏                               | 1Stage 1/2:  53%|██████████████████████████████████▊                               | 1Stage 1/2:  54%|███████████████████████████████████▌                              | Stage 1/2:  55%|████████████████████████████████████▏                             |Stage 1/2:  56%|████████████████████████████████████▊                             |Stage 1/2:  57%|█████████████████████████████████████▌                            Stage 1/2:  58%|██████████████████████████████████████▎                          Stage 1/2:  59%|██████████████████████████████████████▉                          Stage 1/2:  60%|███████████████████████████████████████▍                        Stage 1/2:  61%|████████████████████████████████████████▏                      Stage 1/2:  62%|████████████████████████████████████████▊                      Stage 1/2:  63%|█████████████████████████████████████████▍                    Stage 1/2:  64%|██████████████████████████████████████████                    Stage 1/2:  65%|██████████████████████████████████████████▉                  Stage 1/2:  66%|███████████████████████████████████████████▌                Stage 1/2:  67%|████████████████████████████████████████████▏              Stage 1/2:  68%|████████████████████████████████████████████▋              Stage 1/2:  69%|█████████████████████████████████████████████▎            Stage 1/2:  70%|█████████████████████████████████████████████▉            Stage 1/2:  70%|██████████████████████████████████████████████▌          Stage 1/2:  71%|███████████████████████████████████████████████          Stage 1/2:  73%|███████████████████████████████████████████████▊        Stage 1/2:  73%|████████████████████████████████████████████████▍      Stage 1/2:  74%|█████████████████████████████████████████████████▏    Stage 1/2:  75%|█████████████████████████████████████████████████▋    Stage 1/2:  76%|██████████████████████████████████████████████████▍  Stage 1/2:  77%|███████████████████████████████████████████████████  Stage 1/2:  78%|███████████████████████████████████████████████████▋Stage 1/2:  79%|████████████████████████████████████████████████████Stage 1/2:  80%|████████████████████████████████████████████████████Stage 1/2:  81%|████████████████████████████████████████████████████Stage 1/2:  82%|████████████████████████████████████████████████████Stage 1/2:  83%|████████████████████████████████████████████████████Stage 1/2:  84%|████████████████████████████████████████████████████Stage 1/2:  85%|████████████████████████████████████████████████████Stage 1/2:  86%|████████████████████████████████████████████████████Stage 1/2:  87%|████████████████████████████████████████████████████Stage 1/2:  88%|████████████████████████████████████████████████████Stage 1/2:  89%|████████████████████████████████████████████████████Stage 1/2:  90%|████████████████████████████████████████████████████Stage 1/2:  91%|████████████████████████████████████████████████████Stage 1/2:  92%|████████████████████████████████████████████████████Stage 1/2:  94%|████████████████████████████████████████████████████Stage 1/2:  97%|████████████████████████████████████████████████████Stage 1/2: 100%|██████████████████████████████████████████████████████████████████| 2515/2515 [00:08<00:00, 283.37it/s]
Stage 2/2: 100%|██████████████████████████████████████████████████████████████| 2513/2513 [00:00<00:00, 2513182.15it/s]
Saving...
Check contiguous...
Done!
Creating model from config: D:\sdwebui\webui\repositories\generative-models\configs\inference\sd_xl_base.yaml
Traceback (most recent call last):
  File "D:\sdwebui\system\python\lib\site-packages\gradio\routes.py", line 488, in run_predict
    output = await app.get_blocks().process_api(
  File "D:\sdwebui\system\python\lib\site-packages\gradio\blocks.py", line 1431, in process_api
    result = await self.call_function(
  File "D:\sdwebui\system\python\lib\site-packages\gradio\blocks.py", line 1103, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "D:\sdwebui\system\python\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "D:\sdwebui\system\python\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "D:\sdwebui\system\python\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "D:\sdwebui\system\python\lib\site-packages\gradio\utils.py", line 707, in wrapper
    response = f(*args, **kwargs)
  File "D:\sdwebui\webui\extensions\sd-webui-supermerger\scripts\mergers\mergers.py", line 131, in smergegen
    load_model(checkpoint_info, already_loaded_state_dict=theta_0)
  File "D:\sdwebui\webui\modules\sd_models.py", line 658, in load_model
    load_model_weights(sd_model, checkpoint_info, state_dict, timer)
  File "D:\sdwebui\webui\modules\sd_models.py", line 375, in load_model_weights
    model.load_state_dict(state_dict, strict=False)
  File "D:\sdwebui\webui\modules\sd_disable_initialization.py", line 223, in <lambda>
    module_load_state_dict = self.replace(torch.nn.Module, 'load_state_dict', lambda *args, **kwargs: load_state_dict(module_load_state_dict, *args, **kwargs))
  File "D:\sdwebui\webui\modules\sd_disable_initialization.py", line 221, in load_state_dict
    original(module, state_dict, strict=strict)
  File "D:\sdwebui\system\python\lib\site-packages\torch\nn\modules\module.py", line 2041, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for DiffusionEngine:
        size mismatch for model.diffusion_model.input_blocks.0.0.weight: copying a param with shape torch.Size([320, 9, 3, 3]) from checkpoint, the shape in current model is torch.Size([320, 4, 3, 3]).

All three models worked fine by themselves. And merging non-inpainting model worked fine too. Also tried merging other finetuned SDXL checkpoints, including my own finetunes, same error.

Link to juggernaut model
https://huggingface.co/RunDiffusion/Juggernaut-XL-v9

Thanks in advance.

**Comment by hako-mikan** [comment]
Fixed.
