### ISSUE TITLE
Script will not launch under Automatic 1111

### ISSUE THREAD

**Issue by dymension** [hako-mikan/sd-webui-supermerger#370]
I am using Automatic 111 under google Collab
I installed Supermerger extention from the extension panel first, then direcly from the github repo

The extension will not run, I have the following errors :
```
*** Error loading script: GenParamGetter.py
    Traceback (most recent call last):
      File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/scripts.py", line 527, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
(...)
AttributeError: module 'jax.random' has no attribute 'KeyArray'
```
then 
```
** Error loading script: supermerger.py
    Traceback (most recent call last):
      File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/scripts.py", line 527, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/sd-webui-supermerger/scripts/supermerger.py", line 23, in <module>
        import scripts.mergers.pluslora
(...)
AttributeError: module 'jax.random' has no attribute 'KeyArray'
```

how can we fix that N

**Comment by hako-mikan** [comment]
Is this issue still occurring

**Comment by dymension** [comment]
Hello
I now installed it on local machine.
I have plenty of error message, ... but still it's working
