### ISSUE TITLE
Add DoRA support

### ISSUE THREAD

**Issue by lendrick** [hako-mikan/sd-webui-supermerger#373]
Merging DoRAs currently fails with a Key Error.

merging C:\AI\automatic1111\models\Lora\d\36c_dora-000007.safetensors: [0.0, 0, 0, 0, 0, 0.0, 0.0, 0, 0.0, 0.0, 0, 0, 0, 0.0, 1.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0, 0, 0, 0, 0, 0]
dim: [4], alpha: [2.0]
merging...
Traceback (most recent call last):
  File "C:\AI\automatic1111\extensions\sd-webui-supermerger\scripts\mergers\pluslora.py", line 426, in lmerge
    sd = merge_lora_models(ln, lr, settings, False, calc_precision)
  File "C:\AI\automatic1111\extensions\sd-webui-supermerger\scripts\mergers\pluslora.py", line 480, in merge_lora_models
    base_alpha = base_alphas[lora_module_name]
KeyError: 'lora_te1_text_model_encoder_layers_0_mlp_fc1.dora_scal'

**Comment by a-l-e-x-d-s-9** [comment]
@hako-mikan 
Any updates regarding merging Doras?

**Comment by hako-mikan** [comment]
I’ve implemented support for DoRA merging, but it only works for single merges (such as applying lbw or strength adjustments) and might not function properly for multiple merges.
