### ISSUE TITLE
Error loading script: supermerger.py

### ISSUE THREAD

**Issue by larinius** [hako-mikan/sd-webui-supermerger#384]
This trash doesn't work, same errors as in other posts here year ago. 

` pip install scikit-learn
`
No effect. 
Solved by removing, now I have no errors in console.

`*** Error loading script: supermerger.py
    Traceback (most recent call last):
      File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/scripts.py", line 508, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/script_loading.py", line 13, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed`

**Comment by hako-mikan** [comment]
`pip install scikit-learn`
The command you provided is meant to be installed on your PC's Python environment, not the virtual environment that the web UI is using, so it doesn't make sense. 
I won't be able to assist you unless you show the full error you're encountering.
