### ISSUE TITLE
[BUG] fail to load supermerger in new version WEBforge UI (confirmed)

### ISSUE THREAD

**Issue by kalle07** [hako-mikan/sd-webui-supermerger#391]
i dont know is it on you or not 
(all other exetension working)

*** Error loading script: supermerger.py
    Traceback (most recent call last):
      File "E:\WebUI_Forge\webui\modules\scripts.py", line 525, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "E:\WebUI_Forge\webui\modules\script_loading.py", line 13, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "E:\WebUI_Forge\webui\extensions\sd-webui-supermerger\scripts\supermerger.py", line 41, in <module>
        class ResizeHandleRow(gr.Row):
      File "e:\WebUI_Forge\system\python\lib\site-packages\gradio\component_meta.py", line 202, in __new__
        create_or_modify_pyi(component_class, name, events)
      File "E:\WebUI_Forge\webui\modules\gradio_extensions.py", line 100, in gradio_component_meta_create_or_modify_pyi
        gradio_component_meta_create_or_modify_pyi_original(component_class, class_name, events)
      File "E:\WebUI_Forge\webui\modules_forge\forge_canvas\canvas.py", line 16, in create_or_modify_pyi_org_patched
        return create_or_modify_pyi_org(component_class, class_name, events)
      File "e:\WebUI_Forge\system\python\lib\site-packages\gradio\component_meta.py", line 90, in create_or_modify_pyi
        source_file = Path(inspect.getfile(component_class))
      File "e:\WebUI_Forge\system\python\lib\site-packages\torch\package\package_importer.py", line 696, in _patched_getfile
        return _orig_getfile(object)
      File "inspect.py", line 786, in getfile
    TypeError: <class 'supermerger.py.ResizeHandleRow'> is a built-in class

---

**Comment by BlackSheep1983** [comment]
Mine stopped working today, I'm also using Forge. I get different kind of a error thou.
*** Error executing callback ui_tabs_callback for F:\webui_forge_cu121_torch21\webui\extensions\sd-webui-supermerger\scripts\supermerger.py
    Traceback (most recent call last):
      File "F:\webui_forge_cu121_torch21\webui\modules\script_callbacks.py", line 283, in ui_tabs_callback
        res += c.callback() or []
      File "F:\webui_forge_cu121_torch21\webui\extensions\sd-webui-supermerger\scripts\supermerger.py", line 157, in on_ui_tabs
        with gr.Row(scale=2):
      File "F:\webui_forge_cu121_torch21\system\python\lib\site-packages\gradio\component_meta.py", line 163, in wrapper
        return fn(self, **kwargs)
    TypeError: Row.__init__() got an unexpected keyword argument 'scale'

**Comment by kalle07** [comment]
seems an error on WEBforge ...

**Comment by nicegoodabc** [comment]
> Mine stopped working today, I'm also using Forge. I get different kind of a error thou. *** Error executing callback ui_tabs_callback for F:\webui_forge_cu121_torch21\webui\extensions\sd-webui-supermerger\scripts\supermerger.py Traceback (most recent call last): File "F:\webui_forge_cu121_torch21\webui\modules\script_callbacks.py", line 283, in ui_tabs_callback res += c.callback() or [] File "F:\webui_forge_cu121_torch21\webui\extensions\sd-webui-supermerger\scripts\supermerger.py", line 157, in on_ui_tabs with gr.Row(scale=2): File "F:\webui_forge_cu121_torch21\system\python\lib\site-packages\gradio\component_meta.py", line 163, in wrapper return fn(self, **kwargs) TypeError: Row.**init**() got an unexpected keyword argument 'scale'

same

**Comment by Seeker1970** [comment]
I am also getting an error since ForgeUI was updated:

*** Error executing callback app_started_callback for D:\ForgeUI-new\webui_forge_cu121_torch21\webui\extensions\sd-webui-supermerger\scripts\GenParamGetter.py
    Traceback (most recent call last):
      File "D:\ForgeUI-new\webui_forge_cu121_torch21\webui\modules\script_callbacks.py", line 256, in app_started_callback
        c.callback(demo, app)
      File "D:\ForgeUI-new\webui_forge_cu121_torch21\webui\extensions\sd-webui-supermerger\scripts\GenParamGetter.py", line 56, in get_params_components
        dependencies: list[dict] = [x for x in demo.dependencies if x["trigger"] == "click" and _id in x["targets"]]
    AttributeError: 'Blocks' object has no attribute 'dependencies'

**Comment by dxwarlock** [comment]
Came to report the same bug, see it is reported.
I get the same:
` [...]
     File "inspect.py", line 786, in getfile
    TypeError: <class 'supermerger.py.ResizeHandleRow'> is a built-in class`

**Comment by kwikmn** [comment]
Also came here to report the same bug.

**Comment by hako-mikan** [comment]
Fixed.
