### ISSUE TITLE
Triton & Huggingface Errors

### ISSUE THREAD

**Issue by duskfallcrew** [hako-mikan/sd-webui-supermerger#393]
---
*** Error loading script: supermerger.py
    Traceback (most recent call last):
      File "/workspace/venv/lib/python3.10/site-packages/diffusers/utils/import_utils.py", line 808, in _get_module
        return importlib.import_module("." + module_name, self.__name__)
      File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
        return _bootstrap._gcd_import(name[level:], package, level)
      File "", line 1050, in _gcd_import
      File "", line 1027, in _find_and_load
      File "", line 992, in _find_and_load_unlocked
      File "", line 241, in _call_with_frames_removed
      File "", line 1050, in _gcd_import
      File "", line 1027, in _find_and_load
      File "", line 1006, in _find_and_load_unlocked
      File "", line 688, in _load_unlocked
      File "", line 883, in exec_module
      File "", line 241, in _call_with_frames_removed
      File "/workspace/venv/lib/python3.10/site-packages/diffusers/models/autoencoders/__init__.py", line 1, in 
        from .autoencoder_asym_kl import AsymmetricAutoencoderKL
      File "/workspace/venv/lib/python3.10/site-packages/diffusers/models/autoencoders/autoencoder_asym_kl.py", line 22, in 
        from ..modeling_utils import ModelMixin
      File "/workspace/venv/lib/python3.10/site-packages/diffusers/models/modeling_utils.py", line 29, in 
        from huggingface_hub import create_repo, split_torch_state_dict_into_shards
    ImportError: cannot import name 'split_torch_state_dict_into_shards' from 'huggingface_hub' (/workspace/venv/lib/python3.10/site-packages/huggingface_hub/__init__.py)

    The above exception was the direct cause of the following exception:

    Traceback (most recent call last):
      File "/workspace/stable-diffusion-webui/modules/scripts.py", line 527, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "/workspace/stable-diffusion-webui/modules/script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "", line 883, in exec_module
      File "", line 241, in _call_with_frames_removed
      File "/workspace/stable-diffusion-webui/extensions/sd-webui-supermerger/scripts/supermerger.py", line 23, in 
        import scripts.mergers.pluslora
      File "/workspace/stable-diffusion-webui/extensions/sd-webui-supermerger/scripts/mergers/pluslora.py", line 21, in 
        from scripts.kohyas import extract_lora_from_models as ext
      File "/workspace/stable-diffusion-webui/extensions/sd-webui-supermerger/scripts/kohyas/extract_lora_from_models.py", line 12, in 
        from scripts.kohyas import sai_model_spec,model_util,sdxl_model_util,lora
      File "/workspace/stable-diffusion-webui/extensions/sd-webui-supermerger/scripts/kohyas/model_util.py", line 16, in 
        from diffusers import AutoencoderKL, DDIMScheduler, StableDiffusionPipeline  # , UNet2DConditionModel
      File "", line 1075, in _handle_fromlist
      File "/workspace/venv/lib/python3.10/site-packages/diffusers/utils/import_utils.py", line 799, in __getattr__
        value = getattr(module, name)
      File "/workspace/venv/lib/python3.10/site-packages/diffusers/utils/import_utils.py", line 798, in __getattr__
        module = self._get_module(self._class_to_module[name])
      File "/workspace/venv/lib/python3.10/site-packages/diffusers/utils/import_utils.py", line 810, in _get_module
        raise RuntimeError(
    RuntimeError: Failed to import diffusers.models.autoencoders.autoencoder_kl because of the following error (look up to see its traceback):
    cannot import name 'split_torch_state_dict_into_shards' from 'huggingface_hub' (/workspace/venv/lib/python3.10/site-packages/huggingface_hub/__init__.py)

---

Honestly hoping this can get fixed because i dont know how to fix this on a server side GPU sadly.

**Comment by hako-mikan** [comment]
It seems that there may be an issue with your execution environment. The article below might be helpful.
https://github.com/run-llama/llama_index/discussions/14605

**Comment by duskfallcrew** [comment]
I haven't had this error since then, i just automatically import diffusers it could've been something i messed with. 
I'm still having various other tiny issues but i use ver 20 branch with a fix to get the lora merging to work so i'm going to try and peek what the issues i've had are and TRY and fork and fix - i dont program al ot but i would love to contribute
