### ISSUE TITLE
"Elemental" and "Add elemental" don't work for Z in XYZ

### ISSUE THREAD

**Issue by miasik** [hako-mikan/sd-webui-supermerger#395]
The same set of elementals works in X and Y — i see them as green parameter and its application in the console and as the resulting  images with expected difference
But then i put it into Z — nothing happens. I see it as a parameter for Z in the green part in console, but don't see its application neither in the console nor the resulting images

**Comment by hako-mikan** [comment]
Fixed.

**Comment by miasik** [comment]
My previously working elementals stopped working. They are something like this for XL:
`BASE::0.5,.input_blocks.0::0.1,.input_blocks.1::0.2,.input_blocks.2::0.3,.input_blocks.3::0.4,.input_blocks.4::0.5,.input_blocks.5::0.6,.input_blocks.6::0.7,.input_blocks.7::0.8,.input_blocks.8::0.9,.middle_block.::0.5,.output_blocks.0::0.9,.output_blocks.1::0.8,.output_blocks.2::0.7,.output_blocks.3::0.6,.output_blocks.4::0.5,.output_blocks.5::0.4,.output_blocks.6::0.3,.output_blocks.7::0.2,.output_blocks.8::0.1`

The error:
```
Stage 1/2:  56%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                                                                                              | 1409/2515 [00:04<00:03, 295.62it/s]
Traceback (most recent call last):
  File "g:\StableDiffusion\a1111\system\python\lib\site-packages\gradio\routes.py", line 488, in run_predict
    output = await app.get_blocks().process_api(
  File "g:\StableDiffusion\a1111\system\python\lib\site-packages\gradio\blocks.py", line 1431, in process_api
    result = await self.call_function(
  File "g:\StableDiffusion\a1111\system\python\lib\site-packages\gradio\blocks.py", line 1103, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "g:\StableDiffusion\a1111\system\python\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "g:\StableDiffusion\a1111\system\python\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "g:\StableDiffusion\a1111\system\python\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "g:\StableDiffusion\a1111\system\python\lib\site-packages\gradio\utils.py", line 707, in wrapper
    response = f(*args, **kwargs)
  File "G:\StableDiffusion\a1111\webui\extensions\sd-webui-supermerger\scripts\mergers\xyplot.py", line 78, in numanager
    result,currentmodel,xyimage,a,b,c= sgenxyplot(*allsets)
  File "G:\StableDiffusion\a1111\webui\extensions\sd-webui-supermerger\scripts\mergers\xyplot.py", line 434, in sgenxyplot
    _, currentmodel,modelid,theta_0, metadata =smerge(weights_a_in,weights_b_in, model_a,model_b,model_c, float(alpha),float(beta),mode,calcmode,
  File "G:\StableDiffusion\a1111\webui\extensions\sd-webui-supermerger\scripts\mergers\mergers.py", line 452, in smerge
    weight_index = BLOCKIDXLL.index(blocks26)
ValueError: 'Not Merge' is not in list
```
![изображение](https://github.com/user-attachments/assets/38834347-ebba-4daf-acbe-97bc9e57b2d3)
And Z is None for the run

It's the same as #407 as I see

**Comment by hako-mikan** [comment]
Fixed.

**Comment by miasik** [comment]
It works now, thanks!
