### ISSUE TITLE
Can't use supermerger with SD WebUI Forge

### ISSUE THREAD

**Issue by Neox-000** [hako-mikan/sd-webui-supermerger#396]
```
Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Version: f1.0.2v1.10.1-previous-168-gf743fbff
Commit hash: f743fbff83c7db0bf0957ab9718f8d42a47eb35e
Launching Web UI with arguments:
Total VRAM 6144 MB, total RAM 14188 MB
pytorch version: 2.1.2+cu121
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 3060 Laptop GPU : native
Hint: your device supports --pin-shared-memory for potential speed improvements.
Hint: your device supports --cuda-malloc for potential speed improvements.
Hint: your device supports --cuda-stream for potential speed improvements.
VAE dtype preferences: [torch.bfloat16, torch.float32] -> torch.bfloat16
CUDA Stream Activated:  False
C:\SD\system\python\lib\site-packages\transformers\utils\hub.py:127: FutureWarning: Using `TRANSFORMERS_CACHE` is deprecated and will be removed in v5 of Transformers. Use `HF_HOME` instead.
  warnings.warn(
Using pytorch cross attention
Using pytorch attention for VAE
ControlNet preprocessor location: C:\SD\webui\models\ControlNetPreprocessor
2024-08-07 13:29:42,351 - ControlNet - INFO - ControlNet UI callback registered.
*** Error executing callback ui_tabs_callback for C:\SD\webui\extensions\sd-webui-supermerger\scripts\supermerger.py
    Traceback (most recent call last):
      File "C:\SD\webui\modules\script_callbacks.py", line 283, in ui_tabs_callback
        res += c.callback() or []
      File "C:\SD\webui\extensions\sd-webui-supermerger\scripts\supermerger.py", line 157, in on_ui_tabs
        with gr.Row(scale=2):
      File "C:\SD\system\python\lib\site-packages\gradio\component_meta.py", line 163, in wrapper
        return fn(self, **kwargs)
    TypeError: Row.__init__() got an unexpected keyword argument 'scale'

---
Checkpoint realisticVisionV51_v51VAE.safetensors not found; loading fallback animagineXLV31_v30.safetensors [1449e5b0b9]
Loading weights [1449e5b0b9] from C:\SD\webui\models\Stable-diffusion\animagineXLV31_v30.safetensors
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
StateDict Keys: {'unet': 1680, 'vae': 248, 'text_encoder': 197, 'text_encoder_2': 518, 'ignore': 0}
*** Error executing callback app_started_callback for C:\SD\webui\extensions\sd-webui-supermerger\scripts\GenParamGetter.py
    Traceback (most recent call last):
      File "C:\SD\webui\modules\script_callbacks.py", line 256, in app_started_callback
        c.callback(demo, app)
      File "C:\SD\webui\extensions\sd-webui-supermerger\scripts\GenParamGetter.py", line 56, in get_params_components
        dependencies: list[dict] = [x for x in demo.dependencies if x["trigger"] == "click" and _id in x["targets"]]
    AttributeError: 'Blocks' object has no attribute 'dependencies'

---
Startup time: 22.7s (prepare environment: 5.5s, launcher: 3.1s, import torch: 5.0s, initialize shared: 0.2s, other imports: 2.0s, load scripts: 2.8s, create ui: 2.3s, gradio launch: 1.7s).
Working with z of shape (1, 4, 32, 32) = 4096 dimensions.
K-Model Created: {'storage_dtype': torch.float16, 'computation_dtype': torch.float16, 'manual_cast': False}
Model loaded in 13.0s (load weights from disk: 1.8s, forge model load: 11.1s).
```

**Comment by FrakerKill** [comment]
+1

**Comment by hako-mikan** [comment]
Fixed.
