### ISSUE TITLE
GenParamGetter.py error pop-up since the update.

### ISSUE THREAD

**Issue by Neytiri7** [hako-mikan/sd-webui-supermerger#403]
After the update, the GenParamGetter.py error pops up.

```
*** Error executing callback app_started_callback for W:\SynologyDrive\PonyXL\extensions\sd-webui-supermerger\scripts\GenParamGetter.py
    Traceback (most recent call last):
      File "W:\SynologyDrive\PonyXL\modules\script_callbacks.py", line 256, in app_started_callback
        c.callback(demo, app)
      File "W:\SynologyDrive\PonyXL\extensions\sd-webui-supermerger\scripts\GenParamGetter.py", line 60, in get_params_components
        dependencies: list[dict] = [x for x in demo.config["dependencies"] if x["targets"][0][1] == "click" and _id in x["targets"][0]]
      File "W:\SynologyDrive\PonyXL\extensions\sd-webui-supermerger\scripts\GenParamGetter.py", line 60, in <listcomp>
        dependencies: list[dict] = [x for x in demo.config["dependencies"] if x["targets"][0][1] == "click" and _id in x["targets"][0]]
    TypeError: 'int' object is not subscriptable
```

**Comment by hako-mikan** [comment]
Thanks! Fixed.
