### ISSUE TITLE
After upgrading to a new version, it becomes unusable

### ISSUE THREAD

**Issue by nevernamekimo** [hako-mikan/sd-webui-supermerger#404]
If update to a version after October 9th, you will not be able to use it.
If you downgrade it back to the version on September 28, it will still be usable. I don’t understand why at the moment.

Traceback (most recent call last):
  File "I:\AI\sd-webui-aki\python\lib\site-packages\gradio\routes.py", line 488, in run_predict
    output = await app.get_blocks().process_api(
  File "I:\AI\sd-webui-aki\python\lib\site-packages\gradio\blocks.py", line 1431, in process_api
    result = await self.call_function(
  File "I:\AI\sd-webui-aki\python\lib\site-packages\gradio\blocks.py", line 1103, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "I:\AI\sd-webui-aki\python\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "I:\AI\sd-webui-aki\python\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "I:\AI\sd-webui-aki\python\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "I:\AI\sd-webui-aki\python\lib\site-packages\gradio\utils.py", line 707, in wrapper
    response = f(*args, **kwargs)
  File "I:\AI\sd-webui-aki\extensions\sd-webui-supermerger\scripts\mergers\mergers.py", line 119, in smergegen
    result,currentmodel,modelid,theta_0,metadata = smerge(
  File "I:\AI\sd-webui-aki\extensions\sd-webui-supermerger\scripts\mergers\mergers.py", line 421, in smerge
    theta_1[key] = theta_1[key].to("cuda")
KeyError: 'model.diffusion_model.double_blocks.0.img_attn.proj.bias'
------------------------
Fault Traceback: 
Not Available

**Comment by hako-mikan** [comment]
It seems like you're trying to merge FLUX, but could you tell me what type of models you're trying to merge?

**Comment by nevernamekimo** [comment]
No, I am merger the SD15 MODEL. It is exactly the same MODEL and the same settings. The version on September 28th can be mergered normally, but as long as it is updated to the new version, it will not work. Now I see different errors. message

Traceback (most recent call last):
  File "I:\ATraceback (most recent call last):
  File "I:\AI\sd-webui-aki\python\lib\site-packages\gradio\routes.py", line 488, in run_predict
    output = await app.get_blocks().process_api(
  File "I:\AI\sd-webui-aki\python\lib\site-packages\gradio\blocks.py", line 1431, in process_api
    result = await self.call_function(
  File "I:\AI\sd-webui-aki\python\lib\site-packages\gradio\blocks.py", line 1103, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "I:\AI\sd-webui-aki\python\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "I:\AI\sd-webui-aki\python\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "I:\AI\sd-webui-aki\python\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "I:\AI\sd-webui-aki\python\lib\site-packages\gradio\utils.py", line 707, in wrapper
    response = f(*args, **kwargs)
  File "I:\AI\sd-webui-aki\extensions\sd-webui-supermerger\scripts\mergers\mergers.py", line 119, in smergegen
    result,currentmodel,modelid,theta_0,metadata = smerge(
  File "I:\AI\sd-webui-aki\extensions\sd-webui-supermerger\scripts\mergers\mergers.py", line 279, in smerge
    hashfromname(model_a),hashfromname(model_b),hashfromname(model_c),
  File "I:\AI\sd-webui-aki\extensions\sd-webui-supermerger\scripts\mergers\mergers.py", line 1120, in hashfromname
    if checkpoint_info.shorthash is not None:
AttributeError: 'NoneType' object has no attribute 'shorthash'I\sd-webui-aki\python\lib\site-packages\gradio\routes.py", line 488, in run_predict
    output = await app.get_blocks().process_api(
  File "I:\AI\sd-webui-aki\python\lib\site-packages\gradio\blocks.py", line 1431, in process_api
    result = await self.call_function(
  File "I:\AI\sd-webui-aki\python\lib\site-packages\gradio\blocks.py", line 1103, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "I:\AI\sd-webui-aki\python\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "I:\AI\sd-webui-aki\python\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "I:\AI\sd-webui-aki\python\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "I:\AI\sd-webui-aki\python\lib\site-packages\gradio\utils.py", line 707, in wrapper
    response = f(*args, **kwargs)
  File "I:\AI\sd-webui-aki\extensions\sd-webui-supermerger\scripts\mergers\mergers.py", line 119, in smergegen
    result,currentmodel,modelid,theta_0,metadata = smerge(
  File "I:\AI\sd-webui-aki\extensions\sd-webui-supermerger\scripts\mergers\mergers.py", line 279, in smerge
    hashfromname(model_a),hashfromname(model_b),hashfromname(model_c),
  File "I:\AI\sd-webui-aki\extensions\sd-webui-supermerger\scripts\mergers\mergers.py", line 1120, in hashfromname
    if checkpoint_info.shorthash is not None:
AttributeError: 'NoneType' object has no attribute 'shorthash'

**Comment by hako-mikan** [comment]
The error occurs when nothing is selected in the model field. 
I'm not familiar with something called 'sd-webui-aki,' but can I assume it's the same as Automatic1111's Web UI?

**Comment by nevernamekimo** [comment]
The error code in the previous article, as you said, seems to be OK if you change it to an English file name, but another error code appears. This is the error code I saw when I updated on the first day. 
Traceback (most recent call last):
  File "I:\AI\sd-webui-aki\python\lib\site-packages\gradio\routes.py", line 488, in run_predict
    output = await app.get_blocks().process_api(
  File "I:\AI\sd-webui-aki\python\lib\site-packages\gradio\blocks.py", line 1431, in process_api
    result = await self.call_function(
  File "I:\AI\sd-webui-aki\python\lib\site-packages\gradio\blocks.py", line 1103, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "I:\AI\sd-webui-aki\python\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "I:\AI\sd-webui-aki\python\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "I:\AI\sd-webui-aki\python\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "I:\AI\sd-webui-aki\python\lib\site-packages\gradio\utils.py", line 707, in wrapper
    response = f(*args, **kwargs)
  File "I:\AI\sd-webui-aki\extensions\sd-webui-supermerger\scripts\mergers\mergers.py", line 119, in smergegen
    result,currentmodel,modelid,theta_0,metadata = smerge(
  File "I:\AI\sd-webui-aki\extensions\sd-webui-supermerger\scripts\mergers\mergers.py", line 445, in smerge
    block,blocks26 = blockfromkey(key,isxl,flux)
ValueError: too many values ​​to unpack (expected 2)

**Comment by hako-mikan** [comment]
It seems that the script update is probably incomplete.
I recommend uninstalling it once and then reinstalling it.

**Comment by hako-mikan** [comment]
As far as I've tested, I didn't encounter the same issue. It could be a problem when loading the merged model, or possibly related to the seed. If the same issue is still occurring, please provide more details about the situation. If I know which merged model or LoRA model you're using, I might be able to reproduce the issue on my end.

**Comment by nevernamekimo** [comment]
It seems like this is the problem. I have uninstalled and reinstalled before updating. 
This time I even cleared the cache, reinstalled, and used the latest version updated today, and it can be used normally.
 Thank you so much!
