### ISSUE TITLE
Suport for Flux LoRA merge

### ISSUE THREAD

**Issue by diodiogod** [hako-mikan/sd-webui-supermerger#414]
Please, may you consider support for merging Flux LoRAs? 
Specially with block weights? Maybe consider supporting 19 or 57 values input for the blocks. Refer to this discussion with @nihedon
https://github.com/nihedon/sd-webui-lora-block-weight/issues/2#issuecomment-2390632995

Right now the only tool I know of to merge loras is some nodes on comfyui and this: https://github.com/Anashel-RPG/anashel-utils
And to save loras with modified block weights, I tried to create my own tool, but I'm not sure what is the proper target layers: https://github.com/diodiogod/Flux-Block-Weight-Remerger

I would love to be able to use supermerger again, like I did with SDXL, for flux, specially with the "same to Strength" option.

Thanks!!

**Comment by duskfallcrew** [comment]
There's no way to do it on A111 as there's no flux support AFAIK.

**Comment by diodiogod** [comment]
> There's no way to do it on A111 as there's no flux support AFAIK.

I'm asking for Forge, obviously. Nihedon managed to port LBW to forge and then managed to support Flux. From what I understand, hako-mikan implemented support for Forge, but so far, the lora merging for flux don't work. 
I opened a ticket to so hako-mikan knows this is wanted. I hope it gets implemented! =D

**Comment by duskfallcrew** [comment]
> > There's no way to do it on A111 as there's no flux support AFAIK.
> 
> I'm asking for Forge, obviously. Nihedon managed to port LBW to forge and then managed to support Flux. From what I understand, hako-mikan implemented support for Forge, but so far, the lora merging for flux don't work. I opened a ticket to so hako-mikan knows this is wanted. I hope it gets implemented! =D

If you try the "replace pluslora.py" with the branch/tree 20's version IT MIGIHT work, but that's dependent on the fact it worked for me on a vast instance, and i'm not running forge.

**Comment by hako-mikan** [comment]
I have addressed the issue. 
At the same time, I’ve also implemented Flux support for LoRA Block Weight.

**Comment by diodiogod** [comment]
> I have addressed the issue. At the same time, I’ve also implemented Flux support for LoRA Block Weight.

That is fantastic news! I'll try to test it today.
1- So can we use the same options like "same to strength" to merge flux loras now? 
2- And How have you implemented Flux LoRa blocks? The same way as @nihedon implementation with 19 blocks/57 full blocks or like inspire-pack from comfyui with 58 blocks?

**Comment by hako-mikan** [comment]
Sure. It works as "same to strength." 
Basically, you can get a model that provides outputs as if LoRA was applied normally on the web UI. 
The model's layers are divided into 61 parts, as indicated by the LoRA Block Weight.
https://github.com/hako-mikan/sd-webui-lora-block-weight?tab=readme-ov-file#weights-setting

**Comment by diodiogod** [comment]
> Sure. It works as "same to strength." Basically, you can get a model that provides outputs as if LoRA was applied normally on the web UI. The model's layers are divided into 61 parts, as indicated by the LoRA Block Weight. https://github.com/hako-mikan/sd-webui-lora-block-weight?tab=readme-ov-file#weights-setting

Oh great, I see you updated the README! I get that the clip and T5 are the text encoders, but what does the IN and OUT values mean, since we have the 57 flux main blocks as well (19 double + 38 singles)?

**Comment by hako-mikan** [comment]
Oh, by the way, regarding flux, I wasn’t able to get any LoRA trained on T5 or CLIP, so right now, I can only merge the DiT part. If you know where I can find LoRA trained on T5 or CLIP, please let me know.
As for IN and OUT, if you look at the diagram, you’ll see they correspond to the parts before and after DiT. Stable Diffusion has similar layers, but it seems they were grouped into IN00 and OUT11.
![Image](https://github.com/user-attachments/assets/bfb80f43-35d8-449d-bd0a-56d906413228)

**Comment by diodiogod** [comment]
> Oh, by the way, regarding flux, I wasn’t able to get any LoRA trained on T5 or CLIP, so right now, I can only merge the DiT part. If you know where I can find LoRA trained on T5 or CLIP, please let me know. As for IN and OUT, if you look at the diagram, you’ll see they correspond to the parts before and after DiT. Stable Diffusion has similar layers, but it seems they were grouped into IN00 and OUT11. ![Image](https://github.com/user-attachments/assets/bfb80f43-35d8-449d-bd0a-56d906413228)

Thanks for the explanation, it helps a lot in translation other tools format to test on your implementation!
For now, testing a LoRa without any trainin on TEs, the value on IN and OUT does not change the image at all. I'll test with a LoRa with TE to see if it makes any difference.

I have a LoRa trained with kohya with both t5 and clip. It's not  good lora, so I did not publish it. But if it helps, here it is: 
https://drive.google.com/file/d/1CuZzAcUciLxPzjUDihCR4p2GLVC2Wsof/view?usp=sharing

here is a list of its tensors: https://pastebin.com/XrsYy7Mq

**Comment by hako-mikan** [comment]
Thank you. With this, I can test the code.
Since Flux runs significantly slower on my hardware, it might take some time to verify, but I’ll also work on supporting T5 and CLIP.

**Comment by diodiogod** [comment]
> Thank you. With this, I can test the code. Since Flux runs significantly slower on my hardware, it might take some time to verify, but I’ll also work on supporting T5 and CLIP.

Great!
I did some testing (on block weight, not merging yet) with this LoRa. If I remember correctly it is quite weak so I pumped the strenght to 1.8, also to see more clearly any effect.

my conclusions are still IN or OUT (the third and last value) makes no difference on the image. Even with the CLIP and T5 at 1.

Here are some testings:
0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,1,1,1,1,1,1,1.15,1.15,1.15,1.15,1,1,1,1,0.25,0.25,0.25,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
CLIP T5 0
IN OUT 0
<img src="https://github.com/user-attachments/assets/e26d2576-07ac-4ec4-a6a0-1d211dbad45c" height="200">

0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,1,1,1,1,1,1,1.15,1.15,1.15,1.15,1,1,1,1,0.25,0.25,0.25,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
CLIP T5 0
IN OUT 1 (no change)
<img src="https://github.com/user-attachments/assets/e6fc727a-22d5-486b-8252-05cb7ec5dd6d" height="200">

1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,1,1,1,1,1,1,1.15,1.15,1.15,1.15,1,1,1,1,0.25,0.25,0.25,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1
CLIP T5 1
IN OUT 1
<img src="https://github.com/user-attachments/assets/209884d3-e139-4f50-873b-b2e5a2d454cf" height="200">

1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,1,1,1,1,1,1,1.15,1.15,1.15,1.15,1,1,1,1,0.25,0.25,0.25,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
CLIP T5 1
IN OUT 0 (no change)
<img src="https://github.com/user-attachments/assets/3902ae13-bdc9-4ef5-84de-3860141089eb" height="200">

**Comment by hako-mikan** [comment]
@diodiogod 
Thanks for your model, fixed.

**Comment by diodiogod** [comment]
Ok so @hako-mikan  I have an error, I'll try to explain this the best I can.

I'm unable to merge two flux LoRas that had ANY block weight adjusted to 0 by my tool (I've only tested adjusting the .alpha layers, I have not tested the other layers): https://github.com/diodiogod/Flux-Block-Weight-Remerger

But this only happens if it is the first lora of the list that have a zero layer, for example:
lora_with_weght_adjusted_to_zero:0.4,lora2_with_weght_adjusted_to_zero:1.4

this will error out with this message:
```
Traceback (most recent call last):
  File "J:\stablediffusion1111s2\Data\Packages\forge2\extensions\sd-webui-supermerger\scripts\mergers\pluslora.py", line 458, in lmerge
    sd = merge_lora_models(ln, lr, settings, False, calc_precision, device)
  File "J:\stablediffusion1111s2\Data\Packages\forge2\extensions\sd-webui-supermerger\scripts\mergers\pluslora.py", line 524, in merge_lora_models
    scale = math.sqrt(alpha / base_alpha) * ratio
ZeroDivisionError: float division by zero

```

But if the first lora is a lora that have not been adjusted, but the second one is, it will merge, like this
not_adjusted_lora:0.4,lora2_with_weght_adjusted_to_zero:1.4

This will work.

OR, (I've just tested this now), if the first lora has been adjusted but with weights that are non zero, like this preset for example where the values I wish were 0 I set to 0.05 instead 1,1,1,1,1.15,1.15,1,1,0.25,0.25,0.25,0.25,0.25,0.5,0.25,1.5,1.25,0.25,1,0.05,0.05,0.05,0.05,0.05,0.05,0.05,0.05,1,1,1,1,0.05,0.05,0.5,0.05,0.05,0.05,0.05,0.05,0.05,0.05,0.05,0.05,0.05,0.05,0.05,1,1,1,1,0.05,0.05,0.5,0.05,0.05,0.05,0.05

lora_with_weght_adjusted_close_to_zero:0.4,lora2_with_weght_adjusted_to_zero:1.4

It will work

Thanks in advance. If you want to test this yourself here are some loras:
adjusted_with_zeros_Sweaty Shirt Flux v8c-000020 https://drive.google.com/file/d/1bEMmtsf2RrRCqrLiMO_huo-D_ezfGsiy/view?usp=sharing
adjusted_with_zeros_Sweaty Shirt Flux v7-000017 https://drive.google.com/file/d/1zOhda8baYL7qPKWKLzQLfIdFM3TlMr8o/view?usp=sharing
adjusted_nonzero_Sweaty Shirt Flux v8c-000020 https://drive.google.com/file/d/1MflqcPjFn-MYD6xabU2nvlagCzU2r7aQ/view?usp=sharing

What I initially wanted was merge 0.4 strengh of v8c_epoch20 with 1.4 strengh of v7_epoch17, but each had their layers adjusted to a specific preset by my remerger.

**Comment by shungyuesuolong** [comment]
ERROR:Block is not deteced:model.diffusion_model.double_blocks.0.img_attn.proj.weight
融合lora的时候后台出现这样的提示，我用的秋叶webui ，没有用webui forge，
