### ISSUE TITLE
AttributeError: 'FakeInitialModel' object has no attribute 'sd_checkpoint_info'

### ISSUE THREAD

**Issue by edisonblack55555** [hako-mikan/sd-webui-supermerger#418]
Traceback (most recent call last):
  File "E:\桌面\sd-webui-forge\.ext\Lib\site-packages\gradio\queueing.py", line 536, in process_events
    response = await route_utils.call_process_api(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\桌面\sd-webui-forge\.ext\Lib\site-packages\gradio\route_utils.py", line 285, in call_process_api
    output = await app.get_blocks().process_api(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\桌面\sd-webui-forge\.ext\Lib\site-packages\gradio\blocks.py", line 1923, in process_api
    result = await self.call_function(
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\桌面\sd-webui-forge\.ext\Lib\site-packages\gradio\blocks.py", line 1508, in call_function
    prediction = await anyio.to_thread.run_sync(  # type: ignore
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\桌面\sd-webui-forge\.ext\Lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\桌面\sd-webui-forge\.ext\Lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
           ^^^^^^^^^^^^
  File "E:\桌面\sd-webui-forge\.ext\Lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\桌面\sd-webui-forge\.ext\Lib\site-packages\gradio\utils.py", line 818, in wrapper
    response = f(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^
  File "E:\桌面\sd-webui-forge\extensions\sd-webui-supermerger\scripts\mergers\pluslora.py", line 289, in makelora
    currentinfo = shared.sd_model.sd_checkpoint_info
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'FakeInitialModel' object has no attribute 'sd_checkpoint_info'

**Comment by hako-mikan** [comment]
It was fixed in current version.
