### ISSUE TITLE
Unable to merge LoRA with SDXL

### ISSUE THREAD

**Issue by MY803-DEV** [hako-mikan/sd-webui-supermerger#419]
初めまして。
hakomikan さんのデルタモンのLoRA Block Weight で LoRA の調整を行い、 SuperMerger を使用して最終的にLoRAをマージする記事を拝見しまして、こちらの SuperMerger を試用しております。
記事を参考に私の方ではSDXLベースで試しておりますが、以下のエラーが出てマージが行えない状況です。
設定に問題などありますでしょうか？
解決方法などありましたら教えて頂けますと助かります。

コンソールのエラー文
~~~
merging D:\StabilityMatrix-win-x64_ATP2024PV\Data\Packages\Stable Diffusion WebUI - v1.9.4\models\Lora\test_SDXL_LoRA_v02_001.safetensors: [1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 1.0, 0, 0, 0, 0.0, 1.3, 1.3, 1.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0, 0, 0]
dim: [16], alpha: [8.0]
merging...
Traceback (most recent call last):
  File "D:\StabilityMatrix-win-x64_ATP2024PV\Data\Packages\Stable Diffusion WebUI - v1.9.4\extensions\sd-webui-supermerger\scripts\mergers\pluslora.py", line 426, in lmerge
    sd = merge_lora_models(ln, lr, settings, False, calc_precision)
  File "D:\StabilityMatrix-win-x64_ATP2024PV\Data\Packages\Stable Diffusion WebUI - v1.9.4\extensions\sd-webui-supermerger\scripts\mergers\pluslora.py", line 483, in merge_lora_models
    ratio = ratios[blockfromkey(key, keylist, isv2)]
IndexError: list index out of range
~~~

**使用環境**

diffusers バージョン
- Version: 0.31.0  

Stable Diffusion WebUI バージョン
（※上記エラー文では[Stable Diffusion WebUI - v1.9.4]とありますが、中身はv1.10.1です。）
- 1.10.0  

SuperMerger commit
- [aa82ea5](https://github.com/hako-mikan/sd-webui-supermerger/commit/aa82ea54efc0394ed944d683334c1cda403dff2b)  

Lora Block Weight  commit
- [4d94d24](https://github.com/hako-mikan/sd-webui-lora-block-weight/commit/4d94d247a6e6d77c11c2d536a5138a54f4d9e500)  

StableMatrix バージョン
- Version: 2.12.1  

![SDWebUI_SuperMerger_Setting](https://github.com/user-attachments/assets/fad5b4c3-9140-4374-bd96-9e1d8b1b0891)

**Comment by hako-mikan** [comment]
最新版では修整されているはずです。

**Comment by MY803-DEV** [comment]
対応ありがとうございます。
時間が取れましたら確認させて頂きます。
