### ISSUE TITLE
Will not load in forge. 

### ISSUE THREAD

**Issue by andy8992** [hako-mikan/sd-webui-supermerger#420]
---
*** Error loading script: GenParamGetter.py
    Traceback (most recent call last):
      File "E:\Data\Packages\Stable Diffusion WebUI Forge\modules\scripts.py", line 525, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "E:\Data\Packages\Stable Diffusion WebUI Forge\modules\script_loading.py", line 13, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "E:\Data\Packages\Stable Diffusion WebUI Forge\extensions\sd-webui-supermerger\scripts\GenParamGetter.py", line 2, in <module>
        import scripts.mergers.components as components
    ModuleNotFoundError: No module named 'scripts.mergers'

---
*** Error loading script: supermerger.py
    Traceback (most recent call last):
      File "E:\Data\Packages\Stable Diffusion WebUI Forge\modules\scripts.py", line 525, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "E:\Data\Packages\Stable Diffusion WebUI Forge\modules\script_loading.py", line 13, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "E:\Data\Packages\Stable Diffusion WebUI Forge\extensions\sd-webui-supermerger\scripts\supermerger.py", line 24, in <module>
        import scripts.mergers.mergers
    ModuleNotFoundError: No module named 'scripts.mergers'

No idea why. All scripts are present etc. Fresh extension install

**Comment by andy8992** [comment]
conflict with mosaic extension making new issue
