### ISSUE TITLE
merger runs in a n error - forgeUI

### ISSUE THREAD

**Issue by kalle07** [hako-mikan/sd-webui-supermerger#421]
Stage 0/2: 100%|###################################################################| 2515/2515 [00:34<00:00, 72.42it/s]
Stage 1/2: 100%|##################################################################| 2515/2515 [00:17<00:00, 141.05it/s]
Stage 2/2: 100%|#############################################################################| 260/260 [00:00<?, ?it/s]
Baking in VAE from E:\WebUI_Forge\webui\models\VAE\sdxl_vae_fp16.safetensors
Traceback (most recent call last):
  File "e:\WebUI_Forge\system\python\lib\site-packages\gradio\queueing.py", line 536, in process_events
    response = await route_utils.call_process_api(
  File "e:\WebUI_Forge\system\python\lib\site-packages\gradio\route_utils.py", line 285, in call_process_api
    output = await app.get_blocks().process_api(
  File "e:\WebUI_Forge\system\python\lib\site-packages\gradio\blocks.py", line 1923, in process_api
    result = await self.call_function(
  File "e:\WebUI_Forge\system\python\lib\site-packages\gradio\blocks.py", line 1508, in call_function
    prediction = await anyio.to_thread.run_sync(  # type: ignore
  File "e:\WebUI_Forge\system\python\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "e:\WebUI_Forge\system\python\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "e:\WebUI_Forge\system\python\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "e:\WebUI_Forge\system\python\lib\site-packages\gradio\utils.py", line 818, in wrapper
    response = f(*args, **kwargs)
  File "E:\WebUI_Forge\webui\extensions\sd-webui-supermerger\scripts\mergers\mergers.py", line 119, in smergegen
    result,currentmodel,modelid,theta_0,metadata = smerge(
  File "E:\WebUI_Forge\webui\extensions\sd-webui-supermerger\scripts\mergers\mergers.py", line 611, in smerge
    for key in vae_dict.keys():
AttributeError: 'NoneType' object has no attribute 'keys'

if i dont bake in VAE
no error but if i use the model

AssertionError: You do not have CLIP state dict!
You do not have CLIP state dict!
(in swarmui -> black image)

**Comment by andy8992** [comment]
how'd you even get it to load in forge, mine wont..

**Comment by kalle07** [comment]
disable autorun UI in settings
and copy/paste manualy the local ip in your browser

**Comment by hako-mikan** [comment]
Same to #407, fixed.
