### ISSUE TITLE
Merging Lora w Checkpoint - RuntimeError: Expected all tensors to be on the same device

### ISSUE THREAD

**Issue by cosmiclantern** [hako-mikan/sd-webui-supermerger#49]
Hello, every time I try to merge a Lora with my checkpoint I get the following error:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/gradio/routes.py", line 394, in run_predict
    output = await app.get_blocks().process_api(
  File "/usr/local/lib/python3.9/dist-packages/gradio/blocks.py", line 1075, in process_api
    result = await self.call_function(
  File "/usr/local/lib/python3.9/dist-packages/gradio/blocks.py", line 884, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/usr/local/lib/python3.9/dist-packages/anyio/to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/usr/local/lib/python3.9/dist-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "/usr/local/lib/python3.9/dist-packages/anyio/_backends/_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/sd-webui-supermerger/scripts/mergers/pluslora.py", line 307, in pluslora
    weight = weight  + ratio * (up_weight @ down_weight) * scale
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!

--------

I'm running the webui on Google Colab, TheLastBen's notebook. 

The Lora I'm trying to merge is of dimension 64, and I have checked the "Same Strength" check box.

What am I doing wrong???

**Comment by hako-mikan** [comment]
Colab is difficult to fix.
I don't know why this is happening, but I have tried to deal with it. Please give it a try.

**Comment by cosmiclantern** [comment]
Thank you for replying! I will give the update a try :)

**Comment by cosmiclantern** [comment]
It worked! Thanks for the update 🙏
