### ISSUE TITLE
bug: TypeError: savemodel() takes 5 positional arguments but 6 were given 

### ISSUE THREAD

**Issue by drnighthan** [hako-mikan/sd-webui-supermerger#56]
I already updated the latest version of supermerger, but the problems don't solve

Traceback (most recent call last):
  File "D:\GitHub\StableDiffusion-webui-aki-v3\py310\lib\site-packages\gradio\routes.py", line 394, in run_predict
    output = await app.get_blocks().process_api(
  File "D:\GitHub\StableDiffusion-webui-aki-v3\py310\lib\site-packages\gradio\blocks.py", line 1075, in process_api
    result = await self.call_function(
  File "D:\GitHub\StableDiffusion-webui-aki-v3\py310\lib\site-packages\gradio\blocks.py", line 884, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "D:\GitHub\StableDiffusion-webui-aki-v3\py310\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "D:\GitHub\StableDiffusion-webui-aki-v3\py310\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "D:\GitHub\StableDiffusion-webui-aki-v3\py310\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "D:\GitHub\StableDiffusion-webui-aki-v3\extensions\sd-webui-supermerger\scripts\mergers\mergers.py", line 69, in smergegen
    result = savemodel(theta_0,currentmodel,custom_name,save_sets,model_a,metadata) if save else "Merged model loaded:"+currentmodel
TypeError: savemodel() takes 5 positional arguments but 6 were given

**Comment by drnighthan** [comment]
change back to the old version , problem solve

**Comment by hako-mikan** [comment]
This problem may occur if web-ui.bat is not restarted after the update, not reload.
