### ISSUE TITLE
TypeError: read_state_dict() takes 1 positional argument but 2 were given

### ISSUE THREAD

**Issue by nailz420** [hako-mikan/sd-webui-supermerger#59]
Calculating sha256 for H:\projects\AI\SD\subredditV3_39423.safetensors: c2cae1b33b26ed0f9f7ef2baf63246a58ddb4ab3edd756318628b9d834bc2349
Calculating sha256 for H:\projects\AI\SD\metagodSelfieMix_metagodSelfieMix10.safetensors: a1fd3b0f5cab783487e4fe071c1035961637294a9a8fa07d06f6080e627ce32c
  model A       : subredditV3_39423
  model B       : metagodSelfieMix_metagodSelfieMix10
  model C       :
  alpha,beta    : (0.5, 0.25)
  weights_alpha :
  weights_beta  :
  mode          : Weight sum:A*(1-alpha)+B*alpha
  MBW           : False
  CalcMode      : normal
Loading weights [metagodSelfieMix_metagodSelfieMix10] from file
Traceback (most recent call last):
  File "F:\projects\AI\SD3a\automatic\venv\lib\site-packages\gradio\routes.py", line 394, in run_predict
    output = await app.get_blocks().process_api(
  File "F:\projects\AI\SD3a\automatic\venv\lib\site-packages\gradio\blocks.py", line 1075, in process_api
    result = await self.call_function(
  File "F:\projects\AI\SD3a\automatic\venv\lib\site-packages\gradio\blocks.py", line 884, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "F:\projects\AI\SD3a\automatic\venv\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "F:\projects\AI\SD3a\automatic\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "F:\projects\AI\SD3a\automatic\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "F:\projects\AI\SD3a\automatic\extensions\sd-webui-supermerger\scripts\mergers\mergers.py", line 60, in smergegen
    result,currentmodel,modelid,theta_0,metadata = smerge(weights_a,weights_b,model_a,model_b,model_c,base_alpha,base_beta,mode,calcmode,useblocks,custom_name,save_sets,id_sets,wpresets,deep,deepprint=deepprint)
  File "F:\projects\AI\SD3a\automatic\extensions\sd-webui-supermerger\scripts\mergers\mergers.py", line 159, in smerge
    theta_1=load_model_weights_m(model_b,False,True,save).copy()
  File "F:\projects\AI\SD3a\automatic\extensions\sd-webui-supermerger\scripts\mergers\mergers.py", line 374, in load_model_weights_m
    return sd_models.read_state_dict(checkpoint_info.filename,"cuda")
TypeError: read_state_dict() takes 1 positional argument but 2 were given

**Comment by hako-mikan** [comment]
If you use Vladmandic fork, the problem was fixed.

**Comment by hako-mikan** [comment]
https://github.com/hako-mikan/sd-webui-supermerger/discussions/62
