### ISSUE TITLE
Can't merge on runpod

### ISSUE THREAD

**Issue by blnkspceSD** [hako-mikan/sd-webui-supermerger#6]
I can't seem to use this extension on runpod. Am I missing something? Thanks in advance!

```
2023-02-19T05:03:50.062924236Z Traceback (most recent call last):
2023-02-19T05:03:50.062959276Z   File "/workspace/venv/lib/python3.10/site-packages/gradio/routes.py", line 337, in run_predict
2023-02-19T05:03:50.062965927Z     output = await app.get_blocks().process_api(
2023-02-19T05:03:50.062969676Z   File "/workspace/venv/lib/python3.10/site-packages/gradio/blocks.py", line 1015, in process_api
2023-02-19T05:03:50.062973186Z     result = await self.call_function(
2023-02-19T05:03:50.062976346Z   File "/workspace/venv/lib/python3.10/site-packages/gradio/blocks.py", line 833, in call_function
2023-02-19T05:03:50.062979636Z     prediction = await anyio.to_thread.run_sync(
2023-02-19T05:03:50.062988196Z   File "/workspace/venv/lib/python3.10/site-packages/anyio/to_thread.py", line 31, in run_sync
2023-02-19T05:03:50.062991847Z     return await get_asynclib().run_sync_in_worker_thread(
2023-02-19T05:03:50.062995376Z   File "/workspace/venv/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
2023-02-19T05:03:50.062998967Z     return await future
2023-02-19T05:03:50.063002007Z   File "/workspace/venv/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 867, in run
2023-02-19T05:03:50.063005436Z     result = context.run(func, *args)
2023-02-19T05:03:50.063008487Z   File "/workspace/stable-diffusion-webui/extensions/sd-webui-supermerger/scripts/mergers/mergers.py", line 47, in smergegen
2023-02-19T05:03:50.063011936Z     result,currentmodel,modelid,theta_0 = smerge(weights_a,weights_b,model_a,model_b,model_c,base_alpha,base_beta,mode,useblocks,custom_name,save_sets,id_sets,wpresets)
2023-02-19T05:03:50.063015396Z   File "/workspace/stable-diffusion-webui/extensions/sd-webui-supermerger/scripts/mergers/mergers.py", line 95, in smerge
2023-02-19T05:03:50.063018756Z     mergedmodel =[weights_a,weights_b,
2023-02-19T05:03:50.063021887Z   File "/workspace/stable-diffusion-webui/extensions/sd-webui-supermerger/scripts/mergers/mergers.py", line 396, in hashfromname
2023-02-19T05:03:50.063025327Z     checkpoint_info = sd_models.get_closet_checkpoint_match(name)
2023-02-19T05:03:50.063028486Z AttributeError: 'NoneType' object has no attribute 'shorthash'
```

**Comment by hako-mikan** [comment]
This issue was fixed yesterday. Please try the latest version.

**Comment by hako-mikan** [comment]
This problem may be fixed yesterday. Please update and try it.

**Comment by blnkspceSD** [comment]
Works now! Thank you!
