### ISSUE TITLE
Error when trying to create Alpha/Beta XY graph

### ISSUE THREAD

**Issue by puyebu** [hako-mikan/sd-webui-supermerger#64]
I am trying to get comparison between various merges of models, I set X type to alpha and beta and enter `0 1,0.9 0.1,0.7 0.3,0.4 0.6`, however I get following error:
```
XY plot start, mode:Weight sum:A*(1-alpha)+B*alpha, X: alpha and beta, Y: none, MBW: False
xmen:0 1,0.9 0.1,0.7 0.3,0.4 0.6, ymen:, xtype:alpha and beta, ytype:none, weights_a:0, weights_b:0, model_A:modela.safetensors [1234567890],model_B :modelb.safetensors [1234567890], model_C:, alpha:0.5,        beta :0.25, mode:Weight sum:A*(1-alpha)+B*alpha, blocks:False
['0 1', '0.9 0.1', '0.7 0.3', '0.4 0.6']
['']
Twice mode automatically selected)
XY plot: X: alpha and beta, 0 1, Y: none,  (1/4)
Traceback (most recent call last):
  File "/home/useruser/stable-diffusion-webui/venv/lib/python3.10/site-packages/gradio/routes.py", line 394, in run_predict
    output = await app.get_blocks().process_api(
  File "/home/useruser/stable-diffusion-webui/venv/lib/python3.10/site-packages/gradio/blocks.py", line 1075, in process_api
    result = await self.call_function(
  File "/home/useruser/stable-diffusion-webui/venv/lib/python3.10/site-packages/gradio/blocks.py", line 884, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/home/useruser/stable-diffusion-webui/venv/lib/python3.10/site-packages/anyio/to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/home/useruser/stable-diffusion-webui/venv/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "/home/useruser/stable-diffusion-webui/venv/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "/home/useruser/stable-diffusion-webui/extensions/sd-webui-supermerger/scripts/mergers/xyplot.py", line 52, in numanager
    result,currentmodel,xyimage,a,b,c= sgenxyplot(xtype,xmen,ytype,ymen,esettings,
  File "/home/useruser/stable-diffusion-webui/extensions/sd-webui-supermerger/scripts/mergers/xyplot.py", line 309, in sgenxyplot
    usemodelgen(theta_0,model_a,currentmodel)
  File "/home/useruser/stable-diffusion-webui/extensions/sd-webui-supermerger/scripts/mergers/model_util.py", line 780, in usemodelgen
    model.load_state_dict(theta_0, strict=False)
  File "/home/useruser/stable-diffusion-webui/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1624, in load_state_dict
    raise TypeError("Expected state_dict to be dict-like, got {}.".format(type(state_dict)))
TypeError: Expected state_dict to be dict-like, got <class 'NoneType'>.
```

**Comment by puyebu** [comment]
Figured out, wrong merge mode was stuck for some reason and after restart it works as it should.
