### ISSUE TITLE
AssertionError: weights shape mismatch merging v1 and v2, different dims? 

### ISSUE THREAD

**Issue by ladichanjp** [hako-mikan/sd-webui-supermerger#67]
Traceback (most recent call last):
  File "x:\SD\stable-diffusion-webui\venv\lib\site-packages\gradio\routes.py", line 394, in run_predict
    output = await app.get_blocks().process_api(
  File "x:\SD\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1075, in process_api
    result = await self.call_function(
  File "x:\SD\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 884, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "x:\SD\stable-diffusion-webui\venv\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "x:\SD\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "x:\SD\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "x:\SD\stable-diffusion-webui\extensions\sd-webui-supermerger\scripts\mergers\pluslora.py", line 211, in lmerge
    sd = merge_lora_models(ln, lr,settings)
  File "x:\SD\stable-diffusion-webui\extensions\sd-webui-supermerger\scripts\mergers\pluslora.py", line 716, in merge_lora_models
    assert merged_sd[key].size() == lora_sd[key].size(
AssertionError: weights shape mismatch merging v1 and v2, different dims?

**Comment by ladichanjp** [comment]
if i calculate dimension i get this:

Traceback (most recent call last):
  File "x:\SD\stable-diffusion-webui\venv\lib\site-packages\gradio\routes.py", line 394, in run_predict
    output = await app.get_blocks().process_api(
  File "x:\SD\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1075, in process_api
    result = await self.call_function(
  File "x:\SD\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 884, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "x:\SD\stable-diffusion-webui\venv\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "x:\SD\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "x:\SD\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "x:\SD\stable-diffusion-webui\extensions\sd-webui-supermerger\scripts\mergers\pluslora.py", line 102, in calculatedim
    d,t = dimgetter(c_lora.filename)
  File "x:\SD\stable-diffusion-webui\extensions\sd-webui-supermerger\scripts\mergers\pluslora.py", line 555, in dimgetter
    if alpha is None and 'alpha' in key:
TypeError: argument of type 'int' is not iterable

**Comment by hako-mikan** [comment]
What environment are you using? Do you use forks or other tools?
