### ISSUE TITLE
ModuleNotFoundError: No module named 'diffusers'

### ISSUE THREAD

**Issue by superfid2006** [hako-mikan/sd-webui-supermerger#7]
Hello, I encountered the above error after installing this extension.

I installed the extension using the Extensions>Install from URL tab in Automatic1111's WebUI. This extension is now also listed under "extensions".

However, whenever I run "webui-user.bat, the following message appears within the command window:

Error loading script: supermerger.py
Traceback (most recent call last):
  File "D:\Stable-Diffusion\stable-diffusion-webui\modules\scripts.py", line 229, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "D:\Stable-Diffusion\stable-diffusion-webui\modules\script_loading.py", line 11, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\Stable-Diffusion\stable-diffusion-webui\extensions\sd-webui-supermerger\scripts\supermerger.py", line 11, in <module>
    import scripts.mergers.pluslora as pluslora
  File "D:\Stable-Diffusion\stable-diffusion-webui\extensions\sd-webui-supermerger\scripts\mergers\pluslora.py", line 12, in <module>
    from scripts.mergers.model_util import load_models_from_stable_diffusion_checkpoint,filenamecutter,savemodel
  File "D:\Stable-Diffusion\stable-diffusion-webui\extensions\sd-webui-supermerger\scripts\mergers\model_util.py", line 4, in <module>
    from diffusers import AutoencoderKL,  UNet2DConditionModel
ModuleNotFoundError: No module named 'diffusers'

When opening the WebUI in the browser, no new tab for the Supermerger appears.

**Comment by hako-mikan** [comment]
This extension needs "diffusers" module of python, so you must install that. If windows, in the web-ui folder, using the command prompt, type "pip install diffusers"

**Comment by ange321** [comment]
I'm also getting this error. I ran "pip install diffusers" in the web-ui folder before launching.

`Error loading script: supermerger.py
Traceback (most recent call last):
  File "H:\GitHub\stable-diffusion-webui\modules\scripts.py", line 229, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "H:\GitHub\stable-diffusion-webui\modules\script_loading.py", line 11, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "H:\GitHub\stable-diffusion-webui\extensions\sd-webui-supermerger\scripts\supermerger.py", line 11, in <module>
    import scripts.mergers.pluslora as pluslora
  File "H:\GitHub\stable-diffusion-webui\extensions\sd-webui-supermerger\scripts\mergers\pluslora.py", line 12, in <module>
    from scripts.mergers.model_util import load_models_from_stable_diffusion_checkpoint,filenamecutter,savemodel
  File "H:\GitHub\stable-diffusion-webui\extensions\sd-webui-supermerger\scripts\mergers\model_util.py", line 4, in <module>
    from diffusers import AutoencoderKL,  UNet2DConditionModel
ModuleNotFoundError: No module named 'diffusers'`

**Comment by ClashSAN** [comment]
This is expected. It says so 

>Some operations are RAM-heavy & diffusers is required. 



>diffusers must now be installed. on windows, this can be done by typing "pip install diffusers" at the command prompt in the web-ui folder, but it depends on your environment.

it's not auto-install because it is up to the user to install, since installing latest diffusers version may conflict with dreambooth or another extension requiring diffusers.

**Comment by superfid2006** [comment]
The error sadly still persists even after running pip install diffusers in the web-ui folder, where it says
Requirement already satisfied: diffusers in d:\python\python39\lib\site-packages (0.10.2)

Should they be run in the virtual environment activated with .\venv\scripts\activate?
If I try to do so, it says:
Fatal error in launcher: Unable to create process using '"D:\Stable Diffusion\stable-diffusion-webui\venv\Scripts\python.exe"  "D:\Stable-Diffusion\stable-diffusion-webui\venv\Scripts\pip.exe" install diffusers': The system cannot find the file specified.

**Comment by ClashSAN** [comment]
@superfid2006 the readme instructions would imply to install into venv.
If you can get it working for whatever reason, add diffusers tor requirements.txt and remove after running once

**Comment by superfid2006** [comment]
Sadly, adding diffusers still didn't cause executing the webui-user.bat to download the module.
However, I managed to fix this issue by copying the folder 'diffusers' that was installed in my system's main Python folder (D:\Python\Python39\Lib\site-packages\) when running pip install in the WebUI folder into D:\Stable-Diffusion\stable-diffusion-webui\venv\Lib\site-packages. When running the webui, no error message appeared, and Supermerger now appears as a tab.

This might interest you @ange321, maybe you can solve your problem this way as well.
