### ISSUE TITLE
Calculation modes issues/errors

### ISSUE THREAD

**Issue by JilekJosef** [hako-mikan/sd-webui-supermerger#73]
Using Add difference like A+(B-A)*a results to picture full of pure noise (like just random color dots) when cosineA or cosineB is used. Normal and smoothAdd works fine. Using tensor method just throws this error: 
Loading weights [LD-CORE] from file
Stage 1/2: 100%|██████████████████████████████████████████████████████████████████▉| 1131/1133 [00:35<00:00, 31.89it/s]
Traceback (most recent call last):
  File "C:\Users\jilek\Documents\stable-diffusion-webui\venv\lib\site-packages\gradio\routes.py", line 394, in run_predict
    output = await app.get_blocks().process_api(
  File "C:\Users\jilek\Documents\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1075, in process_api
    result = await self.call_function(
  File "C:\Users\jilek\Documents\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 884, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "C:\Users\jilek\Documents\stable-diffusion-webui\venv\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "C:\Users\jilek\Documents\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "C:\Users\jilek\Documents\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "C:\Users\jilek\Documents\stable-diffusion-webui\extensions\sd-webui-supermerger\scripts\mergers\mergers.py", line 65, in smergegen
    result,currentmodel,modelid,theta_0,metadata = smerge(
  File "C:\Users\jilek\Documents\stable-diffusion-webui\extensions\sd-webui-supermerger\scripts\mergers\mergers.py", line 390, in smerge
    talphas = int(theta_0[key].shape[0]*(current_alpha+current_beta-1))
IndexError: tuple index out of range
![00015-2534883930](https://user-images.githubusercontent.com/83363948/236456267-b98f179c-f44b-4b59-9a13-9bff144af037.png)

**Comment by hako-mikan** [comment]
Thanks reporting, may be fixed.
I don't have models which causes errors, so I couldn't test it.
Try it.

**Comment by Trevor-Z** [comment]
Same thing happens here. Using the settings in the image and a simple prompt, with no LoRA's, I get no errors, but an image that is just noise.

Also, I think merges with three models never work for me. When I get normal images, only models A and B are used to generate them, and model C is ignored.

![Screenshot 2023-05-15 174037](https://github.com/hako-mikan/sd-webui-supermerger/assets/13950948/83800870-96e1-4f5b-ba32-0ce3218cdcab)

**Comment by JilekJosef** [comment]
Cosine still does the same pure noise images and tensor calculation mode now doesn't crash but gives the same images as cosine.

**Comment by hako-mikan** [comment]
as written in [calcmode](https://github.com/hako-mikan/sd-webui-supermerger/blob/main/calcmode_en.md), cosine mode can be used in weight sum only.

**Comment by JilekJosef** [comment]
I see, well than it's solved. Thank you for your work.
