### ISSUE TITLE
During "effective elemental checker": could not convert string to float: ''`

### ISSUE THREAD

**Issue by miasik** [hako-mikan/sd-webui-supermerger#75]
version: [2c004060]
During "effective elemental checker" procedure.
Sequential Merge Parameters was filled from "sample.txt":
"IN00:,IN01:,IN02:,IN03:,IN04:,IN05:,IN06:,IN07:,IN08:,IN09:,IN10:,IN11:,M00:|OUT00:,OUT01:,OUT02:,OUT03:,OUT04:,OUT05:,OUT06:,OUT07:,OUT08:,OUT09:,OUT10:,OUT11:"

The error at step two:
`XY plot: X: effective, IN00:, Y: none,  (2/14)
  model A       : insta
  model B       : Vision_v3
  model C       :
  alpha,beta    : (1.0, 1.0)
  weights_alpha :
  weights_beta  :
  mode          : Weight sum:A*(1-alpha)+B*alpha
  MBW           : False
  CalcMode      : normal
  Elemental     : ['', 'IN00::']
  Tensors       :
Loading weights [Vision_v3] from cache
Loading weights [insta] from cache
Stage 1/2:   1%|█▌                                                                                                                                                      | 12/1143 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "e:\SD\automatic1111\venv\lib\site-packages\gradio\routes.py", line 399, in run_predict
    output = await app.get_blocks().process_api(
  File "e:\SD\automatic1111\venv\lib\site-packages\gradio\blocks.py", line 1299, in process_api
    result = await self.call_function(
  File "e:\SD\automatic1111\venv\lib\site-packages\gradio\blocks.py", line 1022, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "e:\SD\automatic1111\venv\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "e:\SD\automatic1111\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "e:\SD\automatic1111\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "E:\SD\automatic1111\extensions\sd-webui-supermerger\scripts\mergers\xyplot.py", line 52, in numanager
    result,currentmodel,xyimage,a,b,c= sgenxyplot(xtype,xmen,ytype,ymen,esettings,
  File "E:\SD\automatic1111\extensions\sd-webui-supermerger\scripts\mergers\xyplot.py", line 316, in sgenxyplot
    _ , currentmodel,modelid,theta_0,_=smerge(weights_a_in,weights_b_in, model_a,model_b,model_c, float(alpha),float(beta),mode,calcmode,
  File "E:\SD\automatic1111\extensions\sd-webui-supermerger\scripts\mergers\mergers.py", line 307, in smerge
    dr = float(dr)
ValueError: could not convert string to float: ''`

**Comment by miasik** [comment]
It works if I use block without colons, but the result is strange.
IN00,IN01,IN02,IN03,IN04,IN05,IN06,IN07,IN08,IN09,IN10,IN11

**Comment by miasik** [comment]
Sorry, my fault :-(

**Comment by hako-mikan** [comment]
I don't mind. Enjoy!
