### ISSUE TITLE
TypeError: gradio.components.Textbox.__init__() got multiple values for keyword argument 'lines'

### ISSUE THREAD

**Issue by edisonblack55555** [hako-mikan/sd-webui-supermerger#81]
Error executing callback ui_tabs_callback for /kaggle/working/stable-diffusion-webui/extensions/sd-webui-supermerger/scripts/supermerger.py
Traceback (most recent call last):
  File "/kaggle/working/stable-diffusion-webui/modules/script_callbacks.py", line 125, in ui_tabs_callback
    res += c.callback() or []
  File "/kaggle/working/stable-diffusion-webui/extensions/sd-webui-supermerger/scripts/supermerger.py", line 227, in on_ui_tabs
    pluslora.on_ui_tabs()
  File "/kaggle/working/stable-diffusion-webui/extensions/sd-webui-supermerger/scripts/mergers/pluslora.py", line 65, in on_ui_tabs
    sml_loraratios = gr.TextArea(label="",lines=10,value=sml_lbwpresets,visible =True,interactive  = True)
  File "/opt/conda/lib/python3.10/site-packages/gradio/templates.py", line 23, in __init__
    super().__init__(lines=7, **kwargs)
TypeError: gradio.components.Textbox.__init__() got multiple values for keyword argument 'lines'

what wrong?

**Comment by hako-mikan** [comment]
Assuming it's a version issue or something, but I've fixed it. Thanks.
