### ISSUE TITLE
The latest version of SD does not display an interface. Can you update and adapt it?

### ISSUE THREAD

**Issue by wzgrx** [hako-mikan/sd-webui-supermerger#85]
Error loading script: supermerger.py
Traceback (most recent call last):
  File "D:\stable-diffusion-webui\modules\scripts.py", line 263, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "D:\stable-diffusion-webui\modules\script_loading.py", line 10, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\stable-diffusion-webui\extensions\sd-webui-supermerger\scripts\supermerger.py", line 15, in <module>
    import scripts.mergers.mergers
  File "D:\stable-diffusion-webui\extensions\sd-webui-supermerger\scripts\mergers\mergers.py", line 17, in <module>
    from fonts.ttf import Roboto
ModuleNotFoundError: No module named 'fonts'

**Comment by wzgrx** [comment]
pip install fonts

Error loading script: supermerger.py
Traceback (most recent call last):
  File "D:\stable-diffusion-webui\modules\scripts.py", line 263, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "D:\stable-diffusion-webui\modules\script_loading.py", line 10, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\stable-diffusion-webui\extensions\sd-webui-supermerger\scripts\supermerger.py", line 15, in <module>
    import scripts.mergers.mergers
  File "D:\stable-diffusion-webui\extensions\sd-webui-supermerger\scripts\mergers\mergers.py", line 17, in <module>
    from fonts.ttf import Roboto
ImportError: cannot import name 'Roboto' from 'fonts.ttf' (D:\stable-diffusion-webui\venv\lib\site-packages\fonts\ttf\__init__.py)

**Comment by hako-mikan** [comment]
May be fixed but i dont use fork so i cannot test it.
Try it.

**Comment by anonCantCode** [comment]
It's not any fork btw; it's the latest version of AUTOMATIC1111 (the dev branch). It drops `fonts` and `font.roboto` from its requirements.
Anyway, I tested and it works fine now.

**Comment by wzgrx** [comment]
Tested in the latest version of dve, it works normally. Thank you for the hard work of the developers

**Comment by Tktw** [comment]
Error occurs in web-ui ver1.3.0 new install.

from mergers.py line 559
```
    def get_font(fontsize):
        try:
            from fonts.ttf import Roboto
            try:
                return ImageFont.truetype(opts.font or Roboto, fontsize)
            except Exception:
                return ImageFont.truetype(Roboto, fontsize)
```
probably…
```
    def get_font(fontsize):
        try:
            from modules.paths_internal import roboto_ttf_file
            try:
                return ImageFont.truetype(opts.font or roboto_ttf_file, fontsize)
            except Exception:
                return ImageFont.truetype(roboto_ttf_file, fontsize)
```
reference
[https://github.com/AUTOMATIC1111/stable-diffusion-webui/commit/1332c46b71b169b889d7df420f3285d9022da5cc](https://github.com/AUTOMATIC1111/stable-diffusion-webui/commit/1332c46b71b169b889d7df420f3285d9022da5cc)
