### ISSUE TITLE
Doesn't work on dev branch of the WebUI

### ISSUE THREAD

**Issue by anonCantCode** [hako-mikan/sd-webui-supermerger#87]
The dev branch drops `fonts` and `font.roboto` from their `requirements.txt`, so they don't get installed by default, which results in this extension not working.
```
Error loading script: supermerger.py
Traceback (most recent call last):
  File "/tmp/stable-diffusion-webui/modules/scripts.py", line 263, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "/tmp/stable-diffusion-webui/modules/script_loading.py", line 10, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/tmp/stable-diffusion-webui/extensions/sd-webui-supermerger/scripts/supermerger.py", line 15, in <module>
    import scripts.mergers.mergers
  File "/tmp/stable-diffusion-webui/extensions/sd-webui-supermerger/scripts/mergers/mergers.py", line 17, in <module>
    from fonts.ttf import Roboto
ModuleNotFoundError: No module named 'fonts'
```

**Comment by anonCantCode** [comment]
Closing cause I realised it's a duplicate lol #85
