### ISSUE TITLE
sequential XY Merge error when using tensor calculation mode with MBW Alpha preset name 

### ISSUE THREAD

**Issue by Katmoget** [hako-mikan/sd-webui-supermerger#88]
Hi,

when trying to use tensor as a calculation method  with MBW Alpha preset name (i.e GRAD_V
GRAD_A etc ) in sequential XY Merge I get the error below, but using the weight itself in the XY merge doesn't throw the error.
I tried different checkpoints and preset names all trigger the same error.

problem was introduced with commit : c56fc54 in mergers.py
changing line : 116 `usebeta = MODES[2] in mode or MODES[3] in mode or calcmode == "tensor"`
back to `usebeta = MODES[2] in mode or MODES[3] in mode`
in the latest commit 7398bd8d seems to fix the issue.

error :
_Applying xformers cross attention optimization.
Loading VAE weights specified in settings: cached vae-ft-mse-840000-ema-pruned.ckpt
XY plot start, mode:Weight sum:A*(1-alpha)+B*alpha, X: mbw alpha , Y: none, MBW: False
xmen:GRAD_V
GRAD_A
, ymen:, xtype:mbw alpha , ytype:none, weights_a:0, weights_b:0, model_A:deliberate_v2.safetensors [9aba26abdf],model_B :timelessDiffusion_timelessDiffusion.ckpt [6e6683719a], model_C:, alpha:0.5,        beta :0.25, mode:Weight sum:A*(1-alpha)+B*alpha, blocks:False
['GRAD_V', 'GRAD_A']
['']
MBW mode enabled
weights GRAD_V imported from presets : 0,1,0.9166666667,0.8333333333,0.75,0.6666666667,0.5833333333,0.5,0.4166666667,0.3333333333,0.25,0.1666666667,0.0833333333,0,0.0833333333,0.1666666667,0.25,0.3333333333,0.4166666667,0.5,0.5833333333,0.6666666667,0.75,0.8333333333,0.9166666667,1.0
XY plot: X: mbw alpha , GRAD_V, Y: none,  (1/2)
Traceback (most recent call last):
  File "D:\stable_diffusion\stable-diffusion-webui\venv\lib\site-packages\gradio\routes.py", line 408, in run_predict
    output = await app.get_blocks().process_api(
  File "D:\stable_diffusion\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1315, in process_api
    result = await self.call_function(
  File "D:\stable_diffusion\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1043, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "D:\stable_diffusion\stable-diffusion-webui\venv\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "D:\stable_diffusion\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "D:\stable_diffusion\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "D:\stable_diffusion\stable-diffusion-webui\extensions\sd-webui-supermerger\scripts\mergers\xyplot.py", line 52, in numanager
    result,currentmodel,xyimage,a,b,c= sgenxyplot(xtype,xmen,ytype,ymen,esettings,
  File "D:\stable_diffusion\stable-diffusion-webui\extensions\sd-webui-supermerger\scripts\mergers\xyplot.py", line 316, in sgenxyplot
    _ , currentmodel,modelid,theta_0,_=smerge(weights_a_in,weights_b_in, model_a,model_b,model_c, float(alpha),float(beta),mode,calcmode,
  File "D:\stable_diffusion\stable-diffusion-webui\extensions\sd-webui-supermerger\scripts\mergers\mergers.py", line 152, in smerge
    weights_b = [float(w) for w in weights_b_t[1].split(',')]
IndexError: list index out of range_

I'm using : WEBUI version: v1.2.1 Commit hash: 89f9faa63388756314e8a1d96cf86bf5e0663045,
python: 3.10.6 • torch: 1.13.1+cu116 • xformers: 0.0.17.dev464 • gradio: 3.29.0 

Thanks

**Comment by hako-mikan** [comment]
There seems to be a problem with the value regarding beta. Tensor mode uses alpha and beta, is the MBW value for beta set correctly?

**Comment by Katmoget** [comment]
I'm confused because tensor worked using the MBW value but not with the MBW preset name set in Alpha only. 

so does this mean it's not possible to use tensor with other calculation method in XY with MBW anymore ?
