### ISSUE TITLE
No module named 'diffusers' error

### ISSUE THREAD

**Issue by lekima** [hako-mikan/sd-webui-supermerger#9]
I've installed diffusers as per the instruction but the error still appears. Any advice?

```
Error loading script: supermerger.py
Traceback (most recent call last):
  File "D:\AI\stable-diffusion-webui\modules\scripts.py", line 229, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "D:\AI\stable-diffusion-webui\modules\script_loading.py", line 11, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\AI\stable-diffusion-webui\extensions\sd-webui-supermerger\scripts\supermerger.py", line 11, in <module>
    import scripts.mergers.pluslora as pluslora
  File "D:\AI\stable-diffusion-webui\extensions\sd-webui-supermerger\scripts\mergers\pluslora.py", line 12, in <module>
    from scripts.mergers.model_util import load_models_from_stable_diffusion_checkpoint,filenamecutter,savemodel
  File "D:\AI\stable-diffusion-webui\extensions\sd-webui-supermerger\scripts\mergers\model_util.py", line 4, in <module>
    from diffusers import AutoencoderKL,  UNet2DConditionModel
ModuleNotFoundError: No module named 'diffusers'
```

**Comment by lekima** [comment]
Solved.

Here is the solution in case you're also encountering the same issue.

You need to enter the virtual environment of the project first, by typing `.\venv\Scripts\activate` in the web-ui folder. Then you can `pip install diffusers`.

**Comment by superfid2006** [comment]
Glad to hear you managed to solve your issue.
I had a similar problem, and for me, activating the virtual environment did not work: https://github.com/hako-mikan/sd-webui-supermerger/issues/7
What DID help, however, was manually copying the diffusers folder I installed by pip installing them while in the webui folder into the corresponding venv folder.

**Comment by hako-mikan** [comment]
The timing of importing "diffusers" has been changed. With this update, some environments can be started without installing "diffusers".
