### ISSUE TITLE
XY Merge ad Generation を使用した場合、calcmodeだとエラーが起きる。

### ISSUE THREAD

**Issue by w-tea** [hako-mikan/sd-webui-supermerger#90]
AUTOMATIC1111 1.3.0でXY Merge ad Generation を使う場合、
normalは問題ないがcosinA/Bだと以下のエラーが出てしまいます。
normalは使えるようなのですが……。

設定
ModelA＋ModelB
Weight sumモード
useMBWにチェック
Hires.fix、latent(nealest)、ステップ10、ノイズ0.55、倍率2

X：mbw alpha
何かプリセット

Y：calcmode
cosineA,cosineB

環境
version: [v1.3.0]  •  python: 3.10.11  •  torch: 2.0.0+cu118  •  xformers: N/A  •  gradio: 3.31.0

エラー内容
`
Traceback (most recent call last):
  File "F:\01_main\venv\lib\site-packages\gradio\routes.py", line 414, in run_predict
    output = await app.get_blocks().process_api(
  File "F:\01_main\venv\lib\site-packages\gradio\blocks.py", line 1323, in process_api
    result = await self.call_function(
  File "F:\01_main\venv\lib\site-packages\gradio\blocks.py", line 1051, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "F:\01_main\venv\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "F:\01_main\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "F:\01_main\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "F:\01_main\extensions\sd-webui-supermerger\scripts\mergers\xyplot.py", line 52, in numanager
    result,currentmodel,xyimage,a,b,c= sgenxyplot(xtype,xmen,ytype,ymen,esettings,
  File "F:\01_main\extensions\sd-webui-supermerger\scripts\mergers\xyplot.py", line 316, in sgenxyplot
    _ , currentmodel,modelid,theta_0,_=smerge(weights_a_in,weights_b_in, model_a,model_b,model_c, float(alpha),float(beta),mode,calcmode,
  File "F:\01_main\extensions\sd-webui-supermerger\scripts\mergers\mergers.py", line 220, in smerge
    sims = np.append(sims,simab.numpy())
RuntimeError: Can't call numpy() on Tensor that requires grad. Use tensor.detach().numpy() instead.
`

**Comment by w-tea** [comment]
なぜか使えるようになったのでcloseしました。
