### ISSUE TITLE
mergining keeps crashing it

### ISSUE THREAD

**Issue by Maki9009** [hako-mikan/sd-webui-supermerger#94]
trying to merge 2 dreambooth models and c model is 1.5 base model, 

but it keeps crashing with this error 

Traceback (most recent call last):
  File "E:\stable-diffusion-webui\venv\lib\site-packages\gradio\routes.py", line 414, in run_predict
    output = await app.get_blocks().process_api(
  File "E:\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1323, in process_api
    result = await self.call_function(
  File "E:\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1051, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "E:\stable-diffusion-webui\venv\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "E:\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "E:\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "E:\stable-diffusion-webui\extensions\sd-webui-supermerger\scripts\mergers\mergers.py", line 64, in smergegen
    result,currentmodel,modelid,theta_0,metadata = smerge(
  File "E:\stable-diffusion-webui\extensions\sd-webui-supermerger\scripts\mergers\mergers.py", line 245, in smerge
    if usebeta and (not key in theta_2) and (not theta_2 == {}) :
UnboundLocalError: local variable 'theta_2' referenced before assignment

**Comment by hako-mikan** [comment]
Thanks reporting, may be fixed.

**Comment by Maki9009** [comment]
okay it no longer crashes, but the message on the webui says it has merged my model, yet i cant find it in my models folder, and the terminal stopped and froze at loading the vae, which is confusion. because it loaded the same model twice... Model A, not Model B

**Comment by hako-mikan** [comment]
Let me know the detailed settings and what the error is.

**Comment by hobolyra** [comment]
> 


> okay it no longer crashes, but the message on the webui says it has merged my model, yet i cant find it in my models folder, and the terminal stopped and froze at loading the vae, which is confusion. because it loaded the same model twice... Model A, not Model B

Same issue here, in that the error occurs after it tries saving the merge. WIll try to get the error log in a sec.

**Comment by hako-mikan** [comment]
Model may be broken.
Try to resave model using toolkit.
https://github.com/arenasys/stable-diffusion-webui-model-toolkit
